import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type UITheme = "default" | "warcraft" | "cyberpunk" | "forest" | "ocean" | "pokemon" | "yugioh" | "chucknorris" | "lotr";

/* ------------------------------------------------------------------ */
/*  Themed-text dictionary                                             */
/* ------------------------------------------------------------------ */

export interface ThemeText {
  // Branding
  appName: string;
  tagline: string;

  // Navigation
  dashboard: string;
  executions: string;
  workflowDefs: string;
  taskDefs: string;
  taskQueues: string;

  // Actions
  startWorkflow: string;
  startingWorkflow: string;
  search: string;
  newDefinition: string;
  newTaskDef: string;
  viewAll: string;
  cancel: string;
  delete: string;
  edit: string;

  // Dashboard
  dashboardTitle: string;
  dashboardSubtitle: string;
  running: string;
  completed: string;
  failed: string;
  queuedTasks: string;
  healthy: string;
  offline: string;
  statusDistribution: string;
  workflowDefinitions: string;
  taskDefinitions: string;
  registeredDefinitions: string;
  registeredTaskTypes: string;
  recentExecutions: string;
  noRecentExecutions: string;

  // Executions page
  executionsTitle: string;
  autoRefresh: string;
  live: string;
  searchAndFilter: string;
  searchPlaceholder: string;
  allWorkflowTypes: string;
  results: string;
  showing: string;
  workflow: string;
  status: string;
  started: string;
  ended: string;
  actions: string;
  prev: string;
  next: string;
  page: string;
  of: string;
  pause: string;
  terminate: string;
  resume: string;
  restart: string;
  terminateWorkflow: string;
  terminateConfirm: string;

  // Workflow Defs page
  workflowDefsTitle: string;
  filterDefinitions: string;
  noWorkflowDefs: string;
  noDefsMatch: string;
  name: string;
  version: string;
  tasks: string;
  description: string;
  timeout: string;
  startExecution: string;
  viewJson: string;
  cloneAndEdit: string;
  createWorkflowDef: string;
  editWorkflowDef: string;
  deleteWorkflowDef: string;

  // Task Defs page
  taskDefsTitle: string;
  filterTaskDefs: string;
  noTaskDefs: string;
  retryCount: string;
  responseTimeout: string;
  owner: string;
  testRun: string;
  view: string;
  createTaskDef: string;
  deleteTaskDef: string;
  taskInput: string;
  runTest: string;

  // Task Queues page
  taskQueuesTitle: string;
  totalQueued: string;
  filterQueues: string;
  activeQueues: string;
  noQueuesMatch: string;
  noTasksInQueue: string;

  // Command palette
  searchAll: string;
  pages: string;
  noResults: string;

  // Start workflow dialog
  startWorkflowTitle: string;
  startWorkflowDesc: string;
  workflowLabel: string;
  versionLabel: string;
  inputLabel: string;
  correlationId: string;
  selectWorkflow: string;
  loadingWorkflows: string;
  noWorkflowsFound: string;

  // Breadcrumbs
  breadcrumbDashboard: string;
  breadcrumbExecutions: string;
  breadcrumbDefinitions: string;
  breadcrumbTaskDefs: string;
  breadcrumbQueues: string;

  // Loading
  loading: string;

  // Toasts
  toastWorkflowTerminated: string;
  toastWorkflowPaused: string;
  toastWorkflowResumed: string;
  toastWorkflowRestarted: string;
  toastWorkflowRetried: string;
  toastWorkflowStarted: string;
  toastWorkflowDefSaved: string;
  toastTaskDefCreated: string;
  toastDeleted: string;
  toastInvalidJson: string;

  // Workflow detail
  workflowNotFound: string;
  retry: string;
  tasksTab: string;
  timeline: string;
  diagram: string;
  input: string;
  output: string;
  info: string;
  task: string;
  type: string;
  worker: string;
  reason: string;
  viewSubWorkflow: string;
  loadingWorkflowDef: string;
  workflowIdLabel: string;
  correlationIdLabel: string;
  priority: string;
  updated: string;
  scheduled: string;
  pollCount: string;
  duration: string;

  // Confirm dialog
  confirm: string;
  pleaseWait: string;

  // Status filters
  allStatuses: string;

  // Workflow builder
  createWorkflow: string;
  saveWorkflow: string;
  visualBuilder: string;
  jsonEditor: string;
  saving: string;
  addTask: string;
  noTasksYet: string;
  tasksSequentialHint: string;
  workflowNameRequired: string;
  addAtLeastOneTask: string;
  allTasksNeedRefName: string;
  previewJson: string;

  // Workflow builder settings
  workflowSettings: string;
  nameRequired: string;
  descriptionPlaceholder: string;
  timeoutSeconds: string;
  ownerEmail: string;
  failureWorkflow: string;
  optional: string;
  inputParameters: string;
  inputParamPlaceholder: string;
  inputParamHint: string;

  // Task card
  unnamed: string;
  moveUp: string;
  moveDown: string;
  duplicate: string;
  remove: string;
  taskType: string;
  referenceNameRequired: string;
  taskName: string;
  selectRegisteredTask: string;
  startDelay: string;

  // Task def form
  retryLogic: string;
  retryFixed: string;
  retryExponential: string;
  retryLinear: string;
  retryDelay: string;
  timeoutPolicy: string;
  timeoutPolicyTimeOut: string;
  timeoutPolicyAlert: string;
  timeoutPolicyRetry: string;
  responseTimeoutLabel: string;
  concurrentExecLimit: string;
  inputKeys: string;
  outputKeys: string;
  creating: string;
  createFromJson: string;
  form: string;
  json: string;

  // Task type fields
  subWorkflowConfig: string;
  workflowName: string;
  versionOptional: string;
  parallelBranches: string;
  addBranch: string;
  forkJoinNote: string;
  decisionConfig: string;
  caseExpression: string;
  caseValueParam: string;
  cases: string;
  addCase: string;
  doWhileConfig: string;
  loopCondition: string;
  loopBodyTasks: string;

  // Task input fields
  source: string;
  customValue: string;
  selectParameter: string;
  noInputKeys: string;
  selectTaskForInputs: string;
  provideParamsJson: string;
  pickSourceHint: string;

  // Misc
  testRunDescription: string;
  autoParseHint: string;
  deleteConfirmSuffix: string;
  liveInterval: string;
  copyToClipboard: string;
  none: string;

  // Relative time
  justNow: string;
  secondsAgo: string;
  minutesAgo: string;
  hoursAgo: string;
  daysAgo: string;

  // Layout & chrome
  expandSidebar: string;
  collapseSidebar: string;
  commandPalette: string;
  themeLabel: string;
  uiTheme: string;
  autoRefreshOn: string;
  autoRefreshOff: string;

  // Toggle labels
  fields: string;

  // Placeholders & hints
  valueFor: string;
  typeAndPressEnter: string;
  typeKeyAndEnter: string;
  taskDescriptionHint: string;
  noTimeoutHint: string;
  unlimitedHint: string;
  latest: string;
  referenceName: string;
  caseValue: string;

  // Diagram node labels
  diagramStart: string;
  diagramEnd: string;
  diagramFork: string;
  diagramJoin: string;
  diagramSwitch: string;
  diagramSubWf: string;
  diagramLoop: string;
  diagramEvent: string;
  diagramHttp: string;
  diagramWait: string;
  diagramTask: string;

  // Test workflow
  testWorkflowDesc: string;

  // About page
  about: string;
  aboutTitle: string;
  aboutSubtitle: string;
  aboutFooter: string;
  breadcrumbAbout: string;
}

/* ------------------------------------------------------------------ */
/*  Per-theme text                                                     */
/* ------------------------------------------------------------------ */

const defaultText: ThemeText = {
  appName: "Rust Conductor",
  tagline: "Conductor-compliant engine",
  dashboard: "Dashboard",
  executions: "Executions",
  workflowDefs: "Workflow Defs",
  taskDefs: "Task Defs",
  taskQueues: "Task Queues",
  startWorkflow: "Start Workflow",
  startingWorkflow: "Starting...",
  search: "Search…",
  newDefinition: "New Definition",
  newTaskDef: "New Task Def",
  viewAll: "View All",
  cancel: "Cancel",
  delete: "Delete",
  edit: "Edit",
  dashboardTitle: "Dashboard",
  dashboardSubtitle: "Rust Conductor orchestration overview",
  running: "Running",
  completed: "Completed",
  failed: "Failed",
  queuedTasks: "Queued Tasks",
  healthy: "Healthy",
  offline: "Offline",
  statusDistribution: "Workflow Status Distribution",
  workflowDefinitions: "Workflow Definitions",
  taskDefinitions: "Task Definitions",
  registeredDefinitions: "registered definitions",
  registeredTaskTypes: "registered task types",
  recentExecutions: "Recent Executions",
  noRecentExecutions: "No recent executions. Start your first workflow!",
  executionsTitle: "Workflow Executions",
  autoRefresh: "Auto-refresh",
  live: "Live",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by name, ID, or correlation ID...",
  allWorkflowTypes: "All Workflow Types",
  results: "results",
  showing: "showing",
  workflow: "Workflow",
  status: "Status",
  started: "Started",
  ended: "Ended",
  actions: "Actions",
  prev: "Prev",
  next: "Next",
  page: "Page",
  of: "of",
  pause: "Pause",
  terminate: "Terminate",
  resume: "Resume",
  restart: "Restart",
  terminateWorkflow: "Terminate Workflow",
  terminateConfirm: "Are you sure you want to terminate this workflow execution? This will stop all running tasks.",
  workflowDefsTitle: "Workflow Definitions",
  filterDefinitions: "Filter definitions...",
  noWorkflowDefs: "No workflow definitions yet. Create your first one!",
  noDefsMatch: "No definitions match your search.",
  name: "Name",
  version: "Version",
  tasks: "Tasks",
  description: "Description",
  timeout: "Timeout",
  startExecution: "Start Execution",
  viewJson: "View JSON",
  cloneAndEdit: "Clone & Edit",
  createWorkflowDef: "Create Workflow Definition",
  editWorkflowDef: "Edit Workflow Definition",
  deleteWorkflowDef: "Delete Workflow Definition",
  taskDefsTitle: "Task Definitions",
  filterTaskDefs: "Filter task definitions...",
  noTaskDefs: "No task definitions yet. Create your first one!",
  retryCount: "Retry Count",
  responseTimeout: "Response Timeout",
  owner: "Owner",
  testRun: "Test Run",
  view: "View",
  createTaskDef: "Create Task Definition",
  deleteTaskDef: "Delete Task Definition",
  taskInput: "Task Input",
  runTest: "Run Test",
  taskQueuesTitle: "Task Queues",
  totalQueued: "total queued",
  filterQueues: "Filter queues…",
  activeQueues: "Active Queues",
  noQueuesMatch: "No queues match your filter",
  noTasksInQueue: "No tasks in queue",
  searchAll: "Search workflows, tasks, pages…",
  pages: "Pages",
  noResults: "No results found.",
  startWorkflowTitle: "Start Workflow Execution",
  startWorkflowDesc: "Select a workflow definition and provide input to start a new execution.",
  workflowLabel: "Workflow *",
  versionLabel: "Version",
  inputLabel: "Input",
  correlationId: "Correlation ID (optional)",
  selectWorkflow: "Select workflow...",
  loadingWorkflows: "Loading workflows…",
  noWorkflowsFound: "No workflow definitions found. Create one first.",
  breadcrumbDashboard: "Dashboard",
  breadcrumbExecutions: "Executions",
  breadcrumbDefinitions: "Workflow Definitions",
  breadcrumbTaskDefs: "Task Definitions",
  breadcrumbQueues: "Task Queues",
  loading: "Loading...",
  toastWorkflowTerminated: "Workflow terminated",
  toastWorkflowPaused: "Workflow paused",
  toastWorkflowResumed: "Workflow resumed",
  toastWorkflowRestarted: "Workflow restarted",
  toastWorkflowRetried: "Workflow retried",
  toastWorkflowStarted: "Workflow started successfully",
  toastWorkflowDefSaved: "Workflow definition saved",
  toastTaskDefCreated: "Task definition(s) created",
  toastDeleted: "Deleted",
  toastInvalidJson: "Invalid JSON input",
  workflowNotFound: "Workflow not found",
  retry: "Retry",
  tasksTab: "Tasks",
  timeline: "Timeline",
  diagram: "Diagram",
  input: "Input",
  output: "Output",
  info: "Info",
  task: "Task",
  type: "Type",
  worker: "Worker",
  reason: "Reason",
  viewSubWorkflow: "View Sub-Workflow",
  loadingWorkflowDef: "Loading workflow definition...",
  workflowIdLabel: "Workflow ID",
  correlationIdLabel: "Correlation ID",
  priority: "Priority",
  updated: "Updated",
  scheduled: "Scheduled",
  pollCount: "Poll Count",
  duration: "Duration",
  confirm: "Confirm",
  pleaseWait: "Please wait...",
  allStatuses: "All",
  createWorkflow: "Create Workflow",
  saveWorkflow: "Save Workflow",
  visualBuilder: "Visual Builder",
  jsonEditor: "JSON Editor",
  saving: "Saving...",
  addTask: "Add Task",
  noTasksYet: "No tasks yet. Click \"Add Task\" to get started.",
  tasksSequentialHint: "Tasks are executed sequentially in the order listed.",
  workflowNameRequired: "Workflow name is required.",
  addAtLeastOneTask: "Add at least one task.",
  allTasksNeedRefName: "All tasks need a reference name.",
  previewJson: "Preview JSON",
  workflowSettings: "Workflow Settings",
  nameRequired: "Name *",
  descriptionPlaceholder: "What does this workflow do?",
  timeoutSeconds: "Timeout (seconds)",
  ownerEmail: "Owner Email",
  failureWorkflow: "Failure Workflow",
  optional: "Optional",
  inputParameters: "Input Parameters",
  inputParamPlaceholder: "Type a parameter name and press Enter",
  inputParamHint: "These become available as sources for task input mapping.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Remove",
  taskType: "Task Type",
  referenceNameRequired: "Reference Name *",
  taskName: "Task Name",
  selectRegisteredTask: "Select a registered task...",
  startDelay: "Start Delay (s)",
  retryLogic: "Retry Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential Backoff",
  retryLinear: "Linear Backoff",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Policy",
  timeoutPolicyTimeOut: "Time Out Workflow",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Retry",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Exec Limit",
  inputKeys: "Input Keys",
  outputKeys: "Output Keys",
  creating: "Creating...",
  createFromJson: "Create from JSON",
  form: "Form",
  json: "JSON",
  subWorkflowConfig: "Sub-Workflow Configuration",
  workflowName: "Workflow Name",
  versionOptional: "Version (optional)",
  parallelBranches: "Parallel Branches",
  addBranch: "Add Branch",
  forkJoinNote: "Note: A JOIN task will be automatically appended.",
  decisionConfig: "Decision/Switch Configuration",
  caseExpression: "Case Expression",
  caseValueParam: "Case Value Param",
  cases: "Cases",
  addCase: "Add Case",
  doWhileConfig: "Do-While Loop Configuration",
  loopCondition: "Loop Condition",
  loopBodyTasks: "Loop Body Tasks",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select parameter...",
  noInputKeys: "This task has no defined input keys.",
  selectTaskForInputs: "Select a registered task to see its input parameters, or switch to JSON mode.",
  provideParamsJson: "Provide the needed parameters in JSON mode.",
  pickSourceHint: "Pick a source first (workflow input or a previous task), then select the specific parameter.",
  testRunDescription: "This will create a test workflow and start it. The task will appear in its queue, ready to be polled.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This action cannot be undone.",
  liveInterval: "Live (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Expand sidebar",
  collapseSidebar: "Collapse sidebar",
  commandPalette: "Command Palette",
  themeLabel: "Theme",
  uiTheme: "UI Theme",
  autoRefreshOn: "Auto-refresh ON (5s)",
  autoRefreshOff: "Auto-refresh OFF",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Type a key and press Enter",
  taskDescriptionHint: "What does this task do?",
  noTimeoutHint: "0 = no timeout",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Reference name",
  caseValue: "Case value",
  diagramStart: "Start",
  diagramEnd: "End",
  diagramFork: "\u2442 Fork",
  diagramJoin: "\u2295 Join",
  diagramSwitch: "\u25C7 Switch",
  diagramSubWf: "\u21B3 SubWF",
  diagramLoop: "\u21BB Loop",
  diagramEvent: "\u26A1 Event",
  diagramHttp: "\uD83C\uDF10 HTTP",
  diagramWait: "\u231B Wait",
  diagramTask: "\u25AA Task",
  testWorkflowDesc: "Auto-generated test workflow for task",
  about: "About",
  aboutTitle: "About Rust Conductor",
  aboutSubtitle: "A fully Rust-based, Conductor-compatible microservice orchestrator — and the technologies that power it.",
  aboutFooter: "Built with ❤ in Rust — open source, high performance, production ready.",
  breadcrumbAbout: "About",
};

const warcraftText: ThemeText = {
  appName: "War Conductor",
  tagline: "For the Horde… and the Alliance",
  dashboard: "War Room",
  executions: "Battle Log",
  workflowDefs: "Battle Plans",
  taskDefs: "Unit Orders",
  taskQueues: "Rally Points",
  startWorkflow: "Launch Campaign",
  startingWorkflow: "Rallying forces...",
  search: "Scout…",
  newDefinition: "Forge New Plan",
  newTaskDef: "New Unit Order",
  viewAll: "View All Battles",
  cancel: "Retreat",
  delete: "Destroy",
  edit: "Reforge",
  dashboardTitle: "War Room",
  dashboardSubtitle: "Strategic command overview of all operations",
  running: "In Battle",
  completed: "Victorious",
  failed: "Defeated",
  queuedTasks: "Awaiting Orders",
  healthy: "Fortified",
  offline: "Under Siege",
  statusDistribution: "Battle Status Overview",
  workflowDefinitions: "Battle Plans",
  taskDefinitions: "Unit Orders",
  registeredDefinitions: "battle plans forged",
  registeredTaskTypes: "unit types trained",
  recentExecutions: "Recent Campaigns",
  noRecentExecutions: "No campaigns yet. Launch your first assault!",
  executionsTitle: "Battle Log",
  autoRefresh: "Scout Reports",
  live: "Scouting",
  searchAndFilter: "Intelligence & Recon",
  searchPlaceholder: "Search campaigns, units, or battle IDs...",
  allWorkflowTypes: "All Campaign Types",
  results: "campaigns found",
  showing: "revealing",
  workflow: "Campaign",
  status: "Report",
  started: "Deployed",
  ended: "Concluded",
  actions: "Commands",
  prev: "Fall Back",
  next: "Advance",
  page: "Front",
  of: "of",
  pause: "Hold Position",
  terminate: "Sound Retreat",
  resume: "Charge!",
  restart: "Regroup",
  terminateWorkflow: "Sound the Retreat",
  terminateConfirm: "Are you sure you want to call a retreat? All active units will stand down.",
  workflowDefsTitle: "Battle Plans",
  filterDefinitions: "Search battle plans...",
  noWorkflowDefs: "No battle plans drawn. Forge your first strategy!",
  noDefsMatch: "No plans match your search.",
  name: "Name",
  version: "Revision",
  tasks: "Units",
  description: "Intelligence",
  timeout: "Duration",
  startExecution: "Deploy",
  viewJson: "View Scroll",
  cloneAndEdit: "Copy & Reforge",
  createWorkflowDef: "Forge Battle Plan",
  editWorkflowDef: "Reforge Battle Plan",
  deleteWorkflowDef: "Burn Battle Plan",
  taskDefsTitle: "Unit Orders",
  filterTaskDefs: "Search unit orders...",
  noTaskDefs: "No unit orders yet. Train your first unit!",
  retryCount: "Rally Attempts",
  responseTimeout: "Response Window",
  owner: "Commander",
  testRun: "Skirmish",
  view: "Inspect",
  createTaskDef: "Draft Unit Order",
  deleteTaskDef: "Disband Unit Order",
  taskInput: "Unit Supplies",
  runTest: "Begin Skirmish",
  taskQueuesTitle: "Rally Points",
  totalQueued: "units awaiting orders",
  filterQueues: "Search rally points…",
  activeQueues: "Active Rally Points",
  noQueuesMatch: "No rally points match your search",
  noTasksInQueue: "All units deployed — no one awaiting orders",
  searchAll: "Scout campaigns, units, rally points…",
  pages: "Locations",
  noResults: "No intelligence found.",
  startWorkflowTitle: "Launch New Campaign",
  startWorkflowDesc: "Choose a battle plan and supply resources to begin a new campaign.",
  workflowLabel: "Battle Plan *",
  versionLabel: "Revision",
  inputLabel: "Supplies",
  correlationId: "War Banner (optional)",
  selectWorkflow: "Choose battle plan...",
  loadingWorkflows: "Consulting war council…",
  noWorkflowsFound: "No battle plans exist. Forge one first.",
  breadcrumbDashboard: "War Room",
  breadcrumbExecutions: "Battle Log",
  breadcrumbDefinitions: "Battle Plans",
  breadcrumbTaskDefs: "Unit Orders",
  breadcrumbQueues: "Rally Points",
  loading: "Awaiting scouts...",
  toastWorkflowTerminated: "Campaign ended by command",
  toastWorkflowPaused: "Troops holding position",
  toastWorkflowResumed: "Forces marching again",
  toastWorkflowRestarted: "Campaign relaunched",
  toastWorkflowRetried: "Reinforcements sent",
  toastWorkflowStarted: "Campaign launched!",
  toastWorkflowDefSaved: "Battle plan inscribed",
  toastTaskDefCreated: "Unit order(s) filed",
  toastDeleted: "Destroyed",
  toastInvalidJson: "Invalid scroll contents",
  workflowNotFound: "Campaign not found in the archives",
  retry: "Reinforce",
  tasksTab: "Orders",
  timeline: "Battle Timeline",
  diagram: "War Map",
  input: "Supplies",
  output: "Spoils",
  info: "Intel",
  task: "Order",
  type: "Type",
  worker: "Soldier",
  reason: "Cause of Defeat",
  viewSubWorkflow: "View Sub-Campaign",
  loadingWorkflowDef: "Unrolling battle scroll...",
  workflowIdLabel: "Campaign ID",
  correlationIdLabel: "Alliance ID",
  priority: "Priority",
  updated: "Last Report",
  scheduled: "Mustered",
  pollCount: "Scout Reports",
  duration: "Campaign Duration",
  confirm: "Confirm",
  pleaseWait: "Awaiting reinforcements...",
  allStatuses: "All",
  createWorkflow: "Create Battle Plan",
  saveWorkflow: "Save Battle Plan",
  visualBuilder: "War Room",
  jsonEditor: "Scroll Editor",
  saving: "Inscribing...",
  addTask: "Add Order",
  noTasksYet: "No orders yet. Command your troops!",
  tasksSequentialHint: "Orders are executed sequentially as written.",
  workflowNameRequired: "Battle plan name is required.",
  addAtLeastOneTask: "Add at least one order.",
  allTasksNeedRefName: "All orders need a codename.",
  previewJson: "Preview Scroll",
  workflowSettings: "Battle Plan Settings",
  nameRequired: "Codename *",
  descriptionPlaceholder: "What is this campaign's objective?",
  timeoutSeconds: "Time Limit (seconds)",
  ownerEmail: "Commander",
  failureWorkflow: "Retreat Plan",
  optional: "Optional",
  inputParameters: "War Supplies",
  inputParamPlaceholder: "Type a supply name and press Enter",
  inputParamHint: "These become available as resources for troop orders.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Remove",
  taskType: "Order Type",
  referenceNameRequired: "Codename *",
  taskName: "Order Name",
  selectRegisteredTask: "Select a registered unit...",
  startDelay: "March Delay (s)",
  retryLogic: "Retry Tactics",
  retryFixed: "Fixed",
  retryExponential: "Exponential Siege",
  retryLinear: "Linear Advance",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Strategy",
  timeoutPolicyTimeOut: "Abort Campaign",
  timeoutPolicyAlert: "Signal Only",
  timeoutPolicyRetry: "Reinforce",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Squads",
  inputKeys: "Supply Keys",
  outputKeys: "Spoil Keys",
  creating: "Summoning...",
  createFromJson: "Create from Scroll",
  form: "Form",
  json: "Scroll",
  subWorkflowConfig: "Sub-Campaign Configuration",
  workflowName: "Campaign Name",
  versionOptional: "Age (optional)",
  parallelBranches: "Flanking Columns",
  addBranch: "Add Flank",
  forkJoinNote: "Note: A rally point will be automatically appended.",
  decisionConfig: "Strategic Decision",
  caseExpression: "Condition",
  caseValueParam: "Scout Report Value",
  cases: "Outcomes",
  addCase: "Add Outcome",
  doWhileConfig: "Siege Loop Configuration",
  loopCondition: "Siege Condition",
  loopBodyTasks: "Siege Orders",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select supply...",
  noInputKeys: "This order has no defined supply keys.",
  selectTaskForInputs: "Select a registered unit to see its supply needs, or switch to scroll mode.",
  provideParamsJson: "Provide the needed supplies in scroll mode.",
  pickSourceHint: "Pick a supply source first, then select the specific resource.",
  testRunDescription: "This will create a test campaign and deploy it. The order will appear in its rally point.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), scrolls, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Scouting (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "moments ago",
  secondsAgo: "s past",
  minutesAgo: "m past",
  hoursAgo: "h past",
  daysAgo: "d past",
  expandSidebar: "Open war table",
  collapseSidebar: "Collapse war table",
  commandPalette: "War Orders",
  themeLabel: "Theme",
  uiTheme: "Realm Style",
  autoRefreshOn: "Scout active (5s)",
  autoRefreshOff: "Scout idle",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter a rune and press Enter",
  taskDescriptionHint: "Describe this order's purpose",
  noTimeoutHint: "0 = no retreat timer",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Codename",
  caseValue: "Case value",
  diagramStart: "\u2694 Begin",
  diagramEnd: "\uD83C\uDFF0 End",
  diagramFork: "\u2442 Fork",
  diagramJoin: "\u2295 Rally",
  diagramSwitch: "\u25C7 Decision",
  diagramSubWf: "\u21B3 Sub-Campaign",
  diagramLoop: "\u21BB Siege",
  diagramEvent: "\u26A1 Signal",
  diagramHttp: "\uD83C\uDF10 Dispatch",
  diagramWait: "\u231B Hold",
  diagramTask: "\u25AA Order",
  testWorkflowDesc: "Auto-generated test campaign for unit",
  about: "Lore",
  aboutTitle: "Lore of the War Conductor",
  aboutSubtitle: "The forges that built this war machine — every weapon and alliance.",
  aboutFooter: "Forged in Rust — Lok'tar ogar!",
  breadcrumbAbout: "Lore",
};

const cyberpunkText: ThemeText = {
  appName: "NETRUNNER",
  tagline: "Neural orchestration protocol v2.0",
  dashboard: "Neural Hub",
  executions: "Process Stack",
  workflowDefs: "Protocols",
  taskDefs: "Subroutines",
  taskQueues: "Thread Pool",
  startWorkflow: "Execute Protocol",
  startingWorkflow: "Jacking in...",
  search: "Scan…",
  newDefinition: "Upload Protocol",
  newTaskDef: "New Subroutine",
  viewAll: "Full Stack Trace",
  cancel: "Abort",
  delete: "Purge",
  edit: "Patch",
  dashboardTitle: "Neural Hub",
  dashboardSubtitle: "Real-time system telemetry and process overview",
  running: "Active",
  completed: "Terminated",
  failed: "Crashed",
  queuedTasks: "Queued Threads",
  healthy: "Online",
  offline: "Flatlined",
  statusDistribution: "Process State Matrix",
  workflowDefinitions: "Protocols",
  taskDefinitions: "Subroutines",
  registeredDefinitions: "uploaded protocols",
  registeredTaskTypes: "registered subroutines",
  recentExecutions: "Recent Processes",
  noRecentExecutions: "Stack empty. Execute your first protocol.",
  executionsTitle: "Process Stack",
  autoRefresh: "Auto-Scan",
  live: "Live Feed",
  searchAndFilter: "Query & Filter",
  searchPlaceholder: "Scan processes, IDs, or correlation tags...",
  allWorkflowTypes: "All Protocol Types",
  results: "hits",
  showing: "displaying",
  workflow: "Protocol",
  status: "State",
  started: "Initiated",
  ended: "Terminated",
  actions: "Ops",
  prev: "Prev Block",
  next: "Next Block",
  page: "Block",
  of: "of",
  pause: "Freeze",
  terminate: "Kill Process",
  resume: "Unfreeze",
  restart: "Reboot",
  terminateWorkflow: "Kill Process",
  terminateConfirm: "Confirm process termination? All active threads will be killed immediately.",
  workflowDefsTitle: "Protocols",
  filterDefinitions: "Scan protocols...",
  noWorkflowDefs: "No protocols uploaded. Jack in and create one.",
  noDefsMatch: "No protocols match your query.",
  name: "Identifier",
  version: "Build",
  tasks: "Nodes",
  description: "Docs",
  timeout: "TTL",
  startExecution: "Execute",
  viewJson: "View Source",
  cloneAndEdit: "Fork & Patch",
  createWorkflowDef: "Upload Protocol",
  editWorkflowDef: "Patch Protocol",
  deleteWorkflowDef: "Purge Protocol",
  taskDefsTitle: "Subroutines",
  filterTaskDefs: "Scan subroutines...",
  noTaskDefs: "No subroutines registered. Upload your first module.",
  retryCount: "Retry Limit",
  responseTimeout: "RTT Limit",
  owner: "Maintainer",
  testRun: "Dry Run",
  view: "Inspect",
  createTaskDef: "Register Subroutine",
  deleteTaskDef: "Purge Subroutine",
  taskInput: "Input Payload",
  runTest: "Run Dry",
  taskQueuesTitle: "Thread Pool",
  totalQueued: "threads queued",
  filterQueues: "Filter threads…",
  activeQueues: "Active Threads",
  noQueuesMatch: "No threads match your filter",
  noTasksInQueue: "Thread pool empty — all cycles idle",
  searchAll: "Scan protocols, subroutines, threads…",
  pages: "Modules",
  noResults: "No data found in the net.",
  startWorkflowTitle: "Execute New Protocol",
  startWorkflowDesc: "Select a protocol definition and inject payload to initiate execution.",
  workflowLabel: "Protocol *",
  versionLabel: "Build",
  inputLabel: "Payload",
  correlationId: "Trace ID (optional)",
  selectWorkflow: "Select protocol...",
  loadingWorkflows: "Scanning network…",
  noWorkflowsFound: "No protocols on the net. Upload one first.",
  breadcrumbDashboard: "Neural Hub",
  breadcrumbExecutions: "Process Stack",
  breadcrumbDefinitions: "Protocols",
  breadcrumbTaskDefs: "Subroutines",
  breadcrumbQueues: "Thread Pool",
  loading: "Scanning...",
  toastWorkflowTerminated: "Process terminated",
  toastWorkflowPaused: "Process suspended",
  toastWorkflowResumed: "Process resumed",
  toastWorkflowRestarted: "Process rebooted",
  toastWorkflowRetried: "Process re-executed",
  toastWorkflowStarted: "Process initialized",
  toastWorkflowDefSaved: "Blueprint uploaded",
  toastTaskDefCreated: "Subroutine(s) compiled",
  toastDeleted: "Purged",
  toastInvalidJson: "Corrupt data packet",
  workflowNotFound: "Process not found in the net",
  retry: "Re-exec",
  tasksTab: "Threads",
  timeline: "Chrono-Log",
  diagram: "Network Map",
  input: "Input Stream",
  output: "Output Stream",
  info: "Telemetry",
  task: "Thread",
  type: "Module",
  worker: "Node",
  reason: "Error Trace",
  viewSubWorkflow: "Jack Into Sub-Process",
  loadingWorkflowDef: "Downloading blueprint...",
  workflowIdLabel: "Process ID",
  correlationIdLabel: "Link ID",
  priority: "Priority Level",
  updated: "Last Sync",
  scheduled: "Queued",
  pollCount: "Ping Count",
  duration: "Uptime",
  confirm: "Execute",
  pleaseWait: "Compiling...",
  allStatuses: "All",
  createWorkflow: "Compile Blueprint",
  saveWorkflow: "Upload Blueprint",
  visualBuilder: "Visual IDE",
  jsonEditor: "Raw Code",
  saving: "Uploading...",
  addTask: "Add Thread",
  noTasksYet: "No threads yet. Jack in and start coding.",
  tasksSequentialHint: "Threads execute sequentially in the pipeline.",
  workflowNameRequired: "Blueprint name is required.",
  addAtLeastOneTask: "Add at least one thread.",
  allTasksNeedRefName: "All threads need a handle.",
  previewJson: "Preview Code",
  workflowSettings: "Blueprint Config",
  nameRequired: "Handle *",
  descriptionPlaceholder: "What does this blueprint do?",
  timeoutSeconds: "Timeout (seconds)",
  ownerEmail: "Operator",
  failureWorkflow: "Crash Handler",
  optional: "Optional",
  inputParameters: "Input Streams",
  inputParamPlaceholder: "Type a stream name and press Enter",
  inputParamHint: "These become available as data sources for thread mapping.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Clone",
  remove: "Delete",
  taskType: "Thread Type",
  referenceNameRequired: "Handle *",
  taskName: "Thread Name",
  selectRegisteredTask: "Select a registered subroutine...",
  startDelay: "Boot Delay (s)",
  retryLogic: "Retry Protocol",
  retryFixed: "Fixed",
  retryExponential: "Exponential Backoff",
  retryLinear: "Linear Backoff",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Protocol",
  timeoutPolicyTimeOut: "Kill Process",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Re-exec",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Max Parallel Threads",
  inputKeys: "Input Keys",
  outputKeys: "Output Keys",
  creating: "Compiling...",
  createFromJson: "Compile from Code",
  form: "Form",
  json: "Code",
  subWorkflowConfig: "Sub-Process Configuration",
  workflowName: "Blueprint Name",
  versionOptional: "Version (optional)",
  parallelBranches: "Parallel Threads",
  addBranch: "Add Thread",
  forkJoinNote: "Note: A sync barrier will be automatically appended.",
  decisionConfig: "Conditional Branch",
  caseExpression: "Condition Expression",
  caseValueParam: "Switch Variable",
  cases: "Cases",
  addCase: "Add Case",
  doWhileConfig: "Loop Configuration",
  loopCondition: "Loop Condition",
  loopBodyTasks: "Loop Body",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select stream...",
  noInputKeys: "This thread has no defined input keys.",
  selectTaskForInputs: "Select a registered subroutine to see its inputs, or switch to code mode.",
  provideParamsJson: "Provide the needed parameters in code mode.",
  pickSourceHint: "Pick a data source first, then select the specific stream.",
  testRunDescription: "This will create a test process and execute it. The thread will appear in its pool.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This action is irreversible.",
  liveInterval: "Live (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "null",
  justNow: "just now",
  secondsAgo: "s elapsed",
  minutesAgo: "m elapsed",
  hoursAgo: "h elapsed",
  daysAgo: "d elapsed",
  expandSidebar: "Expand panel",
  collapseSidebar: "Collapse panel",
  commandPalette: "Command Terminal",
  themeLabel: "Skin",
  uiTheme: "Interface Skin",
  autoRefreshOn: "Live feed ON (5s)",
  autoRefreshOff: "Live feed OFF",
  fields: "Fields",
  valueFor: "Payload for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter key and press Enter",
  taskDescriptionHint: "What does this routine do?",
  noTimeoutHint: "0 = no timeout",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Handle",
  caseValue: "Branch value",
  diagramStart: "\u25B6 Init",
  diagramEnd: "\u23F9 Halt",
  diagramFork: "\u2442 Fork",
  diagramJoin: "\u2295 Merge",
  diagramSwitch: "\u25C7 Branch",
  diagramSubWf: "\u21B3 SubProc",
  diagramLoop: "\u21BB Loop",
  diagramEvent: "\u26A1 Signal",
  diagramHttp: "\uD83C\uDF10 NetCall",
  diagramWait: "\u231B Idle",
  diagramTask: "\u25AA Thread",
  testWorkflowDesc: "Auto-generated test blueprint for routine",
  about: "Specs",
  aboutTitle: "System Specs // NETRUNNER",
  aboutSubtitle: "Full hardware and software manifest — every chip, every daemon.",
  aboutFooter: "Compiled in Rust // zero bugs, zero mercy.",
  breadcrumbAbout: "Specs",
};

const forestText: ThemeText = {
  appName: "Grove Keeper",
  tagline: "Tending the roots of orchestration",
  dashboard: "Clearing",
  executions: "Trail Log",
  workflowDefs: "Growth Plans",
  taskDefs: "Seed Catalog",
  taskQueues: "Root Network",
  startWorkflow: "Plant Seed",
  startingWorkflow: "Planting...",
  search: "Forage…",
  newDefinition: "New Growth Plan",
  newTaskDef: "New Seed Type",
  viewAll: "View Full Trail",
  cancel: "Step Back",
  delete: "Uproot",
  edit: "Prune",
  dashboardTitle: "The Clearing",
  dashboardSubtitle: "A peaceful overview of the grove's activity",
  running: "Growing",
  completed: "Bloomed",
  failed: "Withered",
  queuedTasks: "Dormant Seeds",
  healthy: "Thriving",
  offline: "Drought",
  statusDistribution: "Growth Distribution",
  workflowDefinitions: "Growth Plans",
  taskDefinitions: "Seed Catalog",
  registeredDefinitions: "growth plans mapped",
  registeredTaskTypes: "seed types cataloged",
  recentExecutions: "Recent Growth",
  noRecentExecutions: "No growth yet. Plant your first seed!",
  executionsTitle: "Trail Log",
  autoRefresh: "Wind Updates",
  live: "Listening",
  searchAndFilter: "Search & Sift",
  searchPlaceholder: "Search trails, seeds, or growth IDs...",
  allWorkflowTypes: "All Growth Types",
  results: "findings",
  showing: "uncovering",
  workflow: "Growth",
  status: "State",
  started: "Sprouted",
  ended: "Settled",
  actions: "Tending",
  prev: "Earlier",
  next: "Further",
  page: "Patch",
  of: "of",
  pause: "Rest",
  terminate: "Harvest",
  resume: "Nurture",
  restart: "Replant",
  terminateWorkflow: "Harvest Early",
  terminateConfirm: "Are you sure you want to harvest this growth early? All active branches will be trimmed.",
  workflowDefsTitle: "Growth Plans",
  filterDefinitions: "Search growth plans...",
  noWorkflowDefs: "No growth plans yet. Map your first one!",
  noDefsMatch: "No plans match your search.",
  name: "Name",
  version: "Season",
  tasks: "Steps",
  description: "Notes",
  timeout: "Lifespan",
  startExecution: "Plant",
  viewJson: "View Map",
  cloneAndEdit: "Graft & Edit",
  createWorkflowDef: "Map New Growth Plan",
  editWorkflowDef: "Edit Growth Plan",
  deleteWorkflowDef: "Uproot Growth Plan",
  taskDefsTitle: "Seed Catalog",
  filterTaskDefs: "Search seed catalog...",
  noTaskDefs: "No seeds cataloged yet. Add your first seed type!",
  retryCount: "Germination Tries",
  responseTimeout: "Response Window",
  owner: "Gardener",
  testRun: "Test Sprout",
  view: "Examine",
  createTaskDef: "Catalog New Seed",
  deleteTaskDef: "Remove from Catalog",
  taskInput: "Soil & Nutrients",
  runTest: "Sprout Test",
  taskQueuesTitle: "Root Network",
  totalQueued: "seeds in the soil",
  filterQueues: "Search roots…",
  activeQueues: "Active Roots",
  noQueuesMatch: "No roots match your search",
  noTasksInQueue: "All soil is resting — no seeds pending",
  searchAll: "Search growth, seeds, roots…",
  pages: "Groves",
  noResults: "Nothing found in the grove.",
  startWorkflowTitle: "Plant New Seed",
  startWorkflowDesc: "Choose a growth plan and provide nutrients to begin cultivation.",
  workflowLabel: "Growth Plan *",
  versionLabel: "Season",
  inputLabel: "Nutrients",
  correlationId: "Garden Tag (optional)",
  selectWorkflow: "Choose growth plan...",
  loadingWorkflows: "Consulting the elders…",
  noWorkflowsFound: "No growth plans exist. Map one first.",
  breadcrumbDashboard: "Clearing",
  breadcrumbExecutions: "Trail Log",
  breadcrumbDefinitions: "Growth Plans",
  breadcrumbTaskDefs: "Seed Catalog",
  breadcrumbQueues: "Root Network",
  loading: "Listening to the wind...",
  toastWorkflowTerminated: "Growth cycle ended",
  toastWorkflowPaused: "Growth dormant",
  toastWorkflowResumed: "Growth resumed",
  toastWorkflowRestarted: "Cycle replanted",
  toastWorkflowRetried: "Re-seeded",
  toastWorkflowStarted: "Seeds planted!",
  toastWorkflowDefSaved: "Blueprint pressed into bark",
  toastTaskDefCreated: "Seed(s) cataloged",
  toastDeleted: "Composted",
  toastInvalidJson: "Rotten seed data",
  workflowNotFound: "Growth not found in the grove",
  retry: "Re-seed",
  tasksTab: "Branches",
  timeline: "Growth Rings",
  diagram: "Canopy Map",
  input: "Soil",
  output: "Harvest",
  info: "Field Notes",
  task: "Branch",
  type: "Species",
  worker: "Gardener",
  reason: "Blight Report",
  viewSubWorkflow: "View Sub-Growth",
  loadingWorkflowDef: "Reading growth rings...",
  workflowIdLabel: "Growth ID",
  correlationIdLabel: "Plot ID",
  priority: "Urgency",
  updated: "Last Tended",
  scheduled: "Planned",
  pollCount: "Inspections",
  duration: "Growing Season",
  confirm: "Confirm",
  pleaseWait: "Germinating...",
  allStatuses: "All",
  createWorkflow: "Plant Blueprint",
  saveWorkflow: "Save Blueprint",
  visualBuilder: "Garden Planner",
  jsonEditor: "Seed Data",
  saving: "Pressing...",
  addTask: "Add Branch",
  noTasksYet: "No branches yet. Start planting!",
  tasksSequentialHint: "Branches grow sequentially along the trunk.",
  workflowNameRequired: "Blueprint name is required.",
  addAtLeastOneTask: "Add at least one branch.",
  allTasksNeedRefName: "All branches need a tag.",
  previewJson: "Preview Seed Data",
  workflowSettings: "Garden Blueprint",
  nameRequired: "Name *",
  descriptionPlaceholder: "What does this growth cycle do?",
  timeoutSeconds: "Season Length (seconds)",
  ownerEmail: "Head Gardener",
  failureWorkflow: "Blight Response",
  optional: "Optional",
  inputParameters: "Soil Nutrients",
  inputParamPlaceholder: "Type a nutrient name and press Enter",
  inputParamHint: "These become available as resources for branch growth.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Propagate",
  remove: "Prune",
  taskType: "Branch Type",
  referenceNameRequired: "Tag *",
  taskName: "Branch Name",
  selectRegisteredTask: "Select a registered seed...",
  startDelay: "Germination Delay (s)",
  retryLogic: "Regrowth Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Regrowth Delay (s)",
  timeoutPolicy: "Season Policy",
  timeoutPolicyTimeOut: "End Season",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Re-seed",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Plots",
  inputKeys: "Nutrient Keys",
  outputKeys: "Harvest Keys",
  creating: "Planting...",
  createFromJson: "Plant from Seed Data",
  form: "Form",
  json: "Seed Data",
  subWorkflowConfig: "Sub-Growth Configuration",
  workflowName: "Blueprint Name",
  versionOptional: "Season (optional)",
  parallelBranches: "Parallel Branches",
  addBranch: "Add Branch",
  forkJoinNote: "Note: Branches will converge at a natural junction.",
  decisionConfig: "Forking Path",
  caseExpression: "Condition",
  caseValueParam: "Soil Sample",
  cases: "Paths",
  addCase: "Add Path",
  doWhileConfig: "Growth Loop Configuration",
  loopCondition: "Growth Condition",
  loopBodyTasks: "Loop Branches",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select nutrient...",
  noInputKeys: "This branch has no defined nutrient keys.",
  selectTaskForInputs: "Select a registered seed to see its nutrients, or switch to seed data mode.",
  provideParamsJson: "Provide the needed nutrients in seed data mode.",
  pickSourceHint: "Pick a nutrient source first, then select the specific element.",
  testRunDescription: "This will create a test growth cycle and start it. The branch will appear in the root network.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Growing (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Open canopy",
  collapseSidebar: "Close canopy",
  commandPalette: "Forest Guide",
  themeLabel: "Theme",
  uiTheme: "Grove Style",
  autoRefreshOn: "Growth watch ON (5s)",
  autoRefreshOff: "Growth watch OFF",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter a seed and press Enter",
  taskDescriptionHint: "What does this seed do?",
  noTimeoutHint: "0 = no season limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Seedling name",
  caseValue: "Branch value",
  diagramStart: "\uD83C\uDF31 Sprout",
  diagramEnd: "\uD83C\uDF42 Harvest",
  diagramFork: "\u2442 Branch",
  diagramJoin: "\u2295 Merge",
  diagramSwitch: "\u25C7 Fork Path",
  diagramSubWf: "\u21B3 Undergrowth",
  diagramLoop: "\u21BB Cycle",
  diagramEvent: "\u26A1 Signal",
  diagramHttp: "\uD83C\uDF10 Pollen",
  diagramWait: "\u231B Dormant",
  diagramTask: "\u25AA Seed",
  testWorkflowDesc: "Auto-generated test trail for seed",
  about: "Roots",
  aboutTitle: "Roots of the Grove",
  aboutSubtitle: "The seeds and soils that nourish this living system.",
  aboutFooter: "Grown in Rust — rooted deep, branching wide.",
  breadcrumbAbout: "Roots",
};

const oceanText: ThemeText = {
  appName: "Tidal Engine",
  tagline: "Navigating the currents of orchestration",
  dashboard: "Lighthouse",
  executions: "Voyage Log",
  workflowDefs: "Current Charts",
  taskDefs: "Crew Roster",
  taskQueues: "Harbor Queue",
  startWorkflow: "Set Sail",
  startingWorkflow: "Casting off...",
  search: "Scan horizon…",
  newDefinition: "Chart New Course",
  newTaskDef: "New Crew Spec",
  viewAll: "Full Log",
  cancel: "Dock",
  delete: "Scuttle",
  edit: "Refit",
  dashboardTitle: "The Lighthouse",
  dashboardSubtitle: "A sweeping view across all maritime operations",
  running: "At Sea",
  completed: "Arrived",
  failed: "Shipwrecked",
  queuedTasks: "Anchored",
  healthy: "Clear Skies",
  offline: "Storm Warning",
  statusDistribution: "Fleet Status Overview",
  workflowDefinitions: "Current Charts",
  taskDefinitions: "Crew Roster",
  registeredDefinitions: "routes charted",
  registeredTaskTypes: "crew types registered",
  recentExecutions: "Recent Voyages",
  noRecentExecutions: "No voyages yet. Set sail on your first mission!",
  executionsTitle: "Voyage Log",
  autoRefresh: "Lookout",
  live: "Watching",
  searchAndFilter: "Chart & Filter",
  searchPlaceholder: "Search voyages, crew, or passage IDs...",
  allWorkflowTypes: "All Voyage Types",
  results: "passages found",
  showing: "surfacing",
  workflow: "Voyage",
  status: "Condition",
  started: "Launched",
  ended: "Docked",
  actions: "Helm",
  prev: "Astern",
  next: "Ahead",
  page: "Log",
  of: "of",
  pause: "Drop Anchor",
  terminate: "Abandon Ship",
  resume: "Weigh Anchor",
  restart: "Relaunch",
  terminateWorkflow: "Abandon Ship",
  terminateConfirm: "Are you sure you want to abandon this voyage? All active crew will be recalled.",
  workflowDefsTitle: "Current Charts",
  filterDefinitions: "Search charts...",
  noWorkflowDefs: "No charts drawn. Chart your first course!",
  noDefsMatch: "No charts match your search.",
  name: "Name",
  version: "Edition",
  tasks: "Waypoints",
  description: "Notes",
  timeout: "Voyage Time",
  startExecution: "Launch",
  viewJson: "View Chart",
  cloneAndEdit: "Copy & Refit",
  createWorkflowDef: "Chart New Course",
  editWorkflowDef: "Refit Current Chart",
  deleteWorkflowDef: "Scuttle Chart",
  taskDefsTitle: "Crew Roster",
  filterTaskDefs: "Search crew roster...",
  noTaskDefs: "No crew registered yet. Recruit your first mate!",
  retryCount: "Rallies",
  responseTimeout: "Signal Timeout",
  owner: "Captain",
  testRun: "Sea Trial",
  view: "Inspect",
  createTaskDef: "Recruit Crew",
  deleteTaskDef: "Discharge Crew",
  taskInput: "Provisions",
  runTest: "Begin Trial",
  taskQueuesTitle: "Harbor Queue",
  totalQueued: "vessels at anchor",
  filterQueues: "Search harbor…",
  activeQueues: "Active Berths",
  noQueuesMatch: "No vessels match your search",
  noTasksInQueue: "Harbor is clear — all ships at sea",
  searchAll: "Search voyages, crew, harbors…",
  pages: "Ports",
  noResults: "Nothing found on the horizon.",
  startWorkflowTitle: "Set Sail on New Voyage",
  startWorkflowDesc: "Select a chart and load provisions to begin a new voyage.",
  workflowLabel: "Chart *",
  versionLabel: "Edition",
  inputLabel: "Provisions",
  correlationId: "Ship Name (optional)",
  selectWorkflow: "Choose chart...",
  loadingWorkflows: "Reading the tides…",
  noWorkflowsFound: "No charts available. Draw one first.",
  breadcrumbDashboard: "Lighthouse",
  breadcrumbExecutions: "Voyage Log",
  breadcrumbDefinitions: "Current Charts",
  breadcrumbTaskDefs: "Crew Roster",
  breadcrumbQueues: "Harbor Queue",
  loading: "Watching the tide...",
  toastWorkflowTerminated: "Voyage scuttled",
  toastWorkflowPaused: "Anchor dropped",
  toastWorkflowResumed: "Anchor weighed — underway",
  toastWorkflowRestarted: "Voyage relaunched",
  toastWorkflowRetried: "Course re-plotted",
  toastWorkflowStarted: "Voyage launched!",
  toastWorkflowDefSaved: "Chart saved to the log",
  toastTaskDefCreated: "Crew assignment(s) filed",
  toastDeleted: "Cast overboard",
  toastInvalidJson: "Corrupt navigational data",
  workflowNotFound: "Voyage not found in the harbor log",
  retry: "Re-plot",
  tasksTab: "Crew",
  timeline: "Tide Chart",
  diagram: "Sea Chart",
  input: "Cargo",
  output: "Catch",
  info: "Ship's Log",
  task: "Crew Member",
  type: "Role",
  worker: "Sailor",
  reason: "Reason for Capsizing",
  viewSubWorkflow: "View Sub-Voyage",
  loadingWorkflowDef: "Reading the sea chart...",
  workflowIdLabel: "Voyage ID",
  correlationIdLabel: "Fleet ID",
  priority: "Urgency",
  updated: "Last Sighted",
  scheduled: "Charted",
  pollCount: "Soundings",
  duration: "Voyage Duration",
  confirm: "Confirm",
  pleaseWait: "Trimming sails...",
  allStatuses: "All",
  createWorkflow: "Chart New Voyage",
  saveWorkflow: "Save Chart",
  visualBuilder: "Chart Room",
  jsonEditor: "Raw Log",
  saving: "Charting...",
  addTask: "Add Crew",
  noTasksYet: "No crew assigned yet. Recruit your first sailor!",
  tasksSequentialHint: "Crew tasks execute in docking order.",
  workflowNameRequired: "Chart name is required.",
  addAtLeastOneTask: "Assign at least one crew member.",
  allTasksNeedRefName: "All crew members need a call sign.",
  previewJson: "Preview Log",
  workflowSettings: "Voyage Settings",
  nameRequired: "Name *",
  descriptionPlaceholder: "What is this voyage's mission?",
  timeoutSeconds: "Timeout (seconds)",
  ownerEmail: "Captain",
  failureWorkflow: "Distress Signal",
  optional: "Optional",
  inputParameters: "Cargo Manifest",
  inputParamPlaceholder: "Type a cargo item and press Enter",
  inputParamHint: "These become available as supplies for crew tasks.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Remove",
  taskType: "Crew Role",
  referenceNameRequired: "Call Sign *",
  taskName: "Crew Name",
  selectRegisteredTask: "Select a registered role...",
  startDelay: "Boarding Delay (s)",
  retryLogic: "Retry Protocol",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Policy",
  timeoutPolicyTimeOut: "Abandon Voyage",
  timeoutPolicyAlert: "Signal Only",
  timeoutPolicyRetry: "Re-plot",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Vessels",
  inputKeys: "Cargo Keys",
  outputKeys: "Catch Keys",
  creating: "Launching...",
  createFromJson: "Chart from Log",
  form: "Form",
  json: "Log",
  subWorkflowConfig: "Sub-Voyage Configuration",
  workflowName: "Chart Name",
  versionOptional: "Edition (optional)",
  parallelBranches: "Parallel Fleets",
  addBranch: "Add Fleet",
  forkJoinNote: "Note: Fleets will rendezvous at a harbor.",
  decisionConfig: "Navigation Decision",
  caseExpression: "Condition",
  caseValueParam: "Wind Reading",
  cases: "Routes",
  addCase: "Add Route",
  doWhileConfig: "Patrol Loop Configuration",
  loopCondition: "Patrol Condition",
  loopBodyTasks: "Patrol Orders",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select cargo...",
  noInputKeys: "This crew role has no defined cargo keys.",
  selectTaskForInputs: "Select a registered role to see its cargo needs, or switch to log mode.",
  provideParamsJson: "Provide the needed cargo in log mode.",
  pickSourceHint: "Pick a supply source first, then select the specific cargo.",
  testRunDescription: "This will chart a test voyage and launch it. The crew task will appear in the harbor queue.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Tide Watch (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Extend gangway",
  collapseSidebar: "Retract gangway",
  commandPalette: "Ship's Log",
  themeLabel: "Theme",
  uiTheme: "Hull Design",
  autoRefreshOn: "Sonar active (5s)",
  autoRefreshOff: "Sonar off",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Log a bearing and press Enter",
  taskDescriptionHint: "What mission does this crew run?",
  noTimeoutHint: "0 = no time limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Call sign",
  caseValue: "Heading value",
  diagramStart: "\u2693 Launch",
  diagramEnd: "\uD83C\uDFF4 Port",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Regroup",
  diagramSwitch: "\u25C7 Navigate",
  diagramSubWf: "\u21B3 Sub-Voyage",
  diagramLoop: "\u21BB Patrol",
  diagramEvent: "\u26A1 Beacon",
  diagramHttp: "\uD83C\uDF10 Radio",
  diagramWait: "\u231B Drift",
  diagramTask: "\u25AA Task",
  testWorkflowDesc: "Auto-generated test voyage for crew",
  about: "Charts",
  aboutTitle: "Nautical Charts",
  aboutSubtitle: "The vessels, instruments, and currents that chart this course.",
  aboutFooter: "Forged in Rust — anchored and seaworthy.",
  breadcrumbAbout: "Charts",
};

const pokemonText: ThemeText = {
  appName: "PokéConductor",
  tagline: "Gotta orchestrate 'em all!",
  dashboard: "Pokédex Hub",
  executions: "Battle Log",
  workflowDefs: "Move Sets",
  taskDefs: "Pokédex",
  taskQueues: "PC Box",
  startWorkflow: "Choose You!",
  startingWorkflow: "Throwing Poké Ball...",
  search: "Pokédex scan…",
  newDefinition: "New Move Set",
  newTaskDef: "Register Pokémon",
  viewAll: "View Full Pokédex",
  cancel: "Run Away",
  delete: "Release",
  edit: "Evolve",
  dashboardTitle: "Pokédex Hub",
  dashboardSubtitle: "Your journey overview — badges, battles, and beyond",
  running: "In Battle",
  completed: "Caught!",
  failed: "Fainted",
  queuedTasks: "In PC Box",
  healthy: "Full HP",
  offline: "Fainted",
  statusDistribution: "Battle Results",
  workflowDefinitions: "Move Sets",
  taskDefinitions: "Pokédex",
  registeredDefinitions: "move sets learned",
  registeredTaskTypes: "Pokémon registered",
  recentExecutions: "Recent Battles",
  noRecentExecutions: "No battles yet. Choose your starter!",
  executionsTitle: "Battle Log",
  autoRefresh: "Auto-Scan",
  live: "Scanning",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by trainer, Pokémon, or battle ID...",
  allWorkflowTypes: "All Move Sets",
  results: "entries found",
  showing: "scanning",
  workflow: "Battle",
  status: "Result",
  started: "Began",
  ended: "Finished",
  actions: "Moves",
  prev: "Back",
  next: "Forward",
  page: "Route",
  of: "of",
  pause: "Switch Out",
  terminate: "Forfeit",
  resume: "Switch In",
  restart: "Rematch",
  terminateWorkflow: "Forfeit Match",
  terminateConfirm: "Are you sure you want to forfeit? All active Pokémon will return to their balls.",
  workflowDefsTitle: "Move Sets",
  filterDefinitions: "Search move sets...",
  noWorkflowDefs: "No move sets yet. Visit Professor Oak!",
  noDefsMatch: "No move sets match your search.",
  name: "Name",
  version: "Gen",
  tasks: "Moves",
  description: "Entry",
  timeout: "Duration",
  startExecution: "Use Move!",
  viewJson: "View Data",
  cloneAndEdit: "Breed & Train",
  createWorkflowDef: "Create Move Set",
  editWorkflowDef: "Edit Move Set",
  deleteWorkflowDef: "Forget Move Set",
  taskDefsTitle: "Pokédex",
  filterTaskDefs: "Search Pokédex...",
  noTaskDefs: "Pokédex is empty. Catch your first Pokémon!",
  retryCount: "PP",
  responseTimeout: "Speed Stat",
  owner: "Trainer",
  testRun: "Test Battle",
  view: "Inspect",
  createTaskDef: "Register Pokémon",
  deleteTaskDef: "Release Pokémon",
  taskInput: "Held Items",
  runTest: "Battle!",
  taskQueuesTitle: "PC Box",
  totalQueued: "Pokémon stored",
  filterQueues: "Search boxes…",
  activeQueues: "Active Boxes",
  noQueuesMatch: "No boxes match your search",
  noTasksInQueue: "All boxes are empty — everyone's on your team",
  searchAll: "Search battles, Pokémon, moves…",
  pages: "Regions",
  noResults: "No Pokémon found.",
  startWorkflowTitle: "Choose Your Pokémon!",
  startWorkflowDesc: "Pick a move set and equip held items to start a new battle.",
  workflowLabel: "Move Set *",
  versionLabel: "Generation",
  inputLabel: "Held Items",
  correlationId: "Trainer ID (optional)",
  selectWorkflow: "Choose move set...",
  loadingWorkflows: "Consulting Professor Oak…",
  noWorkflowsFound: "No move sets available. Create one first.",
  breadcrumbDashboard: "Pokédex Hub",
  breadcrumbExecutions: "Battle Log",
  breadcrumbDefinitions: "Move Sets",
  breadcrumbTaskDefs: "Pokédex",
  breadcrumbQueues: "PC Box",
  loading: "Loading Pokédex...",
  toastWorkflowTerminated: "Battle forfeited!",
  toastWorkflowPaused: "Pokémon returned to ball",
  toastWorkflowResumed: "Go! Pokémon!",
  toastWorkflowRestarted: "Rematch started!",
  toastWorkflowRetried: "Used Revive!",
  toastWorkflowStarted: "Battle started!",
  toastWorkflowDefSaved: "Move set registered!",
  toastTaskDefCreated: "Pokémon registered!",
  toastDeleted: "Released to the wild",
  toastInvalidJson: "Invalid Pokédex data",
  workflowNotFound: "Battle not found in your journey",
  retry: "Use Revive",
  tasksTab: "Pokémon",
  timeline: "Battle Timeline",
  diagram: "Battle Map",
  input: "Held Items",
  output: "Rewards",
  info: "Trainer Card",
  task: "Pokémon",
  type: "Type",
  worker: "Trainer",
  reason: "Cause of Fainting",
  viewSubWorkflow: "View Sub-Battle",
  loadingWorkflowDef: "Consulting Pokédex...",
  workflowIdLabel: "Battle ID",
  correlationIdLabel: "Trainer ID",
  priority: "Priority",
  updated: "Last Healed",
  scheduled: "Queued",
  pollCount: "Encounters",
  duration: "Battle Duration",
  confirm: "Confirm",
  pleaseWait: "Healing Pokémon...",
  allStatuses: "All",
  createWorkflow: "Create Move Set",
  saveWorkflow: "Save Move Set",
  visualBuilder: "Visual Builder",
  jsonEditor: "Data Editor",
  saving: "Saving...",
  addTask: "Add Move",
  noTasksYet: "No moves yet. Teach your first move!",
  tasksSequentialHint: "Moves are used sequentially in battle order.",
  workflowNameRequired: "Move set name is required.",
  addAtLeastOneTask: "Add at least one move.",
  allTasksNeedRefName: "All moves need a name.",
  previewJson: "Preview Data",
  workflowSettings: "Move Set Settings",
  nameRequired: "Name *",
  descriptionPlaceholder: "What does this move set do?",
  timeoutSeconds: "PP Timeout (seconds)",
  ownerEmail: "Trainer Email",
  failureWorkflow: "Faint Handler",
  optional: "Optional",
  inputParameters: "Held Items",
  inputParamPlaceholder: "Type an item name and press Enter",
  inputParamHint: "These become available as equipment for battle moves.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Breed",
  remove: "Release",
  taskType: "Move Type",
  referenceNameRequired: "Nickname *",
  taskName: "Move Name",
  selectRegisteredTask: "Select a registered Pokémon...",
  startDelay: "Charge Time (s)",
  retryLogic: "Revival Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Revival Delay (s)",
  timeoutPolicy: "Timeout Policy",
  timeoutPolicyTimeOut: "Forfeit Battle",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Use Revive",
  responseTimeoutLabel: "Speed Stat Timeout (s)",
  concurrentExecLimit: "Party Size Limit",
  inputKeys: "Item Keys",
  outputKeys: "Reward Keys",
  creating: "Catching...",
  createFromJson: "Import from Pokédex",
  form: "Form",
  json: "Data",
  subWorkflowConfig: "Sub-Battle Configuration",
  workflowName: "Move Set Name",
  versionOptional: "Generation (optional)",
  parallelBranches: "Double Battle Lanes",
  addBranch: "Add Lane",
  forkJoinNote: "Note: Lanes converge after the double battle.",
  decisionConfig: "Type Advantage Branch",
  caseExpression: "Condition",
  caseValueParam: "Type Check",
  cases: "Matchups",
  addCase: "Add Matchup",
  doWhileConfig: "Training Loop",
  loopCondition: "Training Condition",
  loopBodyTasks: "Training Moves",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select item...",
  noInputKeys: "This move has no defined item keys.",
  selectTaskForInputs: "Select a Pokémon to see its items, or switch to data mode.",
  provideParamsJson: "Provide items in data mode.",
  pickSourceHint: "Pick an item source first, then select the specific item.",
  testRunDescription: "This will create a test battle and start it. The move will appear in the PC Box.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Scanning (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Open Pokédex",
  collapseSidebar: "Close Pokédex",
  commandPalette: "Quick Move",
  themeLabel: "Theme",
  uiTheme: "Region Style",
  autoRefreshOn: "Radar active (5s)",
  autoRefreshOff: "Radar off",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter a move and press Enter",
  taskDescriptionHint: "Describe this Pokémon's move",
  noTimeoutHint: "0 = no PP limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Move name",
  caseValue: "Route value",
  diagramStart: "\uD83C\uDFAE Begin",
  diagramEnd: "\uD83C\uDFC6 Finish",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Reunite",
  diagramSwitch: "\u25C7 Choose",
  diagramSubWf: "\u21B3 Side-Quest",
  diagramLoop: "\u21BB Grind",
  diagramEvent: "\u26A1 Encounter",
  diagramHttp: "\uD83C\uDF10 Trade",
  diagramWait: "\u231B Rest",
  diagramTask: "\u25AA Move",
  testWorkflowDesc: "Auto-generated test battle for Pokémon",
  about: "Pokédex",
  aboutTitle: "Tech Pokédex",
  aboutSubtitle: "Every technology catalogued — gotta catch 'em all!",
  aboutFooter: "Built with Rust — it's super effective!",
  breadcrumbAbout: "Pokédex",
};

const yugiohText: ThemeText = {
  appName: "Duel Engine",
  tagline: "It's time to d-d-d-duel!",
  dashboard: "Duel Arena",
  executions: "Duel Log",
  workflowDefs: "Deck Builder",
  taskDefs: "Card Catalog",
  taskQueues: "Graveyard",
  startWorkflow: "Activate!",
  startingWorkflow: "Drawing card...",
  search: "Search deck…",
  newDefinition: "Build Deck",
  newTaskDef: "New Card",
  viewAll: "View All Duels",
  cancel: "End Turn",
  delete: "Banish",
  edit: "Re-equip",
  dashboardTitle: "Duel Arena",
  dashboardSubtitle: "The heart of the cards guides your orchestration",
  running: "Dueling",
  completed: "Victory",
  failed: "Defeated",
  queuedTasks: "Set Cards",
  healthy: "Life Points Full",
  offline: "Life Points Zero",
  statusDistribution: "Duel Results Distribution",
  workflowDefinitions: "Deck Builder",
  taskDefinitions: "Card Catalog",
  registeredDefinitions: "decks constructed",
  registeredTaskTypes: "cards cataloged",
  recentExecutions: "Recent Duels",
  noRecentExecutions: "No duels yet. Activate your first trap card!",
  executionsTitle: "Duel Log",
  autoRefresh: "Auto-Draw",
  live: "Drawing",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by duelist, card, or duel ID...",
  allWorkflowTypes: "All Deck Types",
  results: "records found",
  showing: "revealing",
  workflow: "Duel",
  status: "Result",
  started: "Initiated",
  ended: "Concluded",
  actions: "Moves",
  prev: "Prev Turn",
  next: "Next Turn",
  page: "Turn",
  of: "of",
  pause: "Set Face-Down",
  terminate: "Surrender",
  resume: "Flip Summon",
  restart: "Re-Duel",
  terminateWorkflow: "Surrender Duel",
  terminateConfirm: "Are you sure you want to surrender? All monsters on the field will be destroyed.",
  workflowDefsTitle: "Deck Builder",
  filterDefinitions: "Search decks...",
  noWorkflowDefs: "No decks built. Believe in the heart of the cards!",
  noDefsMatch: "No decks match your search.",
  name: "Card Name",
  version: "Edition",
  tasks: "Cards",
  description: "Lore",
  timeout: "Turn Limit",
  startExecution: "Activate",
  viewJson: "View Card",
  cloneAndEdit: "Copy & Re-equip",
  createWorkflowDef: "Construct New Deck",
  editWorkflowDef: "Modify Deck",
  deleteWorkflowDef: "Banish Deck",
  taskDefsTitle: "Card Catalog",
  filterTaskDefs: "Search cards...",
  noTaskDefs: "No cards in your collection. Open your first booster pack!",
  retryCount: "Summon Limit",
  responseTimeout: "Chain Timer",
  owner: "Duelist",
  testRun: "Test Summon",
  view: "Inspect",
  createTaskDef: "Add Card to Catalog",
  deleteTaskDef: "Banish Card",
  taskInput: "Tribute Cost",
  runTest: "Summon!",
  taskQueuesTitle: "Graveyard",
  totalQueued: "cards in graveyard",
  filterQueues: "Search graveyard…",
  activeQueues: "Active Zones",
  noQueuesMatch: "No cards match your search",
  noTasksInQueue: "Graveyard is empty — all monsters are on the field",
  searchAll: "Search duels, cards, decks…",
  pages: "Zones",
  noResults: "No cards found in the shadow realm.",
  startWorkflowTitle: "Activate New Duel",
  startWorkflowDesc: "Choose a deck and set tribute to begin a new duel.",
  workflowLabel: "Deck *",
  versionLabel: "Edition",
  inputLabel: "Tribute",
  correlationId: "Duelist Tag (optional)",
  selectWorkflow: "Choose deck...",
  loadingWorkflows: "Shuffling deck…",
  noWorkflowsFound: "No decks available. Build one first.",
  breadcrumbDashboard: "Duel Arena",
  breadcrumbExecutions: "Duel Log",
  breadcrumbDefinitions: "Deck Builder",
  breadcrumbTaskDefs: "Card Catalog",
  breadcrumbQueues: "Graveyard",
  loading: "Drawing cards...",
  toastWorkflowTerminated: "Duel surrendered",
  toastWorkflowPaused: "Card set face-down",
  toastWorkflowResumed: "Card flip summoned",
  toastWorkflowRestarted: "Duel restarted",
  toastWorkflowRetried: "Monster reborn activated",
  toastWorkflowStarted: "It's time to duel!",
  toastWorkflowDefSaved: "Deck saved to binder",
  toastTaskDefCreated: "Card(s) added to catalog",
  toastDeleted: "Banished to shadow realm",
  toastInvalidJson: "Corrupted card data",
  workflowNotFound: "Duel not found in the archives",
  retry: "Monster Reborn",
  tasksTab: "Monsters",
  timeline: "Duel Timeline",
  diagram: "Field Layout",
  input: "Hand",
  output: "Rewards",
  info: "Duelist Profile",
  task: "Monster",
  type: "Attribute",
  worker: "Duelist",
  reason: "Cause of Defeat",
  viewSubWorkflow: "View Sub-Duel",
  loadingWorkflowDef: "Shuffling deck...",
  workflowIdLabel: "Duel ID",
  correlationIdLabel: "Duelist Tag",
  priority: "Star Level",
  updated: "Last Phase",
  scheduled: "Set",
  pollCount: "Draw Count",
  duration: "Duel Duration",
  confirm: "Activate",
  pleaseWait: "Drawing card...",
  allStatuses: "All",
  createWorkflow: "Construct Deck",
  saveWorkflow: "Save Deck",
  visualBuilder: "Deck Builder",
  jsonEditor: "Card Data",
  saving: "Saving...",
  addTask: "Add Card",
  noTasksYet: "No cards in deck. Open your first booster!",
  tasksSequentialHint: "Cards are played in turn order.",
  workflowNameRequired: "Deck name is required.",
  addAtLeastOneTask: "Add at least one card.",
  allTasksNeedRefName: "All cards need a name.",
  previewJson: "Preview Card Data",
  workflowSettings: "Deck Configuration",
  nameRequired: "Deck Name *",
  descriptionPlaceholder: "What is this deck's strategy?",
  timeoutSeconds: "Turn Timer (seconds)",
  ownerEmail: "Duelist Email",
  failureWorkflow: "Trap Card",
  optional: "Optional",
  inputParameters: "Tribute Materials",
  inputParamPlaceholder: "Type a material name and press Enter",
  inputParamHint: "These become available as tribute for card summons.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Copy Card",
  remove: "Banish",
  taskType: "Card Type",
  referenceNameRequired: "Card Name *",
  taskName: "Card Name",
  selectRegisteredTask: "Select a card from catalog...",
  startDelay: "Set Delay (s)",
  retryLogic: "Resummon Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Resummon Delay (s)",
  timeoutPolicy: "Timer Policy",
  timeoutPolicyTimeOut: "Disqualify",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Monster Reborn",
  responseTimeoutLabel: "Chain Timer (s)",
  concurrentExecLimit: "Max Field Monsters",
  inputKeys: "Tribute Keys",
  outputKeys: "Reward Keys",
  creating: "Summoning...",
  createFromJson: "Import from Binder",
  form: "Form",
  json: "Card Data",
  subWorkflowConfig: "Sub-Duel Configuration",
  workflowName: "Deck Name",
  versionOptional: "Edition (optional)",
  parallelBranches: "Tag Duel Lanes",
  addBranch: "Add Lane",
  forkJoinNote: "Note: Lanes converge at end phase.",
  decisionConfig: "Trap Card Decision",
  caseExpression: "Activation Condition",
  caseValueParam: "Chain Link",
  cases: "Responses",
  addCase: "Add Response",
  doWhileConfig: "Infinite Loop Configuration",
  loopCondition: "Loop Condition",
  loopBodyTasks: "Loop Cards",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select tribute...",
  noInputKeys: "This card has no defined tribute keys.",
  selectTaskForInputs: "Select a card to see its tributes, or switch to card data mode.",
  provideParamsJson: "Provide tributes in card data mode.",
  pickSourceHint: "Pick a tribute source first, then select the specific material.",
  testRunDescription: "This will create a test duel and activate it. The card will appear in the graveyard queue.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Drawing (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Open spell book",
  collapseSidebar: "Close spell book",
  commandPalette: "Card Search",
  themeLabel: "Theme",
  uiTheme: "Duel Style",
  autoRefreshOn: "Duel tracker ON (5s)",
  autoRefreshOff: "Duel tracker OFF",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter an attribute and press Enter",
  taskDescriptionHint: "Describe this card's effect",
  noTimeoutHint: "0 = no turn limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Card name",
  caseValue: "Gate value",
  diagramStart: "\uD83C\uDCCF Draw",
  diagramEnd: "\uD83C\uDFC6 Victory",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Fusion",
  diagramSwitch: "\u25C7 Trap",
  diagramSubWf: "\u21B3 Chain",
  diagramLoop: "\u21BB Turn",
  diagramEvent: "\u26A1 Activate",
  diagramHttp: "\uD83C\uDF10 Link",
  diagramWait: "\u231B Set",
  diagramTask: "\u25AA Card",
  testWorkflowDesc: "Auto-generated test duel for card",
  about: "Deck List",
  aboutTitle: "Deck List — Tech Cards",
  aboutSubtitle: "Every card in the engine's deck — revealed face-up.",
  aboutFooter: "Assembled in Rust — an unstoppable combo.",
  breadcrumbAbout: "Deck List",
};

const chucknorrisText: ThemeText = {
  appName: "ROUNDHOUSE",
  tagline: "Chuck Norris doesn't orchestrate. He commands.",
  dashboard: "Command Center",
  executions: "Kill Count",
  workflowDefs: "Battle Plans",
  taskDefs: "Arsenal",
  taskQueues: "Boot Camp",
  startWorkflow: "Roundhouse Kick",
  startingWorkflow: "LOADING FIST...",
  search: "Hunt…",
  newDefinition: "New Battle Plan",
  newTaskDef: "New Weapon",
  viewAll: "View All Victories",
  cancel: "Stand Down",
  delete: "Obliterate",
  edit: "Reload",
  dashboardTitle: "Command Center",
  dashboardSubtitle: "Chuck Norris counted to infinity. Twice. Here's the dashboard.",
  running: "In Progress",
  completed: "Destroyed",
  failed: "Impossible",
  queuedTasks: "Waiting in Fear",
  healthy: "UNSTOPPABLE",
  offline: "Taking a Nap",
  statusDistribution: "Destruction Report",
  workflowDefinitions: "Battle Plans",
  taskDefinitions: "Arsenal",
  registeredDefinitions: "battle plans filed",
  registeredTaskTypes: "weapons loaded",
  recentExecutions: "Recent Victories",
  noRecentExecutions: "No missions yet. The world is getting too comfortable.",
  executionsTitle: "Kill Count",
  autoRefresh: "Surveillance",
  live: "Tracking",
  searchAndFilter: "Interrogation",
  searchPlaceholder: "Search targets, missions, or ops...",
  allWorkflowTypes: "All Mission Types",
  results: "targets found",
  showing: "displaying",
  workflow: "Mission",
  status: "Threat Level",
  started: "Launched",
  ended: "Neutralized",
  actions: "Strikes",
  prev: "Fall Back",
  next: "Advance",
  page: "Sector",
  of: "of",
  pause: "Flex",
  terminate: "Roundhouse",
  resume: "Unleash",
  restart: "Round Two",
  terminateWorkflow: "Deliver Roundhouse Kick",
  terminateConfirm: "Chuck Norris doesn't confirm. He just kicks. Are you sure you want to proceed?",
  workflowDefsTitle: "Battle Plans",
  filterDefinitions: "Search battle plans...",
  noWorkflowDefs: "No battle plans needed. Chuck Norris IS the plan.",
  noDefsMatch: "Nothing found. Chuck Norris hid it.",
  name: "Codename",
  version: "Mark",
  tasks: "Targets",
  description: "Intel",
  timeout: "Time Limit",
  startExecution: "Execute",
  viewJson: "Declassify",
  cloneAndEdit: "Copy & Reload",
  createWorkflowDef: "Draft Battle Plan",
  editWorkflowDef: "Revise Battle Plan",
  deleteWorkflowDef: "Shred Battle Plan",
  taskDefsTitle: "Arsenal",
  filterTaskDefs: "Search arsenal...",
  noTaskDefs: "Arsenal is empty. Chuck Norris only needs his fists anyway.",
  retryCount: "Lives Remaining",
  responseTimeout: "Reaction Time",
  owner: "Operative",
  testRun: "Dry Fire",
  view: "Inspect",
  createTaskDef: "Add to Arsenal",
  deleteTaskDef: "Decommission",
  taskInput: "Ammo",
  runTest: "Fire!",
  taskQueuesTitle: "Boot Camp",
  totalQueued: "recruits trembling",
  filterQueues: "Search camps…",
  activeQueues: "Active Camps",
  noQueuesMatch: "No camps match. They fled.",
  noTasksInQueue: "Boot camp is empty — everyone graduated or ran away",
  searchAll: "Hunt missions, weapons, camps…",
  pages: "Zones",
  noResults: "Chuck Norris already found it.",
  startWorkflowTitle: "Launch New Mission",
  startWorkflowDesc: "Select a battle plan and load ammo to begin the operation.",
  workflowLabel: "Battle Plan *",
  versionLabel: "Mark",
  inputLabel: "Ammo",
  correlationId: "Call Sign (optional)",
  selectWorkflow: "Choose battle plan...",
  loadingWorkflows: "Consulting Chuck Norris…",
  noWorkflowsFound: "No battle plans available. Chuck Norris improvises.",
  breadcrumbDashboard: "Command Center",
  breadcrumbExecutions: "Kill Count",
  breadcrumbDefinitions: "Battle Plans",
  breadcrumbTaskDefs: "Arsenal",
  breadcrumbQueues: "Boot Camp",
  loading: "Chuck Norris is thinking...",
  toastWorkflowTerminated: "Target neutralized",
  toastWorkflowPaused: "Chuck flexed. Everything stopped.",
  toastWorkflowResumed: "Chuck said go. It goes.",
  toastWorkflowRestarted: "Round two. FIGHT.",
  toastWorkflowRetried: "Chuck doesn't fail. He retries.",
  toastWorkflowStarted: "Mission deployed!",
  toastWorkflowDefSaved: "Battle plan filed",
  toastTaskDefCreated: "Weapon(s) loaded",
  toastDeleted: "Obliterated",
  toastInvalidJson: "Invalid ammo — reload!",
  workflowNotFound: "Target not found. Chuck already destroyed it.",
  retry: "Try Again (carefully)",
  tasksTab: "Targets",
  timeline: "Action Replay",
  diagram: "Tactical Map",
  input: "Ammo",
  output: "Damage Report",
  info: "Dossier",
  task: "Target",
  type: "Weapon Type",
  worker: "Operative",
  reason: "Cause of Destruction",
  viewSubWorkflow: "View Sub-Mission",
  loadingWorkflowDef: "Consulting Chuck Norris...",
  workflowIdLabel: "Mission ID",
  correlationIdLabel: "Call Sign",
  priority: "Threat Level",
  updated: "Last Strike",
  scheduled: "Queued for Destruction",
  pollCount: "Surveillance Reports",
  duration: "Mission Duration",
  confirm: "DO IT.",
  pleaseWait: "Chuck is warming up...",
  allStatuses: "All",
  createWorkflow: "Draft Battle Plan",
  saveWorkflow: "Save Battle Plan",
  visualBuilder: "War Room",
  jsonEditor: "Raw Intel",
  saving: "Saving...",
  addTask: "Add Target",
  noTasksYet: "No targets yet. Chuck Norris is bored.",
  tasksSequentialHint: "Targets are eliminated sequentially.",
  workflowNameRequired: "Battle plan name is required.",
  addAtLeastOneTask: "Add at least one target.",
  allTasksNeedRefName: "All targets need a codename.",
  previewJson: "Declassify Intel",
  workflowSettings: "Mission Parameters",
  nameRequired: "Codename *",
  descriptionPlaceholder: "What's the mission objective?",
  timeoutSeconds: "Time Limit (seconds)",
  ownerEmail: "Commander",
  failureWorkflow: "Backup Plan",
  optional: "Optional",
  inputParameters: "Ammunition",
  inputParamPlaceholder: "Type a weapon name and press Enter",
  inputParamHint: "These become available as supplies for target ops.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Clone",
  remove: "Eliminate",
  taskType: "Weapon Type",
  referenceNameRequired: "Codename *",
  taskName: "Target Name",
  selectRegisteredTask: "Select a weapon from arsenal...",
  startDelay: "Countdown (s)",
  retryLogic: "Retry Strategy",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Protocol",
  timeoutPolicyTimeOut: "Abort Mission",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Retry",
  responseTimeoutLabel: "Reaction Time (s)",
  concurrentExecLimit: "Simultaneous Strikes",
  inputKeys: "Ammo Keys",
  outputKeys: "Damage Keys",
  creating: "Loading...",
  createFromJson: "Import from Intel",
  form: "Form",
  json: "Intel",
  subWorkflowConfig: "Sub-Mission Configuration",
  workflowName: "Battle Plan Name",
  versionOptional: "Mark (optional)",
  parallelBranches: "Simultaneous Assaults",
  addBranch: "Add Assault",
  forkJoinNote: "Note: Assaults converge at the extraction point.",
  decisionConfig: "Tactical Decision",
  caseExpression: "Condition",
  caseValueParam: "Intel Variable",
  cases: "Outcomes",
  addCase: "Add Outcome",
  doWhileConfig: "Siege Loop Configuration",
  loopCondition: "Siege Condition",
  loopBodyTasks: "Siege Targets",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select ammo...",
  noInputKeys: "This weapon has no defined ammo keys.",
  selectTaskForInputs: "Select a weapon to see its ammo needs, or switch to intel mode.",
  provideParamsJson: "Provide the needed ammo in intel mode.",
  pickSourceHint: "Pick an ammo source first, then select the specific supply.",
  testRunDescription: "This will deploy a test mission. The target will appear in boot camp.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Tracking (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Kick it open",
  collapseSidebar: "Roundhouse close",
  commandPalette: "Action Menu",
  themeLabel: "Theme",
  uiTheme: "Combat Style",
  autoRefreshOn: "Surveillance ON (5s)",
  autoRefreshOff: "Surveillance OFF",
  fields: "Fields",
  valueFor: "Ammo for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Load a round and press Enter",
  taskDescriptionHint: "What does this mission accomplish?",
  noTimeoutHint: "0 = Chuck never times out",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Alias",
  caseValue: "Target value",
  diagramStart: "\uD83D\uDCAA Engage",
  diagramEnd: "\uD83C\uDFC6 Victory",
  diagramFork: "\u2442 Flank",
  diagramJoin: "\u2295 Regroup",
  diagramSwitch: "\u25C7 Decide",
  diagramSubWf: "\u21B3 Side-Op",
  diagramLoop: "\u21BB Roundhouse",
  diagramEvent: "\u26A1 Strike",
  diagramHttp: "\uD83C\uDF10 Intel",
  diagramWait: "\u231B Stalk",
  diagramTask: "\u25AA Op",
  testWorkflowDesc: "Auto-generated field test for mission",
  about: "Intel",
  aboutTitle: "Mission Intel",
  aboutSubtitle: "Full dossier on every technology — Chuck Norris approved.",
  aboutFooter: "Compiled in Rust — Chuck Norris doesn't need a garbage collector.",
  breadcrumbAbout: "Intel",
};

const lotrText: ThemeText = {
  appName: "MIDDLE-EARTH",
  tagline: "One workflow to rule them all.",
  dashboard: "The Shire",
  executions: "Quest Log",
  workflowDefs: "Scrolls of Lore",
  taskDefs: "The Armoury",
  taskQueues: "Mines of Moria",
  startWorkflow: "Begin Quest",
  startingWorkflow: "The fellowship departs\u2026",
  search: "Seek\u2026",
  newDefinition: "Inscribe Scroll",
  newTaskDef: "Forge Weapon",
  viewAll: "View All Quests",
  cancel: "Retreat",
  delete: "Cast into Doom",
  edit: "Reforge",
  dashboardTitle: "The Shire",
  dashboardSubtitle: "A peaceful overview of all journeys across Middle-earth",
  running: "On the Road",
  completed: "Quest Complete",
  failed: "Fallen in Battle",
  queuedTasks: "Awaiting the Council",
  healthy: "Light of E\u00e4rendil",
  offline: "Shrouded in Shadow",
  statusDistribution: "Fate of the Fellowship",
  workflowDefinitions: "Scrolls of Lore",
  taskDefinitions: "The Armoury",
  registeredDefinitions: "scrolls inscribed",
  registeredTaskTypes: "weapons forged",
  recentExecutions: "Recent Quests",
  noRecentExecutions: "No quests begun. The road goes ever on and on\u2026",
  executionsTitle: "Quest Log",
  autoRefresh: "Palant\u00edr",
  live: "Seeing",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by fellowship, realm, or quest\u2026",
  allWorkflowTypes: "All Scrolls",
  results: "tales found",
  showing: "revealing",
  workflow: "Quest",
  status: "Fate",
  started: "Departed",
  ended: "Concluded",
  actions: "Deeds",
  prev: "Go Back",
  next: "Onward",
  page: "Chapter",
  of: "of",
  pause: "Make Camp",
  terminate: "Abandon Quest",
  resume: "Resume March",
  restart: "Begin Anew",
  terminateWorkflow: "Abandon This Quest",
  terminateConfirm: "Even the smallest quest can change the course of the future. Are you sure you wish to abandon it?",
  workflowDefsTitle: "Scrolls of Lore",
  filterDefinitions: "Search scrolls\u2026",
  noWorkflowDefs: "No scrolls inscribed. The tale has yet to begin.",
  noDefsMatch: "No scrolls match your search.",
  name: "Name",
  version: "Age",
  tasks: "Steps",
  description: "Chronicle",
  timeout: "Journey Duration",
  startExecution: "Send Forth",
  viewJson: "Read Scroll",
  cloneAndEdit: "Transcribe & Amend",
  createWorkflowDef: "Inscribe New Scroll",
  editWorkflowDef: "Amend Scroll",
  deleteWorkflowDef: "Burn Scroll",
  taskDefsTitle: "The Armoury",
  filterTaskDefs: "Search armoury\u2026",
  noTaskDefs: "The armoury is bare. Forge your first weapon!",
  retryCount: "Endurance",
  responseTimeout: "Swiftness",
  owner: "Bearer",
  testRun: "Test in Battle",
  view: "Inspect",
  createTaskDef: "Forge New Weapon",
  deleteTaskDef: "Destroy Weapon",
  taskInput: "Provisions",
  runTest: "Test!",
  taskQueuesTitle: "Mines of Moria",
  totalQueued: "tasks in the deep",
  filterQueues: "Search the mines\u2026",
  activeQueues: "Active Shafts",
  noQueuesMatch: "No shafts match your search",
  noTasksInQueue: "The mines are empty \u2014 the dwarves delved too deep",
  searchAll: "Search quests, weapons, scrolls\u2026",
  pages: "Realms",
  noResults: "Not all who wander are lost\u2026 but nothing was found.",
  startWorkflowTitle: "Begin a New Quest",
  startWorkflowDesc: "Choose a scroll of lore and prepare provisions for the journey ahead.",
  workflowLabel: "Scroll *",
  versionLabel: "Age",
  inputLabel: "Provisions",
  correlationId: "Fellowship Name (optional)",
  selectWorkflow: "Choose scroll\u2026",
  loadingWorkflows: "Consulting Gandalf\u2026",
  noWorkflowsFound: "No scrolls available. Inscribe one first.",
  breadcrumbDashboard: "The Shire",
  breadcrumbExecutions: "Quest Log",
  breadcrumbDefinitions: "Scrolls of Lore",
  breadcrumbTaskDefs: "The Armoury",
  breadcrumbQueues: "Mines of Moria",
  loading: "The road goes ever on\u2026",
  toastWorkflowTerminated: "Quest abandoned",
  toastWorkflowPaused: "The fellowship rests",
  toastWorkflowResumed: "The march continues",
  toastWorkflowRestarted: "Quest begun anew",
  toastWorkflowRetried: "A second chance is given",
  toastWorkflowStarted: "The fellowship departs!",
  toastWorkflowDefSaved: "Scroll inscribed in the archive",
  toastTaskDefCreated: "Weapon(s) forged",
  toastDeleted: "Cast into the fires of Mount Doom",
  toastInvalidJson: "The scroll is illegible",
  workflowNotFound: "This quest is lost to history",
  retry: "Seek Again",
  tasksTab: "Fellowship",
  timeline: "Chronicle",
  diagram: "Map of Middle-earth",
  input: "Provisions",
  output: "Spoils",
  info: "Lore",
  task: "Companion",
  type: "Race",
  worker: "Bearer",
  reason: "Cause of Defeat",
  viewSubWorkflow: "View Sub-Quest",
  loadingWorkflowDef: "Unrolling ancient scroll...",
  workflowIdLabel: "Quest ID",
  correlationIdLabel: "Fellowship Name",
  priority: "Urgency",
  updated: "Last Seen",
  scheduled: "Mustered",
  pollCount: "Eagle Sightings",
  duration: "Journey Duration",
  confirm: "So Be It",
  pleaseWait: "The Eagles are coming...",
  allStatuses: "All",
  createWorkflow: "Inscribe Scroll",
  saveWorkflow: "Save Scroll",
  visualBuilder: "Council of Elrond",
  jsonEditor: "Ancient Script",
  saving: "Inscribing...",
  addTask: "Add Companion",
  noTasksYet: "The fellowship is empty. Recruit your first companion!",
  tasksSequentialHint: "Companions set out in the order of the march.",
  workflowNameRequired: "Scroll name is required.",
  addAtLeastOneTask: "Recruit at least one companion.",
  allTasksNeedRefName: "All companions need a name.",
  previewJson: "Preview Script",
  workflowSettings: "Quest Parameters",
  nameRequired: "Name *",
  descriptionPlaceholder: "What is this quest's purpose?",
  timeoutSeconds: "Journey Timeout (seconds)",
  ownerEmail: "Quest Giver",
  failureWorkflow: "Retreat Plan",
  optional: "Optional",
  inputParameters: "Provisions",
  inputParamPlaceholder: "Type a provision and press Enter",
  inputParamHint: "These become available as resources for the fellowship.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Dismiss",
  taskType: "Companion Type",
  referenceNameRequired: "Name *",
  taskName: "Companion Name",
  selectRegisteredTask: "Select from the armoury...",
  startDelay: "Departure Delay (s)",
  retryLogic: "Second Chance Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Journey Policy",
  timeoutPolicyTimeOut: "Abandon Quest",
  timeoutPolicyAlert: "Signal Only",
  timeoutPolicyRetry: "Seek Again",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Fellowship Size Limit",
  inputKeys: "Provision Keys",
  outputKeys: "Spoil Keys",
  creating: "Forging...",
  createFromJson: "Inscribe from Script",
  form: "Form",
  json: "Script",
  subWorkflowConfig: "Sub-Quest Configuration",
  workflowName: "Scroll Name",
  versionOptional: "Age (optional)",
  parallelBranches: "Parallel Paths",
  addBranch: "Add Path",
  forkJoinNote: "Note: Paths converge at the rendezvous.",
  decisionConfig: "Council Decision",
  caseExpression: "Condition",
  caseValueParam: "Palant\u00edr Reading",
  cases: "Fates",
  addCase: "Add Fate",
  doWhileConfig: "Siege of Helm's Deep",
  loopCondition: "Siege Condition",
  loopBodyTasks: "Siege Actions",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select provision...",
  noInputKeys: "This companion has no defined provision keys.",
  selectTaskForInputs: "Select from the armoury to see provisions, or switch to script mode.",
  provideParamsJson: "Provide provisions in script mode.",
  pickSourceHint: "Pick a provision source first, then select the specific resource.",
  testRunDescription: "This will form a test fellowship and begin the quest. The companion will appear in the Mines.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Palant\u00edr (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "moments ago",
  secondsAgo: "s past",
  minutesAgo: "m past",
  hoursAgo: "h past",
  daysAgo: "d past",
  expandSidebar: "Unfurl the map",
  collapseSidebar: "Roll the map",
  commandPalette: "Council of Elrond",
  themeLabel: "Theme",
  uiTheme: "Realm Tapestry",
  autoRefreshOn: "Palant\u00edr active (5s)",
  autoRefreshOff: "Palant\u00edr veiled",
  fields: "Fields",
  valueFor: "Worth of",
  typeAndPressEnter: "Inscribe and press Enter",
  typeKeyAndEnter: "Engrave a rune and press Enter",
  taskDescriptionHint: "What quest does this fellowship undertake?",
  noTimeoutHint: "0 = timeless",
  unlimitedHint: "0 = boundless",
  latest: "Latest",
  referenceName: "Deed name",
  caseValue: "Path value",
  diagramStart: "\uD83D\uDDE1 Embark",
  diagramEnd: "\uD83D\uDC51 Return",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Reunite",
  diagramSwitch: "\u25C7 Crossroads",
  diagramSubWf: "\u21B3 Side-Quest",
  diagramLoop: "\u21BB Journey",
  diagramEvent: "\u26A1 Omen",
  diagramHttp: "\uD83C\uDF10 Raven",
  diagramWait: "\u231B Rest",
  diagramTask: "\u25AA Deed",
  testWorkflowDesc: "Auto-generated quest trial for fellowship",
  about: "Appendices",
  aboutTitle: "The Appendices",
  aboutSubtitle: "A chronicle of the tools and crafts that forged this realm.",
  aboutFooter: "Forged in the fires of Rust — one engine to rule them all.",
  breadcrumbAbout: "Appendices",
};

/* ------------------------------------------------------------------ */
/*  Theme map                                                          */
/* ------------------------------------------------------------------ */

const themeTextMap: Record<UITheme, ThemeText> = {
  default: defaultText,
  warcraft: warcraftText,
  cyberpunk: cyberpunkText,
  forest: forestText,
  ocean: oceanText,
  pokemon: pokemonText,
  yugioh: yugiohText,
  chucknorris: chucknorrisText,
  lotr: lotrText,
};

/* ------------------------------------------------------------------ */
/*  Context                                                            */
/* ------------------------------------------------------------------ */

interface ThemeContextValue {
  uiTheme: UITheme;
  setUITheme: (theme: UITheme) => void;
  t: ThemeText;
}

const ThemeContext = createContext<ThemeContextValue>({
  uiTheme: "default",
  setUITheme: () => {},
  t: defaultText,
});

function getStoredUITheme(): UITheme {
  const stored = localStorage.getItem("ui-theme") as UITheme | null;
  return stored && stored in themeTextMap ? stored : "default";
}

function applyUIThemeClass(theme: UITheme) {
  const root = document.documentElement;
  root.classList.remove("theme-warcraft", "theme-cyberpunk", "theme-forest", "theme-ocean", "theme-pokemon", "theme-yugioh", "theme-chucknorris", "theme-lotr");
  if (theme !== "default") {
    root.classList.add(`theme-${theme}`);
  }
}

export function ThemeProvider({ children }: { children: ReactNode }) {
  const [uiTheme, setUIThemeState] = useState<UITheme>(getStoredUITheme);

  const setUITheme = (theme: UITheme) => {
    setUIThemeState(theme);
    localStorage.setItem("ui-theme", theme);
    applyUIThemeClass(theme);
  };

  useEffect(() => {
    applyUIThemeClass(uiTheme);
  }, [uiTheme]);

  const t = themeTextMap[uiTheme];

  return (
    <ThemeContext.Provider value={{ uiTheme, setUITheme, t }}>
      {children}
    </ThemeContext.Provider>
  );
}

export function useTheme() {
  return useContext(ThemeContext);
}

export function useThemeText() {
  return useContext(ThemeContext).t;
}
