import type { ThemeText } from "./types";

export const chucknorrisText: ThemeText = {
  appName: "ROUNDHOUSE",
  tagline: "Chuck Norris doesn't orchestrate. He commands.",
  dashboard: "Command Center",
  executions: "Kill Count",
  workflowDefs: "Battle Plans",
  taskDefs: "Arsenal",
  taskQueues: "Boot Camp",
  startWorkflow: "Roundhouse Kick",
  startingWorkflow: "LOADING FIST...",
  search: "Huntâ€¦",
  newDefinition: "New Battle Plan",
  newTaskDef: "New Weapon",
  viewAll: "View All Victories",
  cancel: "Stand Down",
  delete: "Obliterate",
  edit: "Reload",
  dashboardTitle: "Command Center",
  dashboardSubtitle: "Chuck Norris counted to infinity. Twice. Here's the dashboard.",
  running: "In Progress",
  completed: "Destroyed",
  failed: "Impossible",
  queuedTasks: "Waiting in Fear",
  healthy: "UNSTOPPABLE",
  offline: "Taking a Nap",
  statusDistribution: "Destruction Report",
  workflowDefinitions: "Battle Plans",
  taskDefinitions: "Arsenal",
  registeredDefinitions: "battle plans filed",
  registeredTaskTypes: "weapons loaded",
  recentExecutions: "Recent Victories",
  noRecentExecutions: "No missions yet. The world is getting too comfortable.",
  executionsTitle: "Kill Count",
  autoRefresh: "Surveillance",
  live: "Tracking",
  searchAndFilter: "Interrogation",
  searchPlaceholder: "Search targets, missions, or ops...",
  allWorkflowTypes: "All Mission Types",
  results: "targets found",
  showing: "displaying",
  workflow: "Mission",
  status: "Threat Level",
  started: "Launched",
  ended: "Neutralized",
  actions: "Strikes",
  prev: "Fall Back",
  next: "Advance",
  page: "Sector",
  of: "of",
  pause: "Flex",
  terminate: "Roundhouse",
  resume: "Unleash",
  restart: "Round Two",
  terminateWorkflow: "Deliver Roundhouse Kick",
  terminateConfirm: "Chuck Norris doesn't confirm. He just kicks. Are you sure you want to proceed?",
  workflowDefsTitle: "Battle Plans",
  filterDefinitions: "Search battle plans...",
  noWorkflowDefs: "No battle plans needed. Chuck Norris IS the plan.",
  noDefsMatch: "Nothing found. Chuck Norris hid it.",
  name: "Codename",
  version: "Mark",
  tasks: "Targets",
  description: "Intel",
  timeout: "Time Limit",
  startExecution: "Execute",
  viewJson: "Declassify",
  cloneAndEdit: "Copy & Reload",
  createWorkflowDef: "Draft Battle Plan",
  editWorkflowDef: "Revise Battle Plan",
  deleteWorkflowDef: "Shred Battle Plan",
  taskDefsTitle: "Arsenal",
  filterTaskDefs: "Search arsenal...",
  noTaskDefs: "Arsenal is empty. Chuck Norris only needs his fists anyway.",
  retryCount: "Lives Remaining",
  responseTimeout: "Reaction Time",
  owner: "Operative",
  testRun: "Dry Fire",
  view: "Inspect",
  createTaskDef: "Add to Arsenal",
  deleteTaskDef: "Decommission",
  taskInput: "Ammo",
  runTest: "Fire!",
  taskQueuesTitle: "Boot Camp",
  totalQueued: "recruits trembling",
  filterQueues: "Search campsâ€¦",
  activeQueues: "Active Camps",
  noQueuesMatch: "No camps match. They fled.",
  noTasksInQueue: "Boot camp is empty â€” everyone graduated or ran away",
  searchAll: "Hunt missions, weapons, campsâ€¦",
  pages: "Zones",
  noResults: "Chuck Norris already found it.",
  startWorkflowTitle: "Launch New Mission",
  startWorkflowDesc: "Select a battle plan and load ammo to begin the operation.",
  workflowLabel: "Battle Plan *",
  versionLabel: "Mark",
  inputLabel: "Ammo",
  correlationId: "Call Sign (optional)",
  selectWorkflow: "Choose battle plan...",
  loadingWorkflows: "Consulting Chuck Norrisâ€¦",
  noWorkflowsFound: "No battle plans available. Chuck Norris improvises.",
  breadcrumbDashboard: "Command Center",
  breadcrumbExecutions: "Kill Count",
  breadcrumbDefinitions: "Battle Plans",
  breadcrumbTaskDefs: "Arsenal",
  breadcrumbQueues: "Boot Camp",
  loading: "Chuck Norris is thinking...",
  toastWorkflowTerminated: "Target neutralized",
  toastWorkflowPaused: "Chuck flexed. Everything stopped.",
  toastWorkflowResumed: "Chuck said go. It goes.",
  toastWorkflowRestarted: "Round two. FIGHT.",
  toastWorkflowRetried: "Chuck doesn't fail. He retries.",
  toastWorkflowStarted: "Mission deployed!",
  toastWorkflowDefSaved: "Battle plan filed",
  toastTaskDefCreated: "Weapon(s) loaded",
  toastDeleted: "Obliterated",
  toastInvalidJson: "Invalid ammo â€” reload!",
  workflowNotFound: "Target not found. Chuck already destroyed it.",
  retry: "Try Again (carefully)",
  tasksTab: "Targets",
  timeline: "Action Replay",
  diagram: "Tactical Map",
  input: "Ammo",
  output: "Damage Report",
  info: "Dossier",
  task: "Target",
  type: "Weapon Type",
  worker: "Operative",
  reason: "Cause of Destruction",
  viewSubWorkflow: "View Sub-Mission",
  loadingWorkflowDef: "Consulting Chuck Norris...",
  workflowIdLabel: "Mission ID",
  correlationIdLabel: "Call Sign",
  priority: "Threat Level",
  updated: "Last Strike",
  scheduled: "Queued for Destruction",
  pollCount: "Surveillance Reports",
  duration: "Mission Duration",
  confirm: "DO IT.",
  pleaseWait: "Chuck is warming up...",
  allStatuses: "All",
  createWorkflow: "Draft Battle Plan",
  saveWorkflow: "Save Battle Plan",
  visualBuilder: "War Room",
  jsonEditor: "Raw Intel",
  saving: "Saving...",
  addTask: "Add Target",
  noTasksYet: "No targets yet. Chuck Norris is bored.",
  tasksSequentialHint: "Targets are eliminated sequentially.",
  workflowNameRequired: "Battle plan name is required.",
  addAtLeastOneTask: "Add at least one target.",
  allTasksNeedRefName: "All targets need a codename.",
  previewJson: "Declassify Intel",
  workflowSettings: "Mission Parameters",
  nameRequired: "Codename *",
  descriptionPlaceholder: "What's the mission objective?",
  timeoutSeconds: "Time Limit (seconds)",
  ownerEmail: "Commander",
  failureWorkflow: "Backup Plan",
  optional: "Optional",
  inputParameters: "Ammunition",
  inputParamPlaceholder: "Type a weapon name and press Enter",
  inputParamHint: "These become available as supplies for target ops.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Clone",
  remove: "Eliminate",
  taskType: "Weapon Type",
  referenceNameRequired: "Codename *",
  taskName: "Target Name",
  selectRegisteredTask: "Select a weapon from arsenal...",
  startDelay: "Countdown (s)",
  retryLogic: "Retry Strategy",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Protocol",
  timeoutPolicyTimeOut: "Abort Mission",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Retry",
  responseTimeoutLabel: "Reaction Time (s)",
  concurrentExecLimit: "Simultaneous Strikes",
  inputKeys: "Ammo Keys",
  outputKeys: "Damage Keys",
  creating: "Loading...",
  createFromJson: "Import from Intel",
  form: "Form",
  json: "Intel",
  subWorkflowConfig: "Sub-Mission Configuration",
  workflowName: "Battle Plan Name",
  versionOptional: "Mark (optional)",
  parallelBranches: "Simultaneous Assaults",
  addBranch: "Add Assault",
  forkJoinNote: "Note: Assaults converge at the extraction point.",
  decisionConfig: "Tactical Decision",
  caseExpression: "Condition",
  caseValueParam: "Intel Variable",
  cases: "Outcomes",
  addCase: "Add Outcome",
  doWhileConfig: "Siege Loop Configuration",
  loopCondition: "Siege Condition",
  loopBodyTasks: "Siege Targets",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select ammo...",
  noInputKeys: "This weapon has no defined ammo keys.",
  selectTaskForInputs: "Select a weapon to see its ammo needs, or switch to intel mode.",
  provideParamsJson: "Provide the needed ammo in intel mode.",
  pickSourceHint: "Pick an ammo source first, then select the specific supply.",
  testRunDescription: "This will deploy a test mission. The target will appear in boot camp.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Tracking (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Kick it open",
  collapseSidebar: "Roundhouse close",
  commandPalette: "Action Menu",
  themeLabel: "Theme",
  uiTheme: "Combat Style",
  autoRefreshOn: "Surveillance ON (5s)",
  autoRefreshOff: "Surveillance OFF",
  fields: "Fields",
  valueFor: "Ammo for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Load a round and press Enter",
  taskDescriptionHint: "What does this mission accomplish?",
  noTimeoutHint: "0 = Chuck never times out",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Alias",
  caseValue: "Target value",
  diagramStart: "\uD83D\uDCAA Engage",
  diagramEnd: "\uD83C\uDFC6 Victory",
  diagramFork: "\u2442 Flank",
  diagramJoin: "\u2295 Regroup",
  diagramSwitch: "\u25C7 Decide",
  diagramSubWf: "\u21B3 Side-Op",
  diagramLoop: "\u21BB Roundhouse",
  diagramEvent: "\u26A1 Strike",
  diagramHttp: "\uD83C\uDF10 Intel",
  diagramWait: "\u231B Stalk",
  diagramTask: "\u25AA Op",
  testWorkflowDesc: "Auto-generated field test for mission",
  about: "Intel",
  aboutTitle: "Mission Intel",
  aboutSubtitle: "Full dossier on every technology â€” Chuck Norris approved.",
  aboutFooter: "Compiled in Rust â€” Chuck Norris doesn't need a garbage collector.",
  breadcrumbAbout: "Intel",
  versionHistory: "Mission Archives",
  compareVersions: "Compare Missions",
  noOtherVersions: "No other missions found.",
  noDifferences: "Chuck sees no difference.",
  added: "Roundhoused in",
  removed: "Roundhoused out",
  customizeDashboard: "Rearrange Dojo",
  resetLayout: "Reset Dojo",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "Chuck is angry!",
  configureAlerts: "Set Chuck Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search all mission archives",
  replayExecution: "Round 2!",
  replayDesc: "Re-execute this mission with the same or modified intel.",
  dependencyGraph: "Strike Chain",
  dependencyGraphDesc: "Mission dependency chain",
  noDependencies: "Chuck needs no dependencies.",
  breadcrumbDependencies: "Strike Chain",
  schedules: "Hit List",
  schedulesTitle: "Scheduled Missions",
  breadcrumbSchedules: "Hit List",
  createSchedule: "Schedule Hit",
  editSchedule: "Revise Hit",
  deleteSchedule: "Cancel Hit",
  cronExpression: "Strike Schedule",
  timezoneLabel: "Chuck Time",
  enabled: "Armed",
  disabled: "Standing Down",
  lastRun: "Last Strike",
  nextRun: "Next Strike",
  noSchedules: "No strikes scheduled. Chuck Norris doesn't need a schedule.",
  scheduleCreated: "Strike scheduled",
  scheduleDeleted: "Strike cancelled",
  scheduleEnabled: "Strike armed",
  scheduleDisabled: "Strike disarmed",
  filterSchedules: "Search hit list...",
  scheduleLastError: "Last Failure",
  onCompleteWebhook: "Victory Report URL",
  onFailureWebhook: "Impossible Failure URL",
  webhookPlaceholder: "https://example.com/dojo",
  slaDeadline: "Mission Deadline (seconds)",
  slaHint: "0 = Chuck never times out",
  tagsLabel: "Mission Tags",
  tagsPlaceholder: "Add a tag and press Enter",
  bulkActions: "Mass Strikes",
  bulkPause: "Flex on All",
  bulkResume: "Unleash All",
  bulkRetry: "Retry All",
  bulkRestart: "Round Two All",
  bulkTerminate: "Roundhouse All",
  bulkConfirm: "Chuck Norris doesn't confirm. Proceed?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Mass strike complete",
  retryOnErrors: "Retry on Specific Failures",
  retryOnErrorsHint: "Chuck rarely fails, but just in case",
  envVars: "Combat Gear",
  envVarsHint: "JSON gear injected before the mission",
};

