import type { ThemeText } from "./types";

export const cyberpunkText: ThemeText = {
  appName: "NETRUNNER",
  tagline: "Neural orchestration protocol v2.0",
  dashboard: "Neural Hub",
  executions: "Process Stack",
  workflowDefs: "Protocols",
  taskDefs: "Subroutines",
  taskQueues: "Thread Pool",
  startWorkflow: "Execute Protocol",
  startingWorkflow: "Jacking in...",
  search: "Scanâ€¦",
  newDefinition: "Upload Protocol",
  newTaskDef: "New Subroutine",
  viewAll: "Full Stack Trace",
  cancel: "Abort",
  delete: "Purge",
  edit: "Patch",
  dashboardTitle: "Neural Hub",
  dashboardSubtitle: "Real-time system telemetry and process overview",
  running: "Active",
  completed: "Terminated",
  failed: "Crashed",
  queuedTasks: "Queued Threads",
  healthy: "Online",
  offline: "Flatlined",
  statusDistribution: "Process State Matrix",
  workflowDefinitions: "Protocols",
  taskDefinitions: "Subroutines",
  registeredDefinitions: "uploaded protocols",
  registeredTaskTypes: "registered subroutines",
  recentExecutions: "Recent Processes",
  noRecentExecutions: "Stack empty. Execute your first protocol.",
  executionsTitle: "Process Stack",
  autoRefresh: "Auto-Scan",
  live: "Live Feed",
  searchAndFilter: "Query & Filter",
  searchPlaceholder: "Scan processes, IDs, or correlation tags...",
  allWorkflowTypes: "All Protocol Types",
  results: "hits",
  showing: "displaying",
  workflow: "Protocol",
  status: "State",
  started: "Initiated",
  ended: "Terminated",
  actions: "Ops",
  prev: "Prev Block",
  next: "Next Block",
  page: "Block",
  of: "of",
  pause: "Freeze",
  terminate: "Kill Process",
  resume: "Unfreeze",
  restart: "Reboot",
  terminateWorkflow: "Kill Process",
  terminateConfirm: "Confirm process termination? All active threads will be killed immediately.",
  workflowDefsTitle: "Protocols",
  filterDefinitions: "Scan protocols...",
  noWorkflowDefs: "No protocols uploaded. Jack in and create one.",
  noDefsMatch: "No protocols match your query.",
  name: "Identifier",
  version: "Build",
  tasks: "Nodes",
  description: "Docs",
  timeout: "TTL",
  startExecution: "Execute",
  viewJson: "View Source",
  cloneAndEdit: "Fork & Patch",
  createWorkflowDef: "Upload Protocol",
  editWorkflowDef: "Patch Protocol",
  deleteWorkflowDef: "Purge Protocol",
  taskDefsTitle: "Subroutines",
  filterTaskDefs: "Scan subroutines...",
  noTaskDefs: "No subroutines registered. Upload your first module.",
  retryCount: "Retry Limit",
  responseTimeout: "RTT Limit",
  owner: "Maintainer",
  testRun: "Dry Run",
  view: "Inspect",
  createTaskDef: "Register Subroutine",
  deleteTaskDef: "Purge Subroutine",
  taskInput: "Input Payload",
  runTest: "Run Dry",
  taskQueuesTitle: "Thread Pool",
  totalQueued: "threads queued",
  filterQueues: "Filter threadsâ€¦",
  activeQueues: "Active Threads",
  noQueuesMatch: "No threads match your filter",
  noTasksInQueue: "Thread pool empty â€” all cycles idle",
  searchAll: "Scan protocols, subroutines, threadsâ€¦",
  pages: "Modules",
  noResults: "No data found in the net.",
  startWorkflowTitle: "Execute New Protocol",
  startWorkflowDesc: "Select a protocol definition and inject payload to initiate execution.",
  workflowLabel: "Protocol *",
  versionLabel: "Build",
  inputLabel: "Payload",
  correlationId: "Trace ID (optional)",
  selectWorkflow: "Select protocol...",
  loadingWorkflows: "Scanning networkâ€¦",
  noWorkflowsFound: "No protocols on the net. Upload one first.",
  breadcrumbDashboard: "Neural Hub",
  breadcrumbExecutions: "Process Stack",
  breadcrumbDefinitions: "Protocols",
  breadcrumbTaskDefs: "Subroutines",
  breadcrumbQueues: "Thread Pool",
  loading: "Scanning...",
  toastWorkflowTerminated: "Process terminated",
  toastWorkflowPaused: "Process suspended",
  toastWorkflowResumed: "Process resumed",
  toastWorkflowRestarted: "Process rebooted",
  toastWorkflowRetried: "Process re-executed",
  toastWorkflowStarted: "Process initialized",
  toastWorkflowDefSaved: "Blueprint uploaded",
  toastTaskDefCreated: "Subroutine(s) compiled",
  toastDeleted: "Purged",
  toastInvalidJson: "Corrupt data packet",
  workflowNotFound: "Process not found in the net",
  retry: "Re-exec",
  tasksTab: "Threads",
  timeline: "Chrono-Log",
  diagram: "Network Map",
  input: "Input Stream",
  output: "Output Stream",
  info: "Telemetry",
  task: "Thread",
  type: "Module",
  worker: "Node",
  reason: "Error Trace",
  viewSubWorkflow: "Jack Into Sub-Process",
  loadingWorkflowDef: "Downloading blueprint...",
  workflowIdLabel: "Process ID",
  correlationIdLabel: "Link ID",
  priority: "Priority Level",
  updated: "Last Sync",
  scheduled: "Queued",
  pollCount: "Ping Count",
  duration: "Uptime",
  confirm: "Execute",
  pleaseWait: "Compiling...",
  allStatuses: "All",
  createWorkflow: "Compile Blueprint",
  saveWorkflow: "Upload Blueprint",
  visualBuilder: "Visual IDE",
  jsonEditor: "Raw Code",
  saving: "Uploading...",
  addTask: "Add Thread",
  noTasksYet: "No threads yet. Jack in and start coding.",
  tasksSequentialHint: "Threads execute sequentially in the pipeline.",
  workflowNameRequired: "Blueprint name is required.",
  addAtLeastOneTask: "Add at least one thread.",
  allTasksNeedRefName: "All threads need a handle.",
  previewJson: "Preview Code",
  workflowSettings: "Blueprint Config",
  nameRequired: "Handle *",
  descriptionPlaceholder: "What does this blueprint do?",
  timeoutSeconds: "Timeout (seconds)",
  ownerEmail: "Operator",
  failureWorkflow: "Crash Handler",
  optional: "Optional",
  inputParameters: "Input Streams",
  inputParamPlaceholder: "Type a stream name and press Enter",
  inputParamHint: "These become available as data sources for thread mapping.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Clone",
  remove: "Delete",
  taskType: "Thread Type",
  referenceNameRequired: "Handle *",
  taskName: "Thread Name",
  selectRegisteredTask: "Select a registered subroutine...",
  startDelay: "Boot Delay (s)",
  retryLogic: "Retry Protocol",
  retryFixed: "Fixed",
  retryExponential: "Exponential Backoff",
  retryLinear: "Linear Backoff",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Protocol",
  timeoutPolicyTimeOut: "Kill Process",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Re-exec",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Max Parallel Threads",
  inputKeys: "Input Keys",
  outputKeys: "Output Keys",
  creating: "Compiling...",
  createFromJson: "Compile from Code",
  form: "Form",
  json: "Code",
  subWorkflowConfig: "Sub-Process Configuration",
  workflowName: "Blueprint Name",
  versionOptional: "Version (optional)",
  parallelBranches: "Parallel Threads",
  addBranch: "Add Thread",
  forkJoinNote: "Note: A sync barrier will be automatically appended.",
  decisionConfig: "Conditional Branch",
  caseExpression: "Condition Expression",
  caseValueParam: "Switch Variable",
  cases: "Cases",
  addCase: "Add Case",
  doWhileConfig: "Loop Configuration",
  loopCondition: "Loop Condition",
  loopBodyTasks: "Loop Body",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select stream...",
  noInputKeys: "This thread has no defined input keys.",
  selectTaskForInputs: "Select a registered subroutine to see its inputs, or switch to code mode.",
  provideParamsJson: "Provide the needed parameters in code mode.",
  pickSourceHint: "Pick a data source first, then select the specific stream.",
  testRunDescription: "This will create a test process and execute it. The thread will appear in its pool.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This action is irreversible.",
  liveInterval: "Live (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "null",
  justNow: "just now",
  secondsAgo: "s elapsed",
  minutesAgo: "m elapsed",
  hoursAgo: "h elapsed",
  daysAgo: "d elapsed",
  expandSidebar: "Expand panel",
  collapseSidebar: "Collapse panel",
  commandPalette: "Command Terminal",
  themeLabel: "Skin",
  uiTheme: "Interface Skin",
  autoRefreshOn: "Live feed ON (5s)",
  autoRefreshOff: "Live feed OFF",
  fields: "Fields",
  valueFor: "Payload for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter key and press Enter",
  taskDescriptionHint: "What does this routine do?",
  noTimeoutHint: "0 = no timeout",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Handle",
  caseValue: "Branch value",
  diagramStart: "\u25B6 Init",
  diagramEnd: "\u23F9 Halt",
  diagramFork: "\u2442 Fork",
  diagramJoin: "\u2295 Merge",
  diagramSwitch: "\u25C7 Branch",
  diagramSubWf: "\u21B3 SubProc",
  diagramLoop: "\u21BB Loop",
  diagramEvent: "\u26A1 Signal",
  diagramHttp: "\uD83C\uDF10 NetCall",
  diagramWait: "\u231B Idle",
  diagramTask: "\u25AA Thread",
  testWorkflowDesc: "Auto-generated test blueprint for routine",
  about: "Specs",
  aboutTitle: "System Specs // NETRUNNER",
  aboutSubtitle: "Full hardware and software manifest â€” every chip, every daemon.",
  aboutFooter: "Compiled in Rust // zero bugs, zero mercy.",
  breadcrumbAbout: "Specs",
  versionHistory: "Firmware Changelog",
  compareVersions: "Diff Firmware",
  noOtherVersions: "No other firmware found.",
  noDifferences: "Binaries are identical.",
  added: "Injected",
  removed: "Purged",
  customizeDashboard: "Reconfigure HUD",
  resetLayout: "Factory Reset",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "System overload!",
  configureAlerts: "Set ICE Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Scan all firmware versions",
  replayExecution: "Re-execute Protocol",
  replayDesc: "Re-run this protocol with the same or modified payload.",
  dependencyGraph: "Network Map",
  dependencyGraphDesc: "Protocol dependency web",
  noDependencies: "No linked protocols found.",
  breadcrumbDependencies: "Network Map",
  schedules: "Cron Jobs",
  schedulesTitle: "Scheduled Protocols",
  breadcrumbSchedules: "Cron Jobs",
  createSchedule: "Program Cron",
  editSchedule: "Patch Cron",
  deleteSchedule: "Kill Cron",
  cronExpression: "Cron Expression",
  timezoneLabel: "Timezone",
  enabled: "Online",
  disabled: "Offline",
  lastRun: "Last Exec",
  nextRun: "Next Exec",
  noSchedules: "No cron jobs running. Program your first daemon.",
  scheduleCreated: "Cron job deployed",
  scheduleDeleted: "Cron job purged",
  scheduleEnabled: "Cron job activated",
  scheduleDisabled: "Cron job suspended",
  filterSchedules: "Scan cron jobs...",
  scheduleLastError: "Last Glitch",
  onCompleteWebhook: "Success Callback URL",
  onFailureWebhook: "Crash Callback URL",
  webhookPlaceholder: "https://example.com/callback",
  slaDeadline: "SLA Timeout (seconds)",
  slaHint: "0 = no SLA",
  tagsLabel: "Tags",
  tagsPlaceholder: "Add a tag and press Enter",
  bulkActions: "Batch Ops",
  bulkPause: "Freeze All",
  bulkResume: "Unfreeze All",
  bulkRetry: "Re-exec All",
  bulkRestart: "Reboot All",
  bulkTerminate: "Kill All",
  bulkConfirm: "Execute this batch operation on all selected processes?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Batch operation complete",
  retryOnErrors: "Retry on Error Codes",
  retryOnErrorsHint: "Only re-exec on these error patterns",
  envVars: "Environment Variables",
  envVarsHint: "JSON env vars injected at runtime",
};

