import type { ThemeText } from "./types";

export const defaultText: ThemeText = {
  appName: "Rust Conductor",
  tagline: "Conductor-compliant engine",
  dashboard: "Dashboard",
  executions: "Executions",
  workflowDefs: "Workflow Defs",
  taskDefs: "Task Defs",
  taskQueues: "Task Queues",
  startWorkflow: "Start Workflow",
  startingWorkflow: "Starting...",
  search: "Search…",
  newDefinition: "New Definition",
  newTaskDef: "New Task Def",
  viewAll: "View All",
  cancel: "Cancel",
  delete: "Delete",
  edit: "Edit",
  dashboardTitle: "Dashboard",
  dashboardSubtitle: "Rust Conductor orchestration overview",
  running: "Running",
  completed: "Completed",
  failed: "Failed",
  queuedTasks: "Queued Tasks",
  healthy: "Healthy",
  offline: "Offline",
  statusDistribution: "Workflow Status Distribution",
  workflowDefinitions: "Workflow Definitions",
  taskDefinitions: "Task Definitions",
  registeredDefinitions: "registered definitions",
  registeredTaskTypes: "registered task types",
  recentExecutions: "Recent Executions",
  noRecentExecutions: "No recent executions. Start your first workflow!",
  executionsTitle: "Workflow Executions",
  autoRefresh: "Auto-refresh",
  live: "Live",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by name, ID, or correlation ID...",
  allWorkflowTypes: "All Workflow Types",
  results: "results",
  showing: "showing",
  workflow: "Workflow",
  status: "Status",
  started: "Started",
  ended: "Ended",
  actions: "Actions",
  prev: "Prev",
  next: "Next",
  page: "Page",
  of: "of",
  pause: "Pause",
  terminate: "Terminate",
  resume: "Resume",
  restart: "Restart",
  terminateWorkflow: "Terminate Workflow",
  terminateConfirm: "Are you sure you want to terminate this workflow execution? This will stop all running tasks.",
  workflowDefsTitle: "Workflow Definitions",
  filterDefinitions: "Filter definitions...",
  noWorkflowDefs: "No workflow definitions yet. Create your first one!",
  noDefsMatch: "No definitions match your search.",
  name: "Name",
  version: "Version",
  tasks: "Tasks",
  description: "Description",
  timeout: "Timeout",
  startExecution: "Start Execution",
  viewJson: "View JSON",
  cloneAndEdit: "Clone & Edit",
  createWorkflowDef: "Create Workflow Definition",
  editWorkflowDef: "Edit Workflow Definition",
  deleteWorkflowDef: "Delete Workflow Definition",
  taskDefsTitle: "Task Definitions",
  filterTaskDefs: "Filter task definitions...",
  noTaskDefs: "No task definitions yet. Create your first one!",
  retryCount: "Retry Count",
  responseTimeout: "Response Timeout",
  owner: "Owner",
  testRun: "Test Run",
  view: "View",
  createTaskDef: "Create Task Definition",
  deleteTaskDef: "Delete Task Definition",
  taskInput: "Task Input",
  runTest: "Run Test",
  taskQueuesTitle: "Task Queues",
  totalQueued: "total queued",
  filterQueues: "Filter queues…",
  activeQueues: "Active Queues",
  noQueuesMatch: "No queues match your filter",
  noTasksInQueue: "No tasks in queue",
  searchAll: "Search workflows, tasks, pages…",
  pages: "Pages",
  noResults: "No results found.",
  startWorkflowTitle: "Start Workflow Execution",
  startWorkflowDesc: "Select a workflow definition and provide input to start a new execution.",
  workflowLabel: "Workflow *",
  versionLabel: "Version",
  inputLabel: "Input",
  correlationId: "Correlation ID (optional)",
  selectWorkflow: "Select workflow...",
  loadingWorkflows: "Loading workflows…",
  noWorkflowsFound: "No workflow definitions found. Create one first.",
  breadcrumbDashboard: "Dashboard",
  breadcrumbExecutions: "Executions",
  breadcrumbDefinitions: "Workflow Definitions",
  breadcrumbTaskDefs: "Task Definitions",
  breadcrumbQueues: "Task Queues",
  loading: "Loading...",
  toastWorkflowTerminated: "Workflow terminated",
  toastWorkflowPaused: "Workflow paused",
  toastWorkflowResumed: "Workflow resumed",
  toastWorkflowRestarted: "Workflow restarted",
  toastWorkflowRetried: "Workflow retried",
  toastWorkflowStarted: "Workflow started successfully",
  toastWorkflowDefSaved: "Workflow definition saved",
  toastTaskDefCreated: "Task definition(s) created",
  toastDeleted: "Deleted",
  toastInvalidJson: "Invalid JSON input",
  workflowNotFound: "Workflow not found",
  retry: "Retry",
  tasksTab: "Tasks",
  timeline: "Timeline",
  diagram: "Diagram",
  input: "Input",
  output: "Output",
  info: "Info",
  task: "Task",
  type: "Type",
  worker: "Worker",
  reason: "Reason",
  viewSubWorkflow: "View Sub-Workflow",
  loadingWorkflowDef: "Loading workflow definition...",
  workflowIdLabel: "Workflow ID",
  correlationIdLabel: "Correlation ID",
  priority: "Priority",
  updated: "Updated",
  scheduled: "Scheduled",
  pollCount: "Poll Count",
  duration: "Duration",
  confirm: "Confirm",
  pleaseWait: "Please wait...",
  allStatuses: "All",
  createWorkflow: "Create Workflow",
  saveWorkflow: "Save Workflow",
  visualBuilder: "Visual Builder",
  jsonEditor: "JSON Editor",
  saving: "Saving...",
  addTask: "Add Task",
  noTasksYet: "No tasks yet. Click \"Add Task\" to get started.",
  tasksSequentialHint: "Tasks are executed sequentially in the order listed.",
  workflowNameRequired: "Workflow name is required.",
  addAtLeastOneTask: "Add at least one task.",
  allTasksNeedRefName: "All tasks need a reference name.",
  previewJson: "Preview JSON",
  workflowSettings: "Workflow Settings",
  nameRequired: "Name *",
  descriptionPlaceholder: "What does this workflow do?",
  timeoutSeconds: "Timeout (seconds)",
  ownerEmail: "Owner Email",
  failureWorkflow: "Failure Workflow",
  optional: "Optional",
  inputParameters: "Input Parameters",
  inputParamPlaceholder: "Type a parameter name and press Enter",
  inputParamHint: "These become available as sources for task input mapping.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Remove",
  taskType: "Task Type",
  referenceNameRequired: "Reference Name *",
  taskName: "Task Name",
  selectRegisteredTask: "Select a registered task...",
  startDelay: "Start Delay (s)",
  retryLogic: "Retry Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential Backoff",
  retryLinear: "Linear Backoff",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Policy",
  timeoutPolicyTimeOut: "Time Out Workflow",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Retry",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Exec Limit",
  inputKeys: "Input Keys",
  outputKeys: "Output Keys",
  creating: "Creating...",
  createFromJson: "Create from JSON",
  form: "Form",
  json: "JSON",
  subWorkflowConfig: "Sub-Workflow Configuration",
  workflowName: "Workflow Name",
  versionOptional: "Version (optional)",
  parallelBranches: "Parallel Branches",
  addBranch: "Add Branch",
  forkJoinNote: "Note: A JOIN task will be automatically appended.",
  decisionConfig: "Decision/Switch Configuration",
  caseExpression: "Case Expression",
  caseValueParam: "Case Value Param",
  cases: "Cases",
  addCase: "Add Case",
  doWhileConfig: "Do-While Loop Configuration",
  loopCondition: "Loop Condition",
  loopBodyTasks: "Loop Body Tasks",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select parameter...",
  noInputKeys: "This task has no defined input keys.",
  selectTaskForInputs: "Select a registered task to see its input parameters, or switch to JSON mode.",
  provideParamsJson: "Provide the needed parameters in JSON mode.",
  pickSourceHint: "Pick a source first (workflow input or a previous task), then select the specific parameter.",
  testRunDescription: "This will create a test workflow and start it. The task will appear in its queue, ready to be polled.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This action cannot be undone.",
  liveInterval: "Live (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Expand sidebar",
  collapseSidebar: "Collapse sidebar",
  commandPalette: "Command Palette",
  themeLabel: "Theme",
  uiTheme: "UI Theme",
  autoRefreshOn: "Auto-refresh ON (5s)",
  autoRefreshOff: "Auto-refresh OFF",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Type a key and press Enter",
  taskDescriptionHint: "What does this task do?",
  noTimeoutHint: "0 = no timeout",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Reference name",
  caseValue: "Case value",
  diagramStart: "Start",
  diagramEnd: "End",
  diagramFork: "\u2442 Fork",
  diagramJoin: "\u2295 Join",
  diagramSwitch: "\u25C7 Switch",
  diagramSubWf: "\u21B3 SubWF",
  diagramLoop: "\u21BB Loop",
  diagramEvent: "\u26A1 Event",
  diagramHttp: "\uD83C\uDF10 HTTP",
  diagramWait: "\u231B Wait",
  diagramTask: "\u25AA Task",
  testWorkflowDesc: "Auto-generated test workflow for task",
  about: "About",
  aboutTitle: "About Rust Conductor",
  aboutSubtitle: "A fully Rust-based, Conductor-compatible microservice orchestrator — and the technologies that power it.",
  aboutFooter: "Built with ❤ in Rust — open source, high performance, production ready.",
  breadcrumbAbout: "About",
  versionHistory: "Version History",
  compareVersions: "Compare Versions",
  noOtherVersions: "No other versions found.",
  noDifferences: "No differences.",
  added: "Added",
  removed: "Removed",
  customizeDashboard: "Customize Dashboard",
  resetLayout: "Reset Layout",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "Threshold exceeded!",
  configureAlerts: "Configure Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search across all versions",
  replayExecution: "Replay Execution",
  replayDesc: "Re-run this workflow with the same or modified input.",
  dependencyGraph: "Dependencies",
  dependencyGraphDesc: "Workflow sub-workflow dependency graph",
  noDependencies: "No sub-workflow dependencies found.",
  breadcrumbDependencies: "Dependencies",
  schedules: "Schedules",
  schedulesTitle: "Scheduled Workflows",
  breadcrumbSchedules: "Schedules",
  createSchedule: "Create Schedule",
  editSchedule: "Edit Schedule",
  deleteSchedule: "Delete Schedule",
  cronExpression: "Cron Expression",
  timezoneLabel: "Timezone",
  enabled: "Enabled",
  disabled: "Disabled",
  lastRun: "Last Run",
  nextRun: "Next Run",
  noSchedules: "No schedules yet. Create one to run workflows on a timer.",
  scheduleCreated: "Schedule created",
  scheduleDeleted: "Schedule deleted",
  scheduleEnabled: "Schedule enabled",
  scheduleDisabled: "Schedule disabled",
  filterSchedules: "Filter schedules...",
  scheduleLastError: "Last Error",
  onCompleteWebhook: "On Complete Webhook",
  onFailureWebhook: "On Failure Webhook",
  webhookPlaceholder: "https://example.com/webhook",
  slaDeadline: "SLA Deadline (seconds)",
  slaHint: "0 = no SLA tracking",
  tagsLabel: "Tags",
  tagsPlaceholder: "Add a tag and press Enter",
  bulkActions: "Bulk Actions",
  bulkPause: "Pause Selected",
  bulkResume: "Resume Selected",
  bulkRetry: "Retry Selected",
  bulkRestart: "Restart Selected",
  bulkTerminate: "Terminate Selected",
  bulkConfirm: "Apply this action to all selected workflows?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Bulk operation completed",
  retryOnErrors: "Retry On Errors",
  retryOnErrorsHint: "Only retry on these error patterns (empty = retry on all)",
  envVars: "Environment Variables",
  envVarsHint: "JSON object of key-value pairs injected at runtime",
};
