import type { ThemeText } from "./types";

export const forestText: ThemeText = {
  appName: "Grove Keeper",
  tagline: "Tending the roots of orchestration",
  dashboard: "Clearing",
  executions: "Trail Log",
  workflowDefs: "Growth Plans",
  taskDefs: "Seed Catalog",
  taskQueues: "Root Network",
  startWorkflow: "Plant Seed",
  startingWorkflow: "Planting...",
  search: "Forageâ€¦",
  newDefinition: "New Growth Plan",
  newTaskDef: "New Seed Type",
  viewAll: "View Full Trail",
  cancel: "Step Back",
  delete: "Uproot",
  edit: "Prune",
  dashboardTitle: "The Clearing",
  dashboardSubtitle: "A peaceful overview of the grove's activity",
  running: "Growing",
  completed: "Bloomed",
  failed: "Withered",
  queuedTasks: "Dormant Seeds",
  healthy: "Thriving",
  offline: "Drought",
  statusDistribution: "Growth Distribution",
  workflowDefinitions: "Growth Plans",
  taskDefinitions: "Seed Catalog",
  registeredDefinitions: "growth plans mapped",
  registeredTaskTypes: "seed types cataloged",
  recentExecutions: "Recent Growth",
  noRecentExecutions: "No growth yet. Plant your first seed!",
  executionsTitle: "Trail Log",
  autoRefresh: "Wind Updates",
  live: "Listening",
  searchAndFilter: "Search & Sift",
  searchPlaceholder: "Search trails, seeds, or growth IDs...",
  allWorkflowTypes: "All Growth Types",
  results: "findings",
  showing: "uncovering",
  workflow: "Growth",
  status: "State",
  started: "Sprouted",
  ended: "Settled",
  actions: "Tending",
  prev: "Earlier",
  next: "Further",
  page: "Patch",
  of: "of",
  pause: "Rest",
  terminate: "Harvest",
  resume: "Nurture",
  restart: "Replant",
  terminateWorkflow: "Harvest Early",
  terminateConfirm: "Are you sure you want to harvest this growth early? All active branches will be trimmed.",
  workflowDefsTitle: "Growth Plans",
  filterDefinitions: "Search growth plans...",
  noWorkflowDefs: "No growth plans yet. Map your first one!",
  noDefsMatch: "No plans match your search.",
  name: "Name",
  version: "Season",
  tasks: "Steps",
  description: "Notes",
  timeout: "Lifespan",
  startExecution: "Plant",
  viewJson: "View Map",
  cloneAndEdit: "Graft & Edit",
  createWorkflowDef: "Map New Growth Plan",
  editWorkflowDef: "Edit Growth Plan",
  deleteWorkflowDef: "Uproot Growth Plan",
  taskDefsTitle: "Seed Catalog",
  filterTaskDefs: "Search seed catalog...",
  noTaskDefs: "No seeds cataloged yet. Add your first seed type!",
  retryCount: "Germination Tries",
  responseTimeout: "Response Window",
  owner: "Gardener",
  testRun: "Test Sprout",
  view: "Examine",
  createTaskDef: "Catalog New Seed",
  deleteTaskDef: "Remove from Catalog",
  taskInput: "Soil & Nutrients",
  runTest: "Sprout Test",
  taskQueuesTitle: "Root Network",
  totalQueued: "seeds in the soil",
  filterQueues: "Search rootsâ€¦",
  activeQueues: "Active Roots",
  noQueuesMatch: "No roots match your search",
  noTasksInQueue: "All soil is resting â€” no seeds pending",
  searchAll: "Search growth, seeds, rootsâ€¦",
  pages: "Groves",
  noResults: "Nothing found in the grove.",
  startWorkflowTitle: "Plant New Seed",
  startWorkflowDesc: "Choose a growth plan and provide nutrients to begin cultivation.",
  workflowLabel: "Growth Plan *",
  versionLabel: "Season",
  inputLabel: "Nutrients",
  correlationId: "Garden Tag (optional)",
  selectWorkflow: "Choose growth plan...",
  loadingWorkflows: "Consulting the eldersâ€¦",
  noWorkflowsFound: "No growth plans exist. Map one first.",
  breadcrumbDashboard: "Clearing",
  breadcrumbExecutions: "Trail Log",
  breadcrumbDefinitions: "Growth Plans",
  breadcrumbTaskDefs: "Seed Catalog",
  breadcrumbQueues: "Root Network",
  loading: "Listening to the wind...",
  toastWorkflowTerminated: "Growth cycle ended",
  toastWorkflowPaused: "Growth dormant",
  toastWorkflowResumed: "Growth resumed",
  toastWorkflowRestarted: "Cycle replanted",
  toastWorkflowRetried: "Re-seeded",
  toastWorkflowStarted: "Seeds planted!",
  toastWorkflowDefSaved: "Blueprint pressed into bark",
  toastTaskDefCreated: "Seed(s) cataloged",
  toastDeleted: "Composted",
  toastInvalidJson: "Rotten seed data",
  workflowNotFound: "Growth not found in the grove",
  retry: "Re-seed",
  tasksTab: "Branches",
  timeline: "Growth Rings",
  diagram: "Canopy Map",
  input: "Soil",
  output: "Harvest",
  info: "Field Notes",
  task: "Branch",
  type: "Species",
  worker: "Gardener",
  reason: "Blight Report",
  viewSubWorkflow: "View Sub-Growth",
  loadingWorkflowDef: "Reading growth rings...",
  workflowIdLabel: "Growth ID",
  correlationIdLabel: "Plot ID",
  priority: "Urgency",
  updated: "Last Tended",
  scheduled: "Planned",
  pollCount: "Inspections",
  duration: "Growing Season",
  confirm: "Confirm",
  pleaseWait: "Germinating...",
  allStatuses: "All",
  createWorkflow: "Plant Blueprint",
  saveWorkflow: "Save Blueprint",
  visualBuilder: "Garden Planner",
  jsonEditor: "Seed Data",
  saving: "Pressing...",
  addTask: "Add Branch",
  noTasksYet: "No branches yet. Start planting!",
  tasksSequentialHint: "Branches grow sequentially along the trunk.",
  workflowNameRequired: "Blueprint name is required.",
  addAtLeastOneTask: "Add at least one branch.",
  allTasksNeedRefName: "All branches need a tag.",
  previewJson: "Preview Seed Data",
  workflowSettings: "Garden Blueprint",
  nameRequired: "Name *",
  descriptionPlaceholder: "What does this growth cycle do?",
  timeoutSeconds: "Season Length (seconds)",
  ownerEmail: "Head Gardener",
  failureWorkflow: "Blight Response",
  optional: "Optional",
  inputParameters: "Soil Nutrients",
  inputParamPlaceholder: "Type a nutrient name and press Enter",
  inputParamHint: "These become available as resources for branch growth.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Propagate",
  remove: "Prune",
  taskType: "Branch Type",
  referenceNameRequired: "Tag *",
  taskName: "Branch Name",
  selectRegisteredTask: "Select a registered seed...",
  startDelay: "Germination Delay (s)",
  retryLogic: "Regrowth Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Regrowth Delay (s)",
  timeoutPolicy: "Season Policy",
  timeoutPolicyTimeOut: "End Season",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Re-seed",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Plots",
  inputKeys: "Nutrient Keys",
  outputKeys: "Harvest Keys",
  creating: "Planting...",
  createFromJson: "Plant from Seed Data",
  form: "Form",
  json: "Seed Data",
  subWorkflowConfig: "Sub-Growth Configuration",
  workflowName: "Blueprint Name",
  versionOptional: "Season (optional)",
  parallelBranches: "Parallel Branches",
  addBranch: "Add Branch",
  forkJoinNote: "Note: Branches will converge at a natural junction.",
  decisionConfig: "Forking Path",
  caseExpression: "Condition",
  caseValueParam: "Soil Sample",
  cases: "Paths",
  addCase: "Add Path",
  doWhileConfig: "Growth Loop Configuration",
  loopCondition: "Growth Condition",
  loopBodyTasks: "Loop Branches",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select nutrient...",
  noInputKeys: "This branch has no defined nutrient keys.",
  selectTaskForInputs: "Select a registered seed to see its nutrients, or switch to seed data mode.",
  provideParamsJson: "Provide the needed nutrients in seed data mode.",
  pickSourceHint: "Pick a nutrient source first, then select the specific element.",
  testRunDescription: "This will create a test growth cycle and start it. The branch will appear in the root network.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Growing (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Open canopy",
  collapseSidebar: "Close canopy",
  commandPalette: "Forest Guide",
  themeLabel: "Theme",
  uiTheme: "Grove Style",
  autoRefreshOn: "Growth watch ON (5s)",
  autoRefreshOff: "Growth watch OFF",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter a seed and press Enter",
  taskDescriptionHint: "What does this seed do?",
  noTimeoutHint: "0 = no season limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Seedling name",
  caseValue: "Branch value",
  diagramStart: "\uD83C\uDF31 Sprout",
  diagramEnd: "\uD83C\uDF42 Harvest",
  diagramFork: "\u2442 Branch",
  diagramJoin: "\u2295 Merge",
  diagramSwitch: "\u25C7 Fork Path",
  diagramSubWf: "\u21B3 Undergrowth",
  diagramLoop: "\u21BB Cycle",
  diagramEvent: "\u26A1 Signal",
  diagramHttp: "\uD83C\uDF10 Pollen",
  diagramWait: "\u231B Dormant",
  diagramTask: "\u25AA Seed",
  testWorkflowDesc: "Auto-generated test trail for seed",
  about: "Roots",
  aboutTitle: "Roots of the Grove",
  aboutSubtitle: "The seeds and soils that nourish this living system.",
  aboutFooter: "Grown in Rust â€” rooted deep, branching wide.",
  breadcrumbAbout: "Roots",
  versionHistory: "Growth Rings",
  compareVersions: "Compare Rings",
  noOtherVersions: "No other growth rings found.",
  noDifferences: "Rings are identical.",
  added: "Sprouted",
  removed: "Withered",
  customizeDashboard: "Rearrange Clearing",
  resetLayout: "Reset Grove",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "Overgrowth detected!",
  configureAlerts: "Set Watch Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search all growth rings",
  replayExecution: "Regrow Path",
  replayDesc: "Retrace this path with the same or modified seeds.",
  dependencyGraph: "Root Network",
  dependencyGraphDesc: "Root inter-dependency map",
  noDependencies: "No connected roots found.",
  breadcrumbDependencies: "Root Network",
  schedules: "Seasons",
  schedulesTitle: "Seasonal Cycles",
  breadcrumbSchedules: "Seasons",
  createSchedule: "Plan Season",
  editSchedule: "Adjust Season",
  deleteSchedule: "End Season",
  cronExpression: "Growth Cycle",
  timezoneLabel: "Sun Position",
  enabled: "Growing",
  disabled: "Dormant",
  lastRun: "Last Bloom",
  nextRun: "Next Bloom",
  noSchedules: "No seasons planned. Set your first growth cycle!",
  scheduleCreated: "Season planned",
  scheduleDeleted: "Season ended",
  scheduleEnabled: "Season started",
  scheduleDisabled: "Season paused",
  filterSchedules: "Search seasons...",
  scheduleLastError: "Last Blight",
  onCompleteWebhook: "Bloom Notification URL",
  onFailureWebhook: "Blight Notification URL",
  webhookPlaceholder: "https://example.com/grove",
  slaDeadline: "Growing Deadline (seconds)",
  slaHint: "0 = no deadline",
  tagsLabel: "Leaf Tags",
  tagsPlaceholder: "Add a leaf tag and press Enter",
  bulkActions: "Grove Actions",
  bulkPause: "Rest All",
  bulkResume: "Nurture All",
  bulkRetry: "Re-seed All",
  bulkRestart: "Replant All",
  bulkTerminate: "Harvest All",
  bulkConfirm: "Apply this to all selected growth cycles?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Grove operation complete",
  retryOnErrors: "Retry on Blight Types",
  retryOnErrorsHint: "Only re-seed on these blight patterns",
  envVars: "Soil Nutrients",
  envVarsHint: "JSON nutrients injected into the soil",
};

