import type { ThemeText } from "./types";

export const lotrText: ThemeText = {
  appName: "MIDDLE-EARTH",
  tagline: "One workflow to rule them all.",
  dashboard: "The Shire",
  executions: "Quest Log",
  workflowDefs: "Scrolls of Lore",
  taskDefs: "The Armoury",
  taskQueues: "Mines of Moria",
  startWorkflow: "Begin Quest",
  startingWorkflow: "The fellowship departs\u2026",
  search: "Seek\u2026",
  newDefinition: "Inscribe Scroll",
  newTaskDef: "Forge Weapon",
  viewAll: "View All Quests",
  cancel: "Retreat",
  delete: "Cast into Doom",
  edit: "Reforge",
  dashboardTitle: "The Shire",
  dashboardSubtitle: "A peaceful overview of all journeys across Middle-earth",
  running: "On the Road",
  completed: "Quest Complete",
  failed: "Fallen in Battle",
  queuedTasks: "Awaiting the Council",
  healthy: "Light of E\u00e4rendil",
  offline: "Shrouded in Shadow",
  statusDistribution: "Fate of the Fellowship",
  workflowDefinitions: "Scrolls of Lore",
  taskDefinitions: "The Armoury",
  registeredDefinitions: "scrolls inscribed",
  registeredTaskTypes: "weapons forged",
  recentExecutions: "Recent Quests",
  noRecentExecutions: "No quests begun. The road goes ever on and on\u2026",
  executionsTitle: "Quest Log",
  autoRefresh: "Palant\u00edr",
  live: "Seeing",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by fellowship, realm, or quest\u2026",
  allWorkflowTypes: "All Scrolls",
  results: "tales found",
  showing: "revealing",
  workflow: "Quest",
  status: "Fate",
  started: "Departed",
  ended: "Concluded",
  actions: "Deeds",
  prev: "Go Back",
  next: "Onward",
  page: "Chapter",
  of: "of",
  pause: "Make Camp",
  terminate: "Abandon Quest",
  resume: "Resume March",
  restart: "Begin Anew",
  terminateWorkflow: "Abandon This Quest",
  terminateConfirm: "Even the smallest quest can change the course of the future. Are you sure you wish to abandon it?",
  workflowDefsTitle: "Scrolls of Lore",
  filterDefinitions: "Search scrolls\u2026",
  noWorkflowDefs: "No scrolls inscribed. The tale has yet to begin.",
  noDefsMatch: "No scrolls match your search.",
  name: "Name",
  version: "Age",
  tasks: "Steps",
  description: "Chronicle",
  timeout: "Journey Duration",
  startExecution: "Send Forth",
  viewJson: "Read Scroll",
  cloneAndEdit: "Transcribe & Amend",
  createWorkflowDef: "Inscribe New Scroll",
  editWorkflowDef: "Amend Scroll",
  deleteWorkflowDef: "Burn Scroll",
  taskDefsTitle: "The Armoury",
  filterTaskDefs: "Search armoury\u2026",
  noTaskDefs: "The armoury is bare. Forge your first weapon!",
  retryCount: "Endurance",
  responseTimeout: "Swiftness",
  owner: "Bearer",
  testRun: "Test in Battle",
  view: "Inspect",
  createTaskDef: "Forge New Weapon",
  deleteTaskDef: "Destroy Weapon",
  taskInput: "Provisions",
  runTest: "Test!",
  taskQueuesTitle: "Mines of Moria",
  totalQueued: "tasks in the deep",
  filterQueues: "Search the mines\u2026",
  activeQueues: "Active Shafts",
  noQueuesMatch: "No shafts match your search",
  noTasksInQueue: "The mines are empty \u2014 the dwarves delved too deep",
  searchAll: "Search quests, weapons, scrolls\u2026",
  pages: "Realms",
  noResults: "Not all who wander are lost\u2026 but nothing was found.",
  startWorkflowTitle: "Begin a New Quest",
  startWorkflowDesc: "Choose a scroll of lore and prepare provisions for the journey ahead.",
  workflowLabel: "Scroll *",
  versionLabel: "Age",
  inputLabel: "Provisions",
  correlationId: "Fellowship Name (optional)",
  selectWorkflow: "Choose scroll\u2026",
  loadingWorkflows: "Consulting Gandalf\u2026",
  noWorkflowsFound: "No scrolls available. Inscribe one first.",
  breadcrumbDashboard: "The Shire",
  breadcrumbExecutions: "Quest Log",
  breadcrumbDefinitions: "Scrolls of Lore",
  breadcrumbTaskDefs: "The Armoury",
  breadcrumbQueues: "Mines of Moria",
  loading: "The road goes ever on\u2026",
  toastWorkflowTerminated: "Quest abandoned",
  toastWorkflowPaused: "The fellowship rests",
  toastWorkflowResumed: "The march continues",
  toastWorkflowRestarted: "Quest begun anew",
  toastWorkflowRetried: "A second chance is given",
  toastWorkflowStarted: "The fellowship departs!",
  toastWorkflowDefSaved: "Scroll inscribed in the archive",
  toastTaskDefCreated: "Weapon(s) forged",
  toastDeleted: "Cast into the fires of Mount Doom",
  toastInvalidJson: "The scroll is illegible",
  workflowNotFound: "This quest is lost to history",
  retry: "Seek Again",
  tasksTab: "Fellowship",
  timeline: "Chronicle",
  diagram: "Map of Middle-earth",
  input: "Provisions",
  output: "Spoils",
  info: "Lore",
  task: "Companion",
  type: "Race",
  worker: "Bearer",
  reason: "Cause of Defeat",
  viewSubWorkflow: "View Sub-Quest",
  loadingWorkflowDef: "Unrolling ancient scroll...",
  workflowIdLabel: "Quest ID",
  correlationIdLabel: "Fellowship Name",
  priority: "Urgency",
  updated: "Last Seen",
  scheduled: "Mustered",
  pollCount: "Eagle Sightings",
  duration: "Journey Duration",
  confirm: "So Be It",
  pleaseWait: "The Eagles are coming...",
  allStatuses: "All",
  createWorkflow: "Inscribe Scroll",
  saveWorkflow: "Save Scroll",
  visualBuilder: "Council of Elrond",
  jsonEditor: "Ancient Script",
  saving: "Inscribing...",
  addTask: "Add Companion",
  noTasksYet: "The fellowship is empty. Recruit your first companion!",
  tasksSequentialHint: "Companions set out in the order of the march.",
  workflowNameRequired: "Scroll name is required.",
  addAtLeastOneTask: "Recruit at least one companion.",
  allTasksNeedRefName: "All companions need a name.",
  previewJson: "Preview Script",
  workflowSettings: "Quest Parameters",
  nameRequired: "Name *",
  descriptionPlaceholder: "What is this quest's purpose?",
  timeoutSeconds: "Journey Timeout (seconds)",
  ownerEmail: "Quest Giver",
  failureWorkflow: "Retreat Plan",
  optional: "Optional",
  inputParameters: "Provisions",
  inputParamPlaceholder: "Type a provision and press Enter",
  inputParamHint: "These become available as resources for the fellowship.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Dismiss",
  taskType: "Companion Type",
  referenceNameRequired: "Name *",
  taskName: "Companion Name",
  selectRegisteredTask: "Select from the armoury...",
  startDelay: "Departure Delay (s)",
  retryLogic: "Second Chance Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Journey Policy",
  timeoutPolicyTimeOut: "Abandon Quest",
  timeoutPolicyAlert: "Signal Only",
  timeoutPolicyRetry: "Seek Again",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Fellowship Size Limit",
  inputKeys: "Provision Keys",
  outputKeys: "Spoil Keys",
  creating: "Forging...",
  createFromJson: "Inscribe from Script",
  form: "Form",
  json: "Script",
  subWorkflowConfig: "Sub-Quest Configuration",
  workflowName: "Scroll Name",
  versionOptional: "Age (optional)",
  parallelBranches: "Parallel Paths",
  addBranch: "Add Path",
  forkJoinNote: "Note: Paths converge at the rendezvous.",
  decisionConfig: "Council Decision",
  caseExpression: "Condition",
  caseValueParam: "Palant\u00edr Reading",
  cases: "Fates",
  addCase: "Add Fate",
  doWhileConfig: "Siege of Helm's Deep",
  loopCondition: "Siege Condition",
  loopBodyTasks: "Siege Actions",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select provision...",
  noInputKeys: "This companion has no defined provision keys.",
  selectTaskForInputs: "Select from the armoury to see provisions, or switch to script mode.",
  provideParamsJson: "Provide provisions in script mode.",
  pickSourceHint: "Pick a provision source first, then select the specific resource.",
  testRunDescription: "This will form a test fellowship and begin the quest. The companion will appear in the Mines.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Palant\u00edr (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "moments ago",
  secondsAgo: "s past",
  minutesAgo: "m past",
  hoursAgo: "h past",
  daysAgo: "d past",
  expandSidebar: "Unfurl the map",
  collapseSidebar: "Roll the map",
  commandPalette: "Council of Elrond",
  themeLabel: "Theme",
  uiTheme: "Realm Tapestry",
  autoRefreshOn: "Palant\u00edr active (5s)",
  autoRefreshOff: "Palant\u00edr veiled",
  fields: "Fields",
  valueFor: "Worth of",
  typeAndPressEnter: "Inscribe and press Enter",
  typeKeyAndEnter: "Engrave a rune and press Enter",
  taskDescriptionHint: "What quest does this fellowship undertake?",
  noTimeoutHint: "0 = timeless",
  unlimitedHint: "0 = boundless",
  latest: "Latest",
  referenceName: "Deed name",
  caseValue: "Path value",
  diagramStart: "\uD83D\uDDE1 Embark",
  diagramEnd: "\uD83D\uDC51 Return",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Reunite",
  diagramSwitch: "\u25C7 Crossroads",
  diagramSubWf: "\u21B3 Side-Quest",
  diagramLoop: "\u21BB Journey",
  diagramEvent: "\u26A1 Omen",
  diagramHttp: "\uD83C\uDF10 Raven",
  diagramWait: "\u231B Rest",
  diagramTask: "\u25AA Deed",
  testWorkflowDesc: "Auto-generated quest trial for fellowship",
  about: "Appendices",
  aboutTitle: "The Appendices",
  aboutSubtitle: "A chronicle of the tools and crafts that forged this realm.",
  aboutFooter: "Forged in the fires of Rust â€” one engine to rule them all.",
  breadcrumbAbout: "Appendices",
  versionHistory: "Chronicle Ages",
  compareVersions: "Compare Ages",
  noOtherVersions: "No other ages found.",
  noDifferences: "The texts are unchanged.",
  added: "Forged",
  removed: "Destroyed",
  customizeDashboard: "Rearrange The Shire",
  resetLayout: "Reset Shire",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "The beacons are lit!",
  configureAlerts: "Set PalantÃ­r Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search all chronicle ages",
  replayExecution: "Walk the Path Again",
  replayDesc: "Retrace this quest with the same or modified provisions.",
  dependencyGraph: "Fellowship Map",
  dependencyGraphDesc: "Quest dependency chain",
  noDependencies: "No allied quests found.",
  breadcrumbDependencies: "Fellowship Map",
  schedules: "Council Calendar",
  schedulesTitle: "Scheduled Quests",
  breadcrumbSchedules: "Council Calendar",
  createSchedule: "Convene Council",
  editSchedule: "Amend Council",
  deleteSchedule: "Dismiss Council",
  cronExpression: "Quest Cadence",
  timezoneLabel: "Realm Time",
  enabled: "Active",
  disabled: "Dormant",
  lastRun: "Last Departure",
  nextRun: "Next Departure",
  noSchedules: "No quests scheduled. The council awaits.",
  scheduleCreated: "Council convened",
  scheduleDeleted: "Council dismissed",
  scheduleEnabled: "Quest activated",
  scheduleDisabled: "Quest suspended",
  filterSchedules: "Search council...",
  scheduleLastError: "Last Defeat",
  onCompleteWebhook: "Eagle Message URL",
  onFailureWebhook: "Beacon of Gondor URL",
  webhookPlaceholder: "https://example.com/rivendell",
  slaDeadline: "Quest Deadline (seconds)",
  slaHint: "0 = timeless",
  tagsLabel: "Rune Tags",
  tagsPlaceholder: "Engrave a rune and press Enter",
  bulkActions: "Fellowship Orders",
  bulkPause: "Rest All",
  bulkResume: "March All",
  bulkRetry: "Seek Again All",
  bulkRestart: "Begin Anew All",
  bulkTerminate: "Abandon All",
  bulkConfirm: "Issue this order to the entire fellowship?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Fellowship order complete",
  retryOnErrors: "Retry on Perils",
  retryOnErrorsHint: "Only seek again on these peril types",
  envVars: "Provisions",
  envVarsHint: "JSON provisions packed for the journey",
};

