import type { ThemeText } from "./types";

export const oceanText: ThemeText = {
  appName: "Tidal Engine",
  tagline: "Navigating the currents of orchestration",
  dashboard: "Lighthouse",
  executions: "Voyage Log",
  workflowDefs: "Current Charts",
  taskDefs: "Crew Roster",
  taskQueues: "Harbor Queue",
  startWorkflow: "Set Sail",
  startingWorkflow: "Casting off...",
  search: "Scan horizonâ€¦",
  newDefinition: "Chart New Course",
  newTaskDef: "New Crew Spec",
  viewAll: "Full Log",
  cancel: "Dock",
  delete: "Scuttle",
  edit: "Refit",
  dashboardTitle: "The Lighthouse",
  dashboardSubtitle: "A sweeping view across all maritime operations",
  running: "At Sea",
  completed: "Arrived",
  failed: "Shipwrecked",
  queuedTasks: "Anchored",
  healthy: "Clear Skies",
  offline: "Storm Warning",
  statusDistribution: "Fleet Status Overview",
  workflowDefinitions: "Current Charts",
  taskDefinitions: "Crew Roster",
  registeredDefinitions: "routes charted",
  registeredTaskTypes: "crew types registered",
  recentExecutions: "Recent Voyages",
  noRecentExecutions: "No voyages yet. Set sail on your first mission!",
  executionsTitle: "Voyage Log",
  autoRefresh: "Lookout",
  live: "Watching",
  searchAndFilter: "Chart & Filter",
  searchPlaceholder: "Search voyages, crew, or passage IDs...",
  allWorkflowTypes: "All Voyage Types",
  results: "passages found",
  showing: "surfacing",
  workflow: "Voyage",
  status: "Condition",
  started: "Launched",
  ended: "Docked",
  actions: "Helm",
  prev: "Astern",
  next: "Ahead",
  page: "Log",
  of: "of",
  pause: "Drop Anchor",
  terminate: "Abandon Ship",
  resume: "Weigh Anchor",
  restart: "Relaunch",
  terminateWorkflow: "Abandon Ship",
  terminateConfirm: "Are you sure you want to abandon this voyage? All active crew will be recalled.",
  workflowDefsTitle: "Current Charts",
  filterDefinitions: "Search charts...",
  noWorkflowDefs: "No charts drawn. Chart your first course!",
  noDefsMatch: "No charts match your search.",
  name: "Name",
  version: "Edition",
  tasks: "Waypoints",
  description: "Notes",
  timeout: "Voyage Time",
  startExecution: "Launch",
  viewJson: "View Chart",
  cloneAndEdit: "Copy & Refit",
  createWorkflowDef: "Chart New Course",
  editWorkflowDef: "Refit Current Chart",
  deleteWorkflowDef: "Scuttle Chart",
  taskDefsTitle: "Crew Roster",
  filterTaskDefs: "Search crew roster...",
  noTaskDefs: "No crew registered yet. Recruit your first mate!",
  retryCount: "Rallies",
  responseTimeout: "Signal Timeout",
  owner: "Captain",
  testRun: "Sea Trial",
  view: "Inspect",
  createTaskDef: "Recruit Crew",
  deleteTaskDef: "Discharge Crew",
  taskInput: "Provisions",
  runTest: "Begin Trial",
  taskQueuesTitle: "Harbor Queue",
  totalQueued: "vessels at anchor",
  filterQueues: "Search harborâ€¦",
  activeQueues: "Active Berths",
  noQueuesMatch: "No vessels match your search",
  noTasksInQueue: "Harbor is clear â€” all ships at sea",
  searchAll: "Search voyages, crew, harborsâ€¦",
  pages: "Ports",
  noResults: "Nothing found on the horizon.",
  startWorkflowTitle: "Set Sail on New Voyage",
  startWorkflowDesc: "Select a chart and load provisions to begin a new voyage.",
  workflowLabel: "Chart *",
  versionLabel: "Edition",
  inputLabel: "Provisions",
  correlationId: "Ship Name (optional)",
  selectWorkflow: "Choose chart...",
  loadingWorkflows: "Reading the tidesâ€¦",
  noWorkflowsFound: "No charts available. Draw one first.",
  breadcrumbDashboard: "Lighthouse",
  breadcrumbExecutions: "Voyage Log",
  breadcrumbDefinitions: "Current Charts",
  breadcrumbTaskDefs: "Crew Roster",
  breadcrumbQueues: "Harbor Queue",
  loading: "Watching the tide...",
  toastWorkflowTerminated: "Voyage scuttled",
  toastWorkflowPaused: "Anchor dropped",
  toastWorkflowResumed: "Anchor weighed â€” underway",
  toastWorkflowRestarted: "Voyage relaunched",
  toastWorkflowRetried: "Course re-plotted",
  toastWorkflowStarted: "Voyage launched!",
  toastWorkflowDefSaved: "Chart saved to the log",
  toastTaskDefCreated: "Crew assignment(s) filed",
  toastDeleted: "Cast overboard",
  toastInvalidJson: "Corrupt navigational data",
  workflowNotFound: "Voyage not found in the harbor log",
  retry: "Re-plot",
  tasksTab: "Crew",
  timeline: "Tide Chart",
  diagram: "Sea Chart",
  input: "Cargo",
  output: "Catch",
  info: "Ship's Log",
  task: "Crew Member",
  type: "Role",
  worker: "Sailor",
  reason: "Reason for Capsizing",
  viewSubWorkflow: "View Sub-Voyage",
  loadingWorkflowDef: "Reading the sea chart...",
  workflowIdLabel: "Voyage ID",
  correlationIdLabel: "Fleet ID",
  priority: "Urgency",
  updated: "Last Sighted",
  scheduled: "Charted",
  pollCount: "Soundings",
  duration: "Voyage Duration",
  confirm: "Confirm",
  pleaseWait: "Trimming sails...",
  allStatuses: "All",
  createWorkflow: "Chart New Voyage",
  saveWorkflow: "Save Chart",
  visualBuilder: "Chart Room",
  jsonEditor: "Raw Log",
  saving: "Charting...",
  addTask: "Add Crew",
  noTasksYet: "No crew assigned yet. Recruit your first sailor!",
  tasksSequentialHint: "Crew tasks execute in docking order.",
  workflowNameRequired: "Chart name is required.",
  addAtLeastOneTask: "Assign at least one crew member.",
  allTasksNeedRefName: "All crew members need a call sign.",
  previewJson: "Preview Log",
  workflowSettings: "Voyage Settings",
  nameRequired: "Name *",
  descriptionPlaceholder: "What is this voyage's mission?",
  timeoutSeconds: "Timeout (seconds)",
  ownerEmail: "Captain",
  failureWorkflow: "Distress Signal",
  optional: "Optional",
  inputParameters: "Cargo Manifest",
  inputParamPlaceholder: "Type a cargo item and press Enter",
  inputParamHint: "These become available as supplies for crew tasks.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Remove",
  taskType: "Crew Role",
  referenceNameRequired: "Call Sign *",
  taskName: "Crew Name",
  selectRegisteredTask: "Select a registered role...",
  startDelay: "Boarding Delay (s)",
  retryLogic: "Retry Protocol",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Policy",
  timeoutPolicyTimeOut: "Abandon Voyage",
  timeoutPolicyAlert: "Signal Only",
  timeoutPolicyRetry: "Re-plot",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Vessels",
  inputKeys: "Cargo Keys",
  outputKeys: "Catch Keys",
  creating: "Launching...",
  createFromJson: "Chart from Log",
  form: "Form",
  json: "Log",
  subWorkflowConfig: "Sub-Voyage Configuration",
  workflowName: "Chart Name",
  versionOptional: "Edition (optional)",
  parallelBranches: "Parallel Fleets",
  addBranch: "Add Fleet",
  forkJoinNote: "Note: Fleets will rendezvous at a harbor.",
  decisionConfig: "Navigation Decision",
  caseExpression: "Condition",
  caseValueParam: "Wind Reading",
  cases: "Routes",
  addCase: "Add Route",
  doWhileConfig: "Patrol Loop Configuration",
  loopCondition: "Patrol Condition",
  loopBodyTasks: "Patrol Orders",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select cargo...",
  noInputKeys: "This crew role has no defined cargo keys.",
  selectTaskForInputs: "Select a registered role to see its cargo needs, or switch to log mode.",
  provideParamsJson: "Provide the needed cargo in log mode.",
  pickSourceHint: "Pick a supply source first, then select the specific cargo.",
  testRunDescription: "This will chart a test voyage and launch it. The crew task will appear in the harbor queue.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Tide Watch (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Extend gangway",
  collapseSidebar: "Retract gangway",
  commandPalette: "Ship's Log",
  themeLabel: "Theme",
  uiTheme: "Hull Design",
  autoRefreshOn: "Sonar active (5s)",
  autoRefreshOff: "Sonar off",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Log a bearing and press Enter",
  taskDescriptionHint: "What mission does this crew run?",
  noTimeoutHint: "0 = no time limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Call sign",
  caseValue: "Heading value",
  diagramStart: "\u2693 Launch",
  diagramEnd: "\uD83C\uDFF4 Port",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Regroup",
  diagramSwitch: "\u25C7 Navigate",
  diagramSubWf: "\u21B3 Sub-Voyage",
  diagramLoop: "\u21BB Patrol",
  diagramEvent: "\u26A1 Beacon",
  diagramHttp: "\uD83C\uDF10 Radio",
  diagramWait: "\u231B Drift",
  diagramTask: "\u25AA Task",
  testWorkflowDesc: "Auto-generated test voyage for crew",
  about: "Charts",
  aboutTitle: "Nautical Charts",
  aboutSubtitle: "The vessels, instruments, and currents that chart this course.",
  aboutFooter: "Forged in Rust â€” anchored and seaworthy.",
  breadcrumbAbout: "Charts",
  versionHistory: "Ship's Log",
  compareVersions: "Compare Logs",
  noOtherVersions: "No other logs found.",
  noDifferences: "Logs are identical.",
  added: "Charted",
  removed: "Lost at sea",
  customizeDashboard: "Rearrange Bridge",
  resetLayout: "Reset Helm",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "Flood warning!",
  configureAlerts: "Set Sonar Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search all ship's logs",
  replayExecution: "Replay Voyage",
  replayDesc: "Retrace this voyage with the same or modified coordinates.",
  dependencyGraph: "Fleet Map",
  dependencyGraphDesc: "Fleet coordination chart",
  noDependencies: "No fleet connections found.",
  breadcrumbDependencies: "Fleet Map",
  schedules: "Tide Table",
  schedulesTitle: "Scheduled Voyages",
  breadcrumbSchedules: "Tide Table",
  createSchedule: "Set Tide",
  editSchedule: "Adjust Tide",
  deleteSchedule: "Cancel Tide",
  cronExpression: "Tide Pattern",
  timezoneLabel: "Maritime Zone",
  enabled: "Active",
  disabled: "Becalmed",
  lastRun: "Last Departure",
  nextRun: "Next Departure",
  noSchedules: "No tides set. Schedule your first voyage!",
  scheduleCreated: "Tide set",
  scheduleDeleted: "Tide cancelled",
  scheduleEnabled: "Tide activated",
  scheduleDisabled: "Tide suspended",
  filterSchedules: "Search tides...",
  scheduleLastError: "Last Shipwreck",
  onCompleteWebhook: "Arrival Signal URL",
  onFailureWebhook: "Distress Signal URL",
  webhookPlaceholder: "https://example.com/harbor",
  slaDeadline: "Voyage Deadline (seconds)",
  slaHint: "0 = no deadline",
  tagsLabel: "Signal Flags",
  tagsPlaceholder: "Add a flag and press Enter",
  bulkActions: "Fleet Orders",
  bulkPause: "Anchor All",
  bulkResume: "Weigh All Anchors",
  bulkRetry: "Re-plot All",
  bulkRestart: "Relaunch All",
  bulkTerminate: "Scuttle All",
  bulkConfirm: "Issue this to the entire fleet?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Fleet order executed",
  retryOnErrors: "Retry on Storm Types",
  retryOnErrorsHint: "Only re-plot on these weather patterns",
  envVars: "Cargo Manifest",
  envVarsHint: "JSON cargo loaded at departure",
};

