import type { ThemeText } from "./types";

export const pokemonText: ThemeText = {
  appName: "PokÃ©Conductor",
  tagline: "Gotta orchestrate 'em all!",
  dashboard: "PokÃ©dex Hub",
  executions: "Battle Log",
  workflowDefs: "Move Sets",
  taskDefs: "PokÃ©dex",
  taskQueues: "PC Box",
  startWorkflow: "Choose You!",
  startingWorkflow: "Throwing PokÃ© Ball...",
  search: "PokÃ©dex scanâ€¦",
  newDefinition: "New Move Set",
  newTaskDef: "Register PokÃ©mon",
  viewAll: "View Full PokÃ©dex",
  cancel: "Run Away",
  delete: "Release",
  edit: "Evolve",
  dashboardTitle: "PokÃ©dex Hub",
  dashboardSubtitle: "Your journey overview â€” badges, battles, and beyond",
  running: "In Battle",
  completed: "Caught!",
  failed: "Fainted",
  queuedTasks: "In PC Box",
  healthy: "Full HP",
  offline: "Fainted",
  statusDistribution: "Battle Results",
  workflowDefinitions: "Move Sets",
  taskDefinitions: "PokÃ©dex",
  registeredDefinitions: "move sets learned",
  registeredTaskTypes: "PokÃ©mon registered",
  recentExecutions: "Recent Battles",
  noRecentExecutions: "No battles yet. Choose your starter!",
  executionsTitle: "Battle Log",
  autoRefresh: "Auto-Scan",
  live: "Scanning",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by trainer, PokÃ©mon, or battle ID...",
  allWorkflowTypes: "All Move Sets",
  results: "entries found",
  showing: "scanning",
  workflow: "Battle",
  status: "Result",
  started: "Began",
  ended: "Finished",
  actions: "Moves",
  prev: "Back",
  next: "Forward",
  page: "Route",
  of: "of",
  pause: "Switch Out",
  terminate: "Forfeit",
  resume: "Switch In",
  restart: "Rematch",
  terminateWorkflow: "Forfeit Match",
  terminateConfirm: "Are you sure you want to forfeit? All active PokÃ©mon will return to their balls.",
  workflowDefsTitle: "Move Sets",
  filterDefinitions: "Search move sets...",
  noWorkflowDefs: "No move sets yet. Visit Professor Oak!",
  noDefsMatch: "No move sets match your search.",
  name: "Name",
  version: "Gen",
  tasks: "Moves",
  description: "Entry",
  timeout: "Duration",
  startExecution: "Use Move!",
  viewJson: "View Data",
  cloneAndEdit: "Breed & Train",
  createWorkflowDef: "Create Move Set",
  editWorkflowDef: "Edit Move Set",
  deleteWorkflowDef: "Forget Move Set",
  taskDefsTitle: "PokÃ©dex",
  filterTaskDefs: "Search PokÃ©dex...",
  noTaskDefs: "PokÃ©dex is empty. Catch your first PokÃ©mon!",
  retryCount: "PP",
  responseTimeout: "Speed Stat",
  owner: "Trainer",
  testRun: "Test Battle",
  view: "Inspect",
  createTaskDef: "Register PokÃ©mon",
  deleteTaskDef: "Release PokÃ©mon",
  taskInput: "Held Items",
  runTest: "Battle!",
  taskQueuesTitle: "PC Box",
  totalQueued: "PokÃ©mon stored",
  filterQueues: "Search boxesâ€¦",
  activeQueues: "Active Boxes",
  noQueuesMatch: "No boxes match your search",
  noTasksInQueue: "All boxes are empty â€” everyone's on your team",
  searchAll: "Search battles, PokÃ©mon, movesâ€¦",
  pages: "Regions",
  noResults: "No PokÃ©mon found.",
  startWorkflowTitle: "Choose Your PokÃ©mon!",
  startWorkflowDesc: "Pick a move set and equip held items to start a new battle.",
  workflowLabel: "Move Set *",
  versionLabel: "Generation",
  inputLabel: "Held Items",
  correlationId: "Trainer ID (optional)",
  selectWorkflow: "Choose move set...",
  loadingWorkflows: "Consulting Professor Oakâ€¦",
  noWorkflowsFound: "No move sets available. Create one first.",
  breadcrumbDashboard: "PokÃ©dex Hub",
  breadcrumbExecutions: "Battle Log",
  breadcrumbDefinitions: "Move Sets",
  breadcrumbTaskDefs: "PokÃ©dex",
  breadcrumbQueues: "PC Box",
  loading: "Loading PokÃ©dex...",
  toastWorkflowTerminated: "Battle forfeited!",
  toastWorkflowPaused: "PokÃ©mon returned to ball",
  toastWorkflowResumed: "Go! PokÃ©mon!",
  toastWorkflowRestarted: "Rematch started!",
  toastWorkflowRetried: "Used Revive!",
  toastWorkflowStarted: "Battle started!",
  toastWorkflowDefSaved: "Move set registered!",
  toastTaskDefCreated: "PokÃ©mon registered!",
  toastDeleted: "Released to the wild",
  toastInvalidJson: "Invalid PokÃ©dex data",
  workflowNotFound: "Battle not found in your journey",
  retry: "Use Revive",
  tasksTab: "PokÃ©mon",
  timeline: "Battle Timeline",
  diagram: "Battle Map",
  input: "Held Items",
  output: "Rewards",
  info: "Trainer Card",
  task: "PokÃ©mon",
  type: "Type",
  worker: "Trainer",
  reason: "Cause of Fainting",
  viewSubWorkflow: "View Sub-Battle",
  loadingWorkflowDef: "Consulting PokÃ©dex...",
  workflowIdLabel: "Battle ID",
  correlationIdLabel: "Trainer ID",
  priority: "Priority",
  updated: "Last Healed",
  scheduled: "Queued",
  pollCount: "Encounters",
  duration: "Battle Duration",
  confirm: "Confirm",
  pleaseWait: "Healing PokÃ©mon...",
  allStatuses: "All",
  createWorkflow: "Create Move Set",
  saveWorkflow: "Save Move Set",
  visualBuilder: "Visual Builder",
  jsonEditor: "Data Editor",
  saving: "Saving...",
  addTask: "Add Move",
  noTasksYet: "No moves yet. Teach your first move!",
  tasksSequentialHint: "Moves are used sequentially in battle order.",
  workflowNameRequired: "Move set name is required.",
  addAtLeastOneTask: "Add at least one move.",
  allTasksNeedRefName: "All moves need a name.",
  previewJson: "Preview Data",
  workflowSettings: "Move Set Settings",
  nameRequired: "Name *",
  descriptionPlaceholder: "What does this move set do?",
  timeoutSeconds: "PP Timeout (seconds)",
  ownerEmail: "Trainer Email",
  failureWorkflow: "Faint Handler",
  optional: "Optional",
  inputParameters: "Held Items",
  inputParamPlaceholder: "Type an item name and press Enter",
  inputParamHint: "These become available as equipment for battle moves.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Breed",
  remove: "Release",
  taskType: "Move Type",
  referenceNameRequired: "Nickname *",
  taskName: "Move Name",
  selectRegisteredTask: "Select a registered PokÃ©mon...",
  startDelay: "Charge Time (s)",
  retryLogic: "Revival Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Revival Delay (s)",
  timeoutPolicy: "Timeout Policy",
  timeoutPolicyTimeOut: "Forfeit Battle",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Use Revive",
  responseTimeoutLabel: "Speed Stat Timeout (s)",
  concurrentExecLimit: "Party Size Limit",
  inputKeys: "Item Keys",
  outputKeys: "Reward Keys",
  creating: "Catching...",
  createFromJson: "Import from PokÃ©dex",
  form: "Form",
  json: "Data",
  subWorkflowConfig: "Sub-Battle Configuration",
  workflowName: "Move Set Name",
  versionOptional: "Generation (optional)",
  parallelBranches: "Double Battle Lanes",
  addBranch: "Add Lane",
  forkJoinNote: "Note: Lanes converge after the double battle.",
  decisionConfig: "Type Advantage Branch",
  caseExpression: "Condition",
  caseValueParam: "Type Check",
  cases: "Matchups",
  addCase: "Add Matchup",
  doWhileConfig: "Training Loop",
  loopCondition: "Training Condition",
  loopBodyTasks: "Training Moves",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select item...",
  noInputKeys: "This move has no defined item keys.",
  selectTaskForInputs: "Select a PokÃ©mon to see its items, or switch to data mode.",
  provideParamsJson: "Provide items in data mode.",
  pickSourceHint: "Pick an item source first, then select the specific item.",
  testRunDescription: "This will create a test battle and start it. The move will appear in the PC Box.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Scanning (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Open PokÃ©dex",
  collapseSidebar: "Close PokÃ©dex",
  commandPalette: "Quick Move",
  themeLabel: "Theme",
  uiTheme: "Region Style",
  autoRefreshOn: "Radar active (5s)",
  autoRefreshOff: "Radar off",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter a move and press Enter",
  taskDescriptionHint: "Describe this PokÃ©mon's move",
  noTimeoutHint: "0 = no PP limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Move name",
  caseValue: "Route value",
  diagramStart: "\uD83C\uDFAE Begin",
  diagramEnd: "\uD83C\uDFC6 Finish",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Reunite",
  diagramSwitch: "\u25C7 Choose",
  diagramSubWf: "\u21B3 Side-Quest",
  diagramLoop: "\u21BB Grind",
  diagramEvent: "\u26A1 Encounter",
  diagramHttp: "\uD83C\uDF10 Trade",
  diagramWait: "\u231B Rest",
  diagramTask: "\u25AA Move",
  testWorkflowDesc: "Auto-generated test battle for PokÃ©mon",
  about: "PokÃ©dex",
  aboutTitle: "Tech PokÃ©dex",
  aboutSubtitle: "Every technology catalogued â€” gotta catch 'em all!",
  aboutFooter: "Built with Rust â€” it's super effective!",
  breadcrumbAbout: "PokÃ©dex",
  versionHistory: "Evolution Chain",
  compareVersions: "Compare Evolutions",
  noOtherVersions: "No other evolutions found.",
  noDifferences: "Forms are identical.",
  added: "Learned",
  removed: "Forgotten",
  customizeDashboard: "Rearrange PC Box",
  resetLayout: "Reset Box",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "HP critical!",
  configureAlerts: "Set PokÃ©gear Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search all evolutions",
  replayExecution: "Rematch!",
  replayDesc: "Re-battle with the same or modified team.",
  dependencyGraph: "Type Chart",
  dependencyGraphDesc: "Move dependency chain",
  noDependencies: "No linked moves found.",
  breadcrumbDependencies: "Type Chart",
  schedules: "Day Care",
  schedulesTitle: "Scheduled Battles",
  breadcrumbSchedules: "Day Care",
  createSchedule: "Schedule Battle",
  editSchedule: "Edit Schedule",
  deleteSchedule: "Cancel Battle",
  cronExpression: "Battle Schedule",
  timezoneLabel: "Region Time",
  enabled: "Active",
  disabled: "Resting",
  lastRun: "Last Battle",
  nextRun: "Next Battle",
  noSchedules: "No battles scheduled. Set up your first gym match!",
  scheduleCreated: "Battle scheduled!",
  scheduleDeleted: "Battle cancelled",
  scheduleEnabled: "Schedule activated",
  scheduleDisabled: "Schedule paused",
  filterSchedules: "Search schedules...",
  scheduleLastError: "Last Faint",
  onCompleteWebhook: "Victory Callback URL",
  onFailureWebhook: "Faint Callback URL",
  webhookPlaceholder: "https://example.com/pokecenter",
  slaDeadline: "Battle Timer (seconds)",
  slaHint: "0 = no time limit",
  tagsLabel: "Type Tags",
  tagsPlaceholder: "Add a type and press Enter",
  bulkActions: "Party Actions",
  bulkPause: "Recall All",
  bulkResume: "Send All Out",
  bulkRetry: "Revive All",
  bulkRestart: "Rematch All",
  bulkTerminate: "Forfeit All",
  bulkConfirm: "Apply this to all selected battles?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Party action complete!",
  retryOnErrors: "Retry on Status Effects",
  retryOnErrorsHint: "Only use Revive on these status effects",
  envVars: "Held Items",
  envVarsHint: "JSON items equipped at battle start",
};

