import type { ThemeText } from "./types";

export const warcraftText: ThemeText = {
  appName: "War Conductor",
  tagline: "For the Hordeâ€¦ and the Alliance",
  dashboard: "War Room",
  executions: "Battle Log",
  workflowDefs: "Battle Plans",
  taskDefs: "Unit Orders",
  taskQueues: "Rally Points",
  startWorkflow: "Launch Campaign",
  startingWorkflow: "Rallying forces...",
  search: "Scoutâ€¦",
  newDefinition: "Forge New Plan",
  newTaskDef: "New Unit Order",
  viewAll: "View All Battles",
  cancel: "Retreat",
  delete: "Destroy",
  edit: "Reforge",
  dashboardTitle: "War Room",
  dashboardSubtitle: "Strategic command overview of all operations",
  running: "In Battle",
  completed: "Victorious",
  failed: "Defeated",
  queuedTasks: "Awaiting Orders",
  healthy: "Fortified",
  offline: "Under Siege",
  statusDistribution: "Battle Status Overview",
  workflowDefinitions: "Battle Plans",
  taskDefinitions: "Unit Orders",
  registeredDefinitions: "battle plans forged",
  registeredTaskTypes: "unit types trained",
  recentExecutions: "Recent Campaigns",
  noRecentExecutions: "No campaigns yet. Launch your first assault!",
  executionsTitle: "Battle Log",
  autoRefresh: "Scout Reports",
  live: "Scouting",
  searchAndFilter: "Intelligence & Recon",
  searchPlaceholder: "Search campaigns, units, or battle IDs...",
  allWorkflowTypes: "All Campaign Types",
  results: "campaigns found",
  showing: "revealing",
  workflow: "Campaign",
  status: "Report",
  started: "Deployed",
  ended: "Concluded",
  actions: "Commands",
  prev: "Fall Back",
  next: "Advance",
  page: "Front",
  of: "of",
  pause: "Hold Position",
  terminate: "Sound Retreat",
  resume: "Charge!",
  restart: "Regroup",
  terminateWorkflow: "Sound the Retreat",
  terminateConfirm: "Are you sure you want to call a retreat? All active units will stand down.",
  workflowDefsTitle: "Battle Plans",
  filterDefinitions: "Search battle plans...",
  noWorkflowDefs: "No battle plans drawn. Forge your first strategy!",
  noDefsMatch: "No plans match your search.",
  name: "Name",
  version: "Revision",
  tasks: "Units",
  description: "Intelligence",
  timeout: "Duration",
  startExecution: "Deploy",
  viewJson: "View Scroll",
  cloneAndEdit: "Copy & Reforge",
  createWorkflowDef: "Forge Battle Plan",
  editWorkflowDef: "Reforge Battle Plan",
  deleteWorkflowDef: "Burn Battle Plan",
  taskDefsTitle: "Unit Orders",
  filterTaskDefs: "Search unit orders...",
  noTaskDefs: "No unit orders yet. Train your first unit!",
  retryCount: "Rally Attempts",
  responseTimeout: "Response Window",
  owner: "Commander",
  testRun: "Skirmish",
  view: "Inspect",
  createTaskDef: "Draft Unit Order",
  deleteTaskDef: "Disband Unit Order",
  taskInput: "Unit Supplies",
  runTest: "Begin Skirmish",
  taskQueuesTitle: "Rally Points",
  totalQueued: "units awaiting orders",
  filterQueues: "Search rally pointsâ€¦",
  activeQueues: "Active Rally Points",
  noQueuesMatch: "No rally points match your search",
  noTasksInQueue: "All units deployed â€” no one awaiting orders",
  searchAll: "Scout campaigns, units, rally pointsâ€¦",
  pages: "Locations",
  noResults: "No intelligence found.",
  startWorkflowTitle: "Launch New Campaign",
  startWorkflowDesc: "Choose a battle plan and supply resources to begin a new campaign.",
  workflowLabel: "Battle Plan *",
  versionLabel: "Revision",
  inputLabel: "Supplies",
  correlationId: "War Banner (optional)",
  selectWorkflow: "Choose battle plan...",
  loadingWorkflows: "Consulting war councilâ€¦",
  noWorkflowsFound: "No battle plans exist. Forge one first.",
  breadcrumbDashboard: "War Room",
  breadcrumbExecutions: "Battle Log",
  breadcrumbDefinitions: "Battle Plans",
  breadcrumbTaskDefs: "Unit Orders",
  breadcrumbQueues: "Rally Points",
  loading: "Awaiting scouts...",
  toastWorkflowTerminated: "Campaign ended by command",
  toastWorkflowPaused: "Troops holding position",
  toastWorkflowResumed: "Forces marching again",
  toastWorkflowRestarted: "Campaign relaunched",
  toastWorkflowRetried: "Reinforcements sent",
  toastWorkflowStarted: "Campaign launched!",
  toastWorkflowDefSaved: "Battle plan inscribed",
  toastTaskDefCreated: "Unit order(s) filed",
  toastDeleted: "Destroyed",
  toastInvalidJson: "Invalid scroll contents",
  workflowNotFound: "Campaign not found in the archives",
  retry: "Reinforce",
  tasksTab: "Orders",
  timeline: "Battle Timeline",
  diagram: "War Map",
  input: "Supplies",
  output: "Spoils",
  info: "Intel",
  task: "Order",
  type: "Type",
  worker: "Soldier",
  reason: "Cause of Defeat",
  viewSubWorkflow: "View Sub-Campaign",
  loadingWorkflowDef: "Unrolling battle scroll...",
  workflowIdLabel: "Campaign ID",
  correlationIdLabel: "Alliance ID",
  priority: "Priority",
  updated: "Last Report",
  scheduled: "Mustered",
  pollCount: "Scout Reports",
  duration: "Campaign Duration",
  confirm: "Confirm",
  pleaseWait: "Awaiting reinforcements...",
  allStatuses: "All",
  createWorkflow: "Create Battle Plan",
  saveWorkflow: "Save Battle Plan",
  visualBuilder: "War Room",
  jsonEditor: "Scroll Editor",
  saving: "Inscribing...",
  addTask: "Add Order",
  noTasksYet: "No orders yet. Command your troops!",
  tasksSequentialHint: "Orders are executed sequentially as written.",
  workflowNameRequired: "Battle plan name is required.",
  addAtLeastOneTask: "Add at least one order.",
  allTasksNeedRefName: "All orders need a codename.",
  previewJson: "Preview Scroll",
  workflowSettings: "Battle Plan Settings",
  nameRequired: "Codename *",
  descriptionPlaceholder: "What is this campaign's objective?",
  timeoutSeconds: "Time Limit (seconds)",
  ownerEmail: "Commander",
  failureWorkflow: "Retreat Plan",
  optional: "Optional",
  inputParameters: "War Supplies",
  inputParamPlaceholder: "Type a supply name and press Enter",
  inputParamHint: "These become available as resources for troop orders.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Duplicate",
  remove: "Remove",
  taskType: "Order Type",
  referenceNameRequired: "Codename *",
  taskName: "Order Name",
  selectRegisteredTask: "Select a registered unit...",
  startDelay: "March Delay (s)",
  retryLogic: "Retry Tactics",
  retryFixed: "Fixed",
  retryExponential: "Exponential Siege",
  retryLinear: "Linear Advance",
  retryDelay: "Retry Delay (s)",
  timeoutPolicy: "Timeout Strategy",
  timeoutPolicyTimeOut: "Abort Campaign",
  timeoutPolicyAlert: "Signal Only",
  timeoutPolicyRetry: "Reinforce",
  responseTimeoutLabel: "Response Timeout (s)",
  concurrentExecLimit: "Concurrent Squads",
  inputKeys: "Supply Keys",
  outputKeys: "Spoil Keys",
  creating: "Summoning...",
  createFromJson: "Create from Scroll",
  form: "Form",
  json: "Scroll",
  subWorkflowConfig: "Sub-Campaign Configuration",
  workflowName: "Campaign Name",
  versionOptional: "Age (optional)",
  parallelBranches: "Flanking Columns",
  addBranch: "Add Flank",
  forkJoinNote: "Note: A rally point will be automatically appended.",
  decisionConfig: "Strategic Decision",
  caseExpression: "Condition",
  caseValueParam: "Scout Report Value",
  cases: "Outcomes",
  addCase: "Add Outcome",
  doWhileConfig: "Siege Loop Configuration",
  loopCondition: "Siege Condition",
  loopBodyTasks: "Siege Orders",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select supply...",
  noInputKeys: "This order has no defined supply keys.",
  selectTaskForInputs: "Select a registered unit to see its supply needs, or switch to scroll mode.",
  provideParamsJson: "Provide the needed supplies in scroll mode.",
  pickSourceHint: "Pick a supply source first, then select the specific resource.",
  testRunDescription: "This will create a test campaign and deploy it. The order will appear in its rally point.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), scrolls, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Scouting (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "moments ago",
  secondsAgo: "s past",
  minutesAgo: "m past",
  hoursAgo: "h past",
  daysAgo: "d past",
  expandSidebar: "Open war table",
  collapseSidebar: "Collapse war table",
  commandPalette: "War Orders",
  themeLabel: "Theme",
  uiTheme: "Realm Style",
  autoRefreshOn: "Scout active (5s)",
  autoRefreshOff: "Scout idle",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter a rune and press Enter",
  taskDescriptionHint: "Describe this order's purpose",
  noTimeoutHint: "0 = no retreat timer",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Codename",
  caseValue: "Case value",
  diagramStart: "\u2694 Begin",
  diagramEnd: "\uD83C\uDFF0 End",
  diagramFork: "\u2442 Fork",
  diagramJoin: "\u2295 Rally",
  diagramSwitch: "\u25C7 Decision",
  diagramSubWf: "\u21B3 Sub-Campaign",
  diagramLoop: "\u21BB Siege",
  diagramEvent: "\u26A1 Signal",
  diagramHttp: "\uD83C\uDF10 Dispatch",
  diagramWait: "\u231B Hold",
  diagramTask: "\u25AA Order",
  testWorkflowDesc: "Auto-generated test campaign for unit",
  about: "Lore",
  aboutTitle: "Lore of the War Conductor",
  aboutSubtitle: "The forges that built this war machine â€” every weapon and alliance.",
  aboutFooter: "Forged in Rust â€” Lok'tar ogar!",
  breadcrumbAbout: "Lore",
  versionHistory: "Ancient Scrolls",
  compareVersions: "Compare Scrolls",
  noOtherVersions: "No other scrolls found.",
  noDifferences: "Scrolls are identical.",
  added: "Reinforced",
  removed: "Disbanded",
  customizeDashboard: "Rearrange War Room",
  resetLayout: "Reset Formation",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "Forces overwhelmed!",
  configureAlerts: "Set Watchtower Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search all scroll versions",
  replayExecution: "Replay Battle",
  replayDesc: "Re-launch this campaign with the same or modified orders.",
  dependencyGraph: "Alliance Map",
  dependencyGraphDesc: "Campaign dependency chain",
  noDependencies: "No allied campaigns found.",
  breadcrumbDependencies: "Alliance Map",
  schedules: "War Drums",
  schedulesTitle: "Scheduled Campaigns",
  breadcrumbSchedules: "War Drums",
  createSchedule: "Sound the Drums",
  editSchedule: "Revise Orders",
  deleteSchedule: "Silence the Drums",
  cronExpression: "Battle Cadence",
  timezoneLabel: "Realm Time",
  enabled: "Active",
  disabled: "Dormant",
  lastRun: "Last Assault",
  nextRun: "Next Assault",
  noSchedules: "No war drums sounding. Schedule your first campaign!",
  scheduleCreated: "War drums set",
  scheduleDeleted: "Drums silenced",
  scheduleEnabled: "Drums activated",
  scheduleDisabled: "Drums silenced",
  filterSchedules: "Search war drums...",
  scheduleLastError: "Last Defeat",
  onCompleteWebhook: "Victory Herald URL",
  onFailureWebhook: "Defeat Herald URL",
  webhookPlaceholder: "https://example.com/herald",
  slaDeadline: "Campaign Deadline (seconds)",
  slaHint: "0 = no deadline",
  tagsLabel: "War Banners",
  tagsPlaceholder: "Add a banner and press Enter",
  bulkActions: "Mass Orders",
  bulkPause: "Hold All",
  bulkResume: "Charge All",
  bulkRetry: "Reinforce All",
  bulkRestart: "Regroup All",
  bulkTerminate: "Retreat All",
  bulkConfirm: "Issue this order to all selected campaigns?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Mass order executed",
  retryOnErrors: "Retry on Specific Defeats",
  retryOnErrorsHint: "Only reinforce on these defeat patterns",
  envVars: "War Supplies",
  envVarsHint: "JSON supplies injected at deployment",
};

