import type { ThemeText } from "./types";

export const yugiohText: ThemeText = {
  appName: "Duel Engine",
  tagline: "It's time to d-d-d-duel!",
  dashboard: "Duel Arena",
  executions: "Duel Log",
  workflowDefs: "Deck Builder",
  taskDefs: "Card Catalog",
  taskQueues: "Graveyard",
  startWorkflow: "Activate!",
  startingWorkflow: "Drawing card...",
  search: "Search deckâ€¦",
  newDefinition: "Build Deck",
  newTaskDef: "New Card",
  viewAll: "View All Duels",
  cancel: "End Turn",
  delete: "Banish",
  edit: "Re-equip",
  dashboardTitle: "Duel Arena",
  dashboardSubtitle: "The heart of the cards guides your orchestration",
  running: "Dueling",
  completed: "Victory",
  failed: "Defeated",
  queuedTasks: "Set Cards",
  healthy: "Life Points Full",
  offline: "Life Points Zero",
  statusDistribution: "Duel Results Distribution",
  workflowDefinitions: "Deck Builder",
  taskDefinitions: "Card Catalog",
  registeredDefinitions: "decks constructed",
  registeredTaskTypes: "cards cataloged",
  recentExecutions: "Recent Duels",
  noRecentExecutions: "No duels yet. Activate your first trap card!",
  executionsTitle: "Duel Log",
  autoRefresh: "Auto-Draw",
  live: "Drawing",
  searchAndFilter: "Search & Filter",
  searchPlaceholder: "Search by duelist, card, or duel ID...",
  allWorkflowTypes: "All Deck Types",
  results: "records found",
  showing: "revealing",
  workflow: "Duel",
  status: "Result",
  started: "Initiated",
  ended: "Concluded",
  actions: "Moves",
  prev: "Prev Turn",
  next: "Next Turn",
  page: "Turn",
  of: "of",
  pause: "Set Face-Down",
  terminate: "Surrender",
  resume: "Flip Summon",
  restart: "Re-Duel",
  terminateWorkflow: "Surrender Duel",
  terminateConfirm: "Are you sure you want to surrender? All monsters on the field will be destroyed.",
  workflowDefsTitle: "Deck Builder",
  filterDefinitions: "Search decks...",
  noWorkflowDefs: "No decks built. Believe in the heart of the cards!",
  noDefsMatch: "No decks match your search.",
  name: "Card Name",
  version: "Edition",
  tasks: "Cards",
  description: "Lore",
  timeout: "Turn Limit",
  startExecution: "Activate",
  viewJson: "View Card",
  cloneAndEdit: "Copy & Re-equip",
  createWorkflowDef: "Construct New Deck",
  editWorkflowDef: "Modify Deck",
  deleteWorkflowDef: "Banish Deck",
  taskDefsTitle: "Card Catalog",
  filterTaskDefs: "Search cards...",
  noTaskDefs: "No cards in your collection. Open your first booster pack!",
  retryCount: "Summon Limit",
  responseTimeout: "Chain Timer",
  owner: "Duelist",
  testRun: "Test Summon",
  view: "Inspect",
  createTaskDef: "Add Card to Catalog",
  deleteTaskDef: "Banish Card",
  taskInput: "Tribute Cost",
  runTest: "Summon!",
  taskQueuesTitle: "Graveyard",
  totalQueued: "cards in graveyard",
  filterQueues: "Search graveyardâ€¦",
  activeQueues: "Active Zones",
  noQueuesMatch: "No cards match your search",
  noTasksInQueue: "Graveyard is empty â€” all monsters are on the field",
  searchAll: "Search duels, cards, decksâ€¦",
  pages: "Zones",
  noResults: "No cards found in the shadow realm.",
  startWorkflowTitle: "Activate New Duel",
  startWorkflowDesc: "Choose a deck and set tribute to begin a new duel.",
  workflowLabel: "Deck *",
  versionLabel: "Edition",
  inputLabel: "Tribute",
  correlationId: "Duelist Tag (optional)",
  selectWorkflow: "Choose deck...",
  loadingWorkflows: "Shuffling deckâ€¦",
  noWorkflowsFound: "No decks available. Build one first.",
  breadcrumbDashboard: "Duel Arena",
  breadcrumbExecutions: "Duel Log",
  breadcrumbDefinitions: "Deck Builder",
  breadcrumbTaskDefs: "Card Catalog",
  breadcrumbQueues: "Graveyard",
  loading: "Drawing cards...",
  toastWorkflowTerminated: "Duel surrendered",
  toastWorkflowPaused: "Card set face-down",
  toastWorkflowResumed: "Card flip summoned",
  toastWorkflowRestarted: "Duel restarted",
  toastWorkflowRetried: "Monster reborn activated",
  toastWorkflowStarted: "It's time to duel!",
  toastWorkflowDefSaved: "Deck saved to binder",
  toastTaskDefCreated: "Card(s) added to catalog",
  toastDeleted: "Banished to shadow realm",
  toastInvalidJson: "Corrupted card data",
  workflowNotFound: "Duel not found in the archives",
  retry: "Monster Reborn",
  tasksTab: "Monsters",
  timeline: "Duel Timeline",
  diagram: "Field Layout",
  input: "Hand",
  output: "Rewards",
  info: "Duelist Profile",
  task: "Monster",
  type: "Attribute",
  worker: "Duelist",
  reason: "Cause of Defeat",
  viewSubWorkflow: "View Sub-Duel",
  loadingWorkflowDef: "Shuffling deck...",
  workflowIdLabel: "Duel ID",
  correlationIdLabel: "Duelist Tag",
  priority: "Star Level",
  updated: "Last Phase",
  scheduled: "Set",
  pollCount: "Draw Count",
  duration: "Duel Duration",
  confirm: "Activate",
  pleaseWait: "Drawing card...",
  allStatuses: "All",
  createWorkflow: "Construct Deck",
  saveWorkflow: "Save Deck",
  visualBuilder: "Deck Builder",
  jsonEditor: "Card Data",
  saving: "Saving...",
  addTask: "Add Card",
  noTasksYet: "No cards in deck. Open your first booster!",
  tasksSequentialHint: "Cards are played in turn order.",
  workflowNameRequired: "Deck name is required.",
  addAtLeastOneTask: "Add at least one card.",
  allTasksNeedRefName: "All cards need a name.",
  previewJson: "Preview Card Data",
  workflowSettings: "Deck Configuration",
  nameRequired: "Deck Name *",
  descriptionPlaceholder: "What is this deck's strategy?",
  timeoutSeconds: "Turn Timer (seconds)",
  ownerEmail: "Duelist Email",
  failureWorkflow: "Trap Card",
  optional: "Optional",
  inputParameters: "Tribute Materials",
  inputParamPlaceholder: "Type a material name and press Enter",
  inputParamHint: "These become available as tribute for card summons.",
  unnamed: "(unnamed)",
  moveUp: "Move up",
  moveDown: "Move down",
  duplicate: "Copy Card",
  remove: "Banish",
  taskType: "Card Type",
  referenceNameRequired: "Card Name *",
  taskName: "Card Name",
  selectRegisteredTask: "Select a card from catalog...",
  startDelay: "Set Delay (s)",
  retryLogic: "Resummon Logic",
  retryFixed: "Fixed",
  retryExponential: "Exponential",
  retryLinear: "Linear",
  retryDelay: "Resummon Delay (s)",
  timeoutPolicy: "Timer Policy",
  timeoutPolicyTimeOut: "Disqualify",
  timeoutPolicyAlert: "Alert Only",
  timeoutPolicyRetry: "Monster Reborn",
  responseTimeoutLabel: "Chain Timer (s)",
  concurrentExecLimit: "Max Field Monsters",
  inputKeys: "Tribute Keys",
  outputKeys: "Reward Keys",
  creating: "Summoning...",
  createFromJson: "Import from Binder",
  form: "Form",
  json: "Card Data",
  subWorkflowConfig: "Sub-Duel Configuration",
  workflowName: "Deck Name",
  versionOptional: "Edition (optional)",
  parallelBranches: "Tag Duel Lanes",
  addBranch: "Add Lane",
  forkJoinNote: "Note: Lanes converge at end phase.",
  decisionConfig: "Trap Card Decision",
  caseExpression: "Activation Condition",
  caseValueParam: "Chain Link",
  cases: "Responses",
  addCase: "Add Response",
  doWhileConfig: "Infinite Loop Configuration",
  loopCondition: "Loop Condition",
  loopBodyTasks: "Loop Cards",
  source: "Source...",
  customValue: "Custom value",
  selectParameter: "Select tribute...",
  noInputKeys: "This card has no defined tribute keys.",
  selectTaskForInputs: "Select a card to see its tributes, or switch to card data mode.",
  provideParamsJson: "Provide tributes in card data mode.",
  pickSourceHint: "Pick a tribute source first, then select the specific material.",
  testRunDescription: "This will create a test duel and activate it. The card will appear in the graveyard queue.",
  autoParseHint: "Values are auto-parsed: numbers, booleans (true/false), JSON objects/arrays, or strings.",
  deleteConfirmSuffix: "This cannot be undone.",
  liveInterval: "Drawing (5s)",
  copyToClipboard: "Copy to clipboard",
  none: "none",
  justNow: "just now",
  secondsAgo: "s ago",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  expandSidebar: "Open spell book",
  collapseSidebar: "Close spell book",
  commandPalette: "Card Search",
  themeLabel: "Theme",
  uiTheme: "Duel Style",
  autoRefreshOn: "Duel tracker ON (5s)",
  autoRefreshOff: "Duel tracker OFF",
  fields: "Fields",
  valueFor: "Value for",
  typeAndPressEnter: "Type and press Enter",
  typeKeyAndEnter: "Enter an attribute and press Enter",
  taskDescriptionHint: "Describe this card's effect",
  noTimeoutHint: "0 = no turn limit",
  unlimitedHint: "0 = unlimited",
  latest: "Latest",
  referenceName: "Card name",
  caseValue: "Gate value",
  diagramStart: "\uD83C\uDCCF Draw",
  diagramEnd: "\uD83C\uDFC6 Victory",
  diagramFork: "\u2442 Split",
  diagramJoin: "\u2295 Fusion",
  diagramSwitch: "\u25C7 Trap",
  diagramSubWf: "\u21B3 Chain",
  diagramLoop: "\u21BB Turn",
  diagramEvent: "\u26A1 Activate",
  diagramHttp: "\uD83C\uDF10 Link",
  diagramWait: "\u231B Set",
  diagramTask: "\u25AA Card",
  testWorkflowDesc: "Auto-generated test duel for card",
  about: "Deck List",
  aboutTitle: "Deck List â€” Tech Cards",
  aboutSubtitle: "Every card in the engine's deck â€” revealed face-up.",
  aboutFooter: "Assembled in Rust â€” an unstoppable combo.",
  breadcrumbAbout: "Deck List",
  versionHistory: "Card Errata",
  compareVersions: "Compare Errata",
  noOtherVersions: "No other prints found.",
  noDifferences: "Cards are identical.",
  added: "Summoned",
  removed: "Banished",
  customizeDashboard: "Rearrange Field",
  resetLayout: "Reset Field",
  widgetVisible: "Visible",
  alertThreshold: "Alert Threshold",
  thresholdExceeded: "Life points critical!",
  configureAlerts: "Set Trap Alerts",
  clearThreshold: "Clear",
  searchAllVersions: "Search all card prints",
  replayExecution: "Replay Duel",
  replayDesc: "Re-duel with the same or modified deck.",
  dependencyGraph: "Fusion Chart",
  dependencyGraphDesc: "Card fusion dependency map",
  noDependencies: "No fusion materials found.",
  breadcrumbDependencies: "Fusion Chart",
  schedules: "Turn Timer",
  schedulesTitle: "Scheduled Duels",
  breadcrumbSchedules: "Turn Timer",
  createSchedule: "Set Timer",
  editSchedule: "Adjust Timer",
  deleteSchedule: "Cancel Duel",
  cronExpression: "Duel Schedule",
  timezoneLabel: "Arena Time",
  enabled: "Active",
  disabled: "Face-Down",
  lastRun: "Last Duel",
  nextRun: "Next Duel",
  noSchedules: "No duels scheduled. Set your first tournament!",
  scheduleCreated: "Duel scheduled!",
  scheduleDeleted: "Duel cancelled",
  scheduleEnabled: "Timer activated",
  scheduleDisabled: "Timer paused",
  filterSchedules: "Search duels...",
  scheduleLastError: "Last Trap Card",
  onCompleteWebhook: "Victory Herald URL",
  onFailureWebhook: "Defeat Herald URL",
  webhookPlaceholder: "https://example.com/arena",
  slaDeadline: "Turn Limit (seconds)",
  slaHint: "0 = no limit",
  tagsLabel: "Card Tags",
  tagsPlaceholder: "Add a tag and press Enter",
  bulkActions: "Field Actions",
  bulkPause: "Set All Face-Down",
  bulkResume: "Flip All",
  bulkRetry: "Monster Reborn All",
  bulkRestart: "Re-Duel All",
  bulkTerminate: "Surrender All",
  bulkConfirm: "Apply this to all selected duels?",
  selectedCount: "selected",
  selectAll: "Select All",
  deselectAll: "Deselect All",
  bulkSuccess: "Field action complete",
  retryOnErrors: "Retry on Trap Effects",
  retryOnErrorsHint: "Only resummon on these trap effects",
  envVars: "Spell Cards",
  envVarsHint: "JSON spells equipped at duel start",
};

